// Autogenerated by HotRod -- Do not edit.

package com.myapp.daos.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import com.myapp.daos.TaskImpl;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class TaskDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<com.myapp.daos.TaskImpl> selectByExample(final com.myapp.daos.TaskImpl example, final TaskOrderBy... orderBies)
      {
    DaoWithOrder<com.myapp.daos.TaskImpl, TaskOrderBy> dwo = //
        new DaoWithOrder<com.myapp.daos.TaskImpl, TaskOrderBy>(example, orderBies);
    return this.sqlSession.selectList("com.myapp.daos.primitives.task.selectByExample", dwo);
  }

  public Cursor<com.myapp.daos.TaskImpl> selectByExampleCursor(final com.myapp.daos.TaskImpl example, final TaskOrderBy... orderBies)
      {
    DaoWithOrder<com.myapp.daos.TaskImpl, TaskOrderBy> dwo = //
        new DaoWithOrder<com.myapp.daos.TaskImpl, TaskOrderBy>(example, orderBies);
    return new MyBatisCursor<com.myapp.daos.TaskImpl>(this.sqlSession.selectCursor("com.myapp.daos.primitives.task.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<com.myapp.daos.TaskImpl> selectByCriteria(final TaskDAO.TaskTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<com.myapp.daos.TaskImpl>(from, this.liveSQLDialect, this.sqlSession,
        predicate, "com.myapp.daos.primitives.task.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public int insert(final com.myapp.daos.TaskImpl vo) {
    String id = "com.myapp.daos.primitives.task.insert";
    return this.sqlSession.insert(id, vo);
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int updateByExample(final com.myapp.daos.TaskImpl example, final com.myapp.daos.TaskImpl updateValues) {
    UpdateByExampleDao<com.myapp.daos.TaskImpl> fvd = //
      new UpdateByExampleDao<com.myapp.daos.TaskImpl>(example, updateValues);
    return this.sqlSession.update("com.myapp.daos.primitives.task.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final com.myapp.daos.TaskImpl example) {
    return this.sqlSession.delete("com.myapp.daos.primitives.task.deleteByExample", example);
  }

  // DAO ordering

  public enum TaskOrderBy implements OrderBy {

    ID("exampledb.schema3.task", "id", true), //
    ID$DESC("exampledb.schema3.task", "id", false), //
    NAME("exampledb.schema3.task", "name", true), //
    NAME$DESC("exampledb.schema3.task", "name", false), //
    NAME$CASEINSENSITIVE("exampledb.schema3.task", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("exampledb.schema3.task", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("exampledb.schema3.task", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("exampledb.schema3.task", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("exampledb.schema3.task", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("exampledb.schema3.task", "lower(name), name", true), //
    DUE("exampledb.schema3.task", "due", true), //
    DUE$DESC("exampledb.schema3.task", "due", false);

    private TaskOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static TaskTable newTable() {
    return new TaskTable();
  }

  public static TaskTable newTable(final String alias) {
    return new TaskTable(alias);
  }

  public static class TaskTable extends Table {

    // Properties

    public NumberColumn id;
    public StringColumn name;
    public DateTimeColumn due;

    // Constructors

    TaskTable() {
      super("EXAMPLEDB", "SCHEMA3", "TASK", "Table", null);
      initialize();
    }

    TaskTable(final String alias) {
      super("EXAMPLEDB", "SCHEMA3", "TASK", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "ID", "id");
      this.name = new StringColumn(this, "NAME", "name");
      this.due = new DateTimeColumn(this, "DUE", "due");
    }

  }

}
