// Generated by HotRod 5.1.19-SNAPSHOT on Apr 12, 2026 at 17:20:31

package app.persistence.layout;

import java.io.Serializable;

import org.hotrod.json.JSONObject;

public class OrderTypeALayout implements Serializable {

  private static final long serialVersionUID = 1L;

  // Layout Properties (table columns)

  protected Integer id = null; // Type Source: STATIC_DIALECT_RULE, rule #D9
  protected String orderCase = null; // Type Source: STATIC_DIALECT_RULE, rule #D14

  // getters & setters

  public Integer getId() {
    return this.id;
  }

  public void setId(final Integer id) {
    this.id = id;
  }

  public String getOrderCase() {
    return this.orderCase;
  }

  public void setOrderCase(final String orderCase) {
    this.orderCase = orderCase;
  }

  // to string

  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- id=" + this.id + "\n");
    sb.append("- orderCase=" + this.orderCase);
    return sb.toString();
  }

  // to JSON Object

  public JSONObject toJSONObject() {
    JSONObject obj = new JSONObject();
    obj.addProperty("id", this.id);
    obj.addProperty("orderCase", this.orderCase);
    return obj;
  }

  // to JSON String

  public String toJSON() {
    return toJSONObject().render();
  }

}
