// Generated by HotRod 5.1.11 on Feb 16, 2026 at 13:23:14

package app.persistence.resources;

import java.util.ArrayList;
import java.util.List;

import org.hotrod.livesql.LayerConfiguration;
import org.hotrod.livesql.queries.typesolver.TypeRule;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class LayerResourcesBean {

  @Bean
  public LayerConfiguration layerConfig() {
    List<TypeRule> rules = new ArrayList<>();
    return () -> rules;
  }

}
