// Autogenerated by HotRod -- Do not edit.

package app.persistence.layout;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.hotrod.json.JSONObject;

public class AccountLayout implements Serializable {

  private static final long serialVersionUID = 1L;

  // Layout Properties (table columns)

  protected Integer id = null;
  protected String name = null;
  protected String type = null;
  protected Double balance = null;
  protected Integer active = null;
  protected LocalDateTime updatedAt = null;
  protected Integer version = null;

  // getters & setters

  public Integer getId() {
    return this.id;
  }

  public void setId(final Integer id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(final String name) {
    this.name = name;
  }

  public String getType() {
    return this.type;
  }

  public void setType(final String type) {
    this.type = type;
  }

  public Double getBalance() {
    return this.balance;
  }

  public void setBalance(final Double balance) {
    this.balance = balance;
  }

  public Integer getActive() {
    return this.active;
  }

  public void setActive(final Integer active) {
    this.active = active;
  }

  public LocalDateTime getUpdatedAt() {
    return this.updatedAt;
  }

  public void setUpdatedAt(final LocalDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Integer getVersion() {
    return this.version;
  }

  public void setVersion(final Integer version) {
    this.version = version;
  }

  // to string

  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- id=" + this.id + "\n");
    sb.append("- name=" + this.name + "\n");
    sb.append("- type=" + this.type + "\n");
    sb.append("- balance=" + this.balance + "\n");
    sb.append("- active=" + this.active + "\n");
    sb.append("- updatedAt=" + this.updatedAt + "\n");
    sb.append("- version=" + this.version);
    return sb.toString();
  }

  // to JSON Object

  public JSONObject toJSONObject() {
    JSONObject obj = new JSONObject();
    obj.addProperty("id", this.id);
    obj.addProperty("name", this.name);
    obj.addProperty("type", this.type);
    obj.addProperty("balance", this.balance);
    obj.addProperty("active", this.active);
    obj.addProperty("updatedAt", this.updatedAt);
    obj.addProperty("version", this.version);
    return obj;
  }

  // to JSON String

  public String toJSON() {
    return toJSONObject().render();
  }

}
