// Autogenerated by HotRod -- Do not edit.

package app.persistence.layout;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.ZonedDateTime;

import org.hotrod.json.JSONObject;

public class DatesLayout implements Serializable {

  private static final long serialVersionUID = 1L;

  // Layout Properties (table columns)

  protected Integer id = null; // NUMBER
  protected Date dat1 = null; // DATE
  protected Timestamp dat2 = null; // TIMESTAMP(6)
  protected ZonedDateTime dat3 = null; // TIMESTAMP(6) WITH TIME ZONE
  protected ZonedDateTime dat4 = null; // TIMESTAMP(6) WITH LOCAL TIME ZONE

  // getters & setters

  public Integer getId() {
    return this.id;
  }

  public void setId(final Integer id) {
    this.id = id;
  }

  public Date getDat1() {
    return this.dat1;
  }

  public void setDat1(final Date dat1) {
    this.dat1 = dat1;
  }

  public Timestamp getDat2() {
    return this.dat2;
  }

  public void setDat2(final Timestamp dat2) {
    this.dat2 = dat2;
  }

  public ZonedDateTime getDat3() {
    return this.dat3;
  }

  public void setDat3(final ZonedDateTime dat3) {
    this.dat3 = dat3;
  }

  public ZonedDateTime getDat4() {
    return this.dat4;
  }

  public void setDat4(final ZonedDateTime dat4) {
    this.dat4 = dat4;
  }

  // to string

  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- id=" + this.id + "\n");
    sb.append("- dat1=" + this.dat1 + "\n");
    sb.append("- dat2=" + this.dat2 + "\n");
    sb.append("- dat3=" + this.dat3 + "\n");
    sb.append("- dat4=" + this.dat4);
    return sb.toString();
  }

  // to JSON Object

  public JSONObject toJSONObject() {
    JSONObject obj = new JSONObject();
    obj.addProperty("id", this.id);
    obj.addProperty("dat1", this.dat1);
    obj.addProperty("dat2", this.dat2);
    obj.addProperty("dat3", this.dat3);
    obj.addProperty("dat4", this.dat4);
    return obj;
  }

  // to JSON String

  public String toJSON() {
    return toJSONObject().render();
  }

}
