// Generated by HotRod 5.1.18-SNAPSHOT on Apr 6, 2026 at 10:17:34

package app.persistence.layout;

import java.io.Serializable;

import org.hotrod.json.JSONObject;

public class MyAccountLayout implements Serializable {

  private static final long serialVersionUID = 1L;

  // Expression properties

  protected Byte id = null; // Source Type: STATIC_DIALECT_RULE, rule #D7
  protected String name = null; // Source Type: STATIC_DIALECT_RULE, rule #D14

  // getters & setters

  public final Byte getId() {
    return this.id;
  }

  public final void setId(final java.lang.Byte id) {
    this.id = id;
  }

  public final String getName() {
    return this.name;
  }

  public final void setName(final java.lang.String name) {
    this.name = name;
  }

  // to string

  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(super.toString() + "\n");
    sb.append("- id=" + this.id + "\n");
    sb.append("- name=" + this.name);
    return sb.toString();
  }

  // to JSON Object

  public JSONObject toJSONObject() {
    JSONObject obj = new JSONObject();
    obj.addProperty("id", this.id);
    obj.addProperty("name", this.name);
    return obj;
  }

  // to JSON String

  public String toJSON() {
    return toJSONObject().render();
  }

}
