<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>hotrod-generator</artifactId>
  <packaging>jar</packaging>

  <name>hotrod-generator</name>
  <description>HotRod is an ORM for Java, Spring and SpringBoot.</description>
  <url>https://github.com/hotrodorm/hotrod</url>

  <parent>
    <groupId>org.hotrodorm.hotrod</groupId>
    <artifactId>hotrod-project</artifactId>
    <version>5.1.17</version>
  </parent>

  <properties>
  </properties>

  <dependencies>

    <!-- HotRod -->

    <dependency>
      <groupId>org.hotrodorm.hotrod</groupId>
      <artifactId>hotrod</artifactId>
      <version>5.1.17</version>
    </dependency>

    <dependency>
      <groupId>org.hotrodorm.hotrod</groupId>
      <artifactId>hotrod-livesql</artifactId>
      <version>5.1.17</version>
    </dependency>

    <dependency>
      <groupId>org.hotrodorm.hotrod</groupId>
      <artifactId>hotrod-dynamicsql</artifactId>
      <version>5.1.17</version>
    </dependency>

    <!-- Tartarus -->

    <dependency>
      <groupId>org.nocrala.tools.database</groupId>
      <artifactId>tartarus</artifactId>
    </dependency>
    
    <!-- Adding JAXB (RI) dependency, so any Java 9+ client will work -->

    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>javax.activation</groupId>
      <artifactId>activation</artifactId>
      <scope>provided</scope>
    </dependency>

  </dependencies>

</project>
