package org.hotrod.generator.jdbc;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.sql.DataSource;

import org.hotrod.config.AbstractDAOTag;
import org.hotrod.config.Constants;
import org.hotrod.config.HotRodFragmentConfigTag;
import org.hotrod.config.JDBCTag;
import org.hotrod.database.DatabaseAdapter;
import org.hotrod.dynamic.DynamicExpressionException;
import org.hotrod.dynamic.DynamicExpressionFactory;
import org.hotrod.dynamic.DynamicInsertQuery;
import org.hotrod.dynamic.DynamicModificationQuery;
import org.hotrod.dynamic.ParameterContext;
import org.hotrod.dynamic.PreparedModificationQuery;
import org.hotrod.dynamic.builder.QueryBuilder;
import org.hotrod.dynamic.insert.PreparedInsertQuery;
import org.hotrod.dynamic.insert.PrimaryKeyRetrievalMode;
import org.hotrod.exceptions.ControlledException;
import org.hotrod.exceptions.SequencesNotSupportedException;
import org.hotrod.exceptions.UncontrolledException;
import org.hotrod.generator.DAOType;
import org.hotrod.generator.FileGenerator;
import org.hotrod.generator.FileGenerator.TextWriter;
import org.hotrod.generator.mybatisspring.Const;
import org.hotrod.generator.mybatisspring.DataSetLayout;
import org.hotrod.generator.mybatisspring.EnumClass;
import org.hotrod.metadata.ColumnMetadata;
import org.hotrod.metadata.DataSetMetadata;
import org.hotrod.metadata.EnumDataSetMetadata;
import org.hotrod.metadata.ForeignKeyMetadata;
import org.hotrod.metadata.KeyMetadata;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.queries.LiveSQLContext;
import org.hotrod.runtime.livesql.queries.typesolver.TypeSolver;
import org.hotrod.typesolver.UnresolvableDataTypeException;
import org.hotrod.utils.AbstractClassWriter.ExternalClass;
import org.hotrod.utils.ClassPackage;
import org.hotrod.utils.ClassWriter;
import org.hotrod.utils.GenUtils;
import org.hotrod.utils.SUtil;
import org.hotrod.utils.Separator;
import org.nocrala.tools.database.tartarus.core.JdbcColumn.AutogenerationType;

// Optimistic version control NOT YET IMPLEMENTED

public class DAO {

  private static final Logger log = Logger.getLogger(DAO.class.getName());

  // Properties

  private AbstractDAOTag tag;

  private DataSetMetadata metadata;
  private DataSetLayout layout;
  private JDBCGenerator generator;
  private DAOType daoType;
  private JDBCTag myBatisTag;
  private DatabaseAdapter adapter;

  private HotRodFragmentConfigTag fragmentConfig;
  private ClassPackage fragmentPackage;

  private ClassPackage classPackage;

  private Entity entity = null;
  private Model model = null;

  private String metadataClassName;

  private Map<DataSetMetadata, LinkedHashSet<ForeignKeyMetadata>> fkSelectors;
  private Map<DataSetMetadata, LinkedHashSet<ForeignKeyMetadata>> efkSelectors;

  private ClassWriter w;

  // Constructors

  public DAO(final AbstractDAOTag tag, final DataSetMetadata metadata, final DataSetLayout layout,
      final JDBCGenerator generator, final DAOType type, final JDBCTag myBatisTag, final DatabaseAdapter adapter,
      final Entity entity, final Model model) {
    super();
    this.tag = tag;
    this.metadata = metadata;
    this.layout = layout;
    this.generator = generator;
    if (type == null) {
      throw new RuntimeException("DAOType cannot be null.");
    }
    this.daoType = type;
    this.myBatisTag = myBatisTag;
    this.adapter = adapter;

    this.entity = entity;
    this.model = model;

    this.fragmentConfig = metadata.getFragmentConfig();
    this.fragmentPackage = this.fragmentConfig != null && this.fragmentConfig.getFragmentPackage() != null
        ? this.fragmentConfig.getFragmentPackage()
        : null;

    this.classPackage = this.layout.getDAOPrimitivePackage(this.fragmentPackage);
    this.metadataClassName = this.metadata.getId().getJavaClassName() + (this.isTable() ? "Table" : "View");

    this.fkSelectors = compileDistinctFKs(this.metadata.getImportedFKs());
    this.efkSelectors = compileDistinctFKs(this.metadata.getExportedFKs());
  }

  public void generate(final FileGenerator fileGenerator, final JDBCGenerator mg)
      throws UncontrolledException, ControlledException {

    String className = this.getClassName() + ".java";

    File dir = this.layout.getDaoPrimitivePackageDir(this.fragmentPackage);
    File f = new File(dir, className);
    log.fine("f=" + f);

    try (TextWriter tw = fileGenerator.createWriter(f)) {

      this.w = new ClassWriter(this.classPackage, "// Autogenerated by " + Constants.TOOL_NAME + " -- Do not edit.",
          "");
      writeBody(mg);
      this.w.writeTo(tw);

    } catch (IOException e) {

      throw new UncontrolledException(
          "Could not generate DAO primitives class for DAO defined in the <" + this.tag.getTagName() + "> tag in "
              + this.tag.getSourceLocation().render() + ":\n" + "could not write to file '" + f.getName() + "'.",
          e);
    } catch (UnresolvableDataTypeException e) {
      throw new ControlledException(
          "Could not generate DAO primitives class for DAO defined in the <" + this.tag.getTagName() + "> tag in "
              + this.tag.getSourceLocation().render() + ":\n" + "'could not handle columns '"
              + e.getColumnMetadata().getName() + "' type: " + e.getColumnMetadata().getTypeName());
    } catch (SequencesNotSupportedException e) {
      throw new ControlledException("Could not generate DAO primitives class for DAO defined in the <"
          + this.tag.getTagName() + "> tag in " + this.tag.getSourceLocation().render() + ":\n" + e.getMessage());
    }

  }

  private void writeBody(final JDBCGenerator g)
      throws IOException, UnresolvableDataTypeException, ControlledException, SequencesNotSupportedException {

    writeClassHeader();

//    if (!this.isExecutor()) {
//
//      writeRowParser();
//
//      if (this.isTable()) {
//        writeSelectByPK(mg);
//        writeSelectByUI(mg);
//      }
//
//      writeSelectByExample();
//      writeSelectByCriteria();
//
//      if (this.isTable()) {
//        if (this.generator.isClassicFKNavigationEnabled() || this.isClassicFKNavigationEnabled()) {
//          log.fine("FK navigation");
//          writeSelectParentByFK();
//          writeSelectChildrenByFK();
//        }
//
    writeInsert();
//
    writeUpdateByPK();
//
    writeDeleteByPK();
//      }
//
//      if (this.isView()) {
//        writeInsertByExample();
//      }
//
//      if (this.isTable() || this.isView()) {
    writeUpdateByExample();
//        writeUpdateByCriteria();
//
    writeDeleteByExample();
//        writeDeleteByCriteria();
//      }
//
//      writeEnumTypeHandlers();
//
//      writeOrderingEnum();
//
//      writeMetadata();
//
//      if (this.getBundle().getParent() != null) {
//        writeAOPAspect();
//      }
//
//    }
//
//    writeConverters();
//
//    if (this.tag != null) {
//
//      log.fine("SQL NAME=" + this.metadata.getId().getCanonicalSQLName() + " this.tag=" + this.tag);
//      for (SequenceMethodTag s : this.tag.getSequences()) {
//        log.fine("s.getName()=" + s.getSequenceId().getRenderedSQLName());
//        writeSelectSequence(s);
//      }
//
//      for (QueryMethodTag q : this.tag.getQueries()) {
//        log.fine("q.getJavaMethodName()=" + q.getMethod());
//        writeQuery(q);
//      }
//
//      for (SelectMethodMetadata s : this.metadata.getSelectsMetadata()) {
//        writeSelect(s);
//      }
//
//    }

    writeClassFooter();
  }

  private void writeClassHeader() throws IOException {

    w.println("@", Const.COMPONENT);
    w.println("public class " + this.getClassName() + " implements ", Serializable.class, ", ",
        Const.APPLICATION_CONTEXT_AWARE, " {");
    w.println();

    // Serial Version UID

    w.println("  private static final long serialVersionUID = 1L;");
    w.println();

    w.println("  private static final ", Logger.class, " log = ", Logger.class,
        ".getLogger(" + this.getClassName() + ".class.getName());");
    w.println();

    // Spring properties

//    Map<String, String> daoMembers = new HashMap<String, String>();

    w.println("  @", Const.AUTOWIRED);
    if (!SUtil.isEmpty(this.layout.getLiveSQLDialectBeanQualifier())) {
      w.println("  @", Const.QUALIFIER, "(\"" + this.layout.getLiveSQLDialectBeanQualifier() + "\")");
    }
    w.println("  private ", LiveSQLDialect.class, " liveSQLDialect;");
    w.println();

    w.println("  private final ", DynamicExpressionFactory.class, " factory = ", DynamicExpressionFactory.class,
        ".getFactory();");
    w.println("  private final ", QueryBuilder.class, " builder = new ", QueryBuilder.class, "(this.factory);");
    w.println();

    w.println("  @", Const.AUTOWIRED);
    w.println("  private ", Const.SPRING_BEAN_OBJECT_FACTORY, " springBeanObjectFactory;");
    w.println();

    w.println("  @", Const.AUTOWIRED);
    w.println("  private ", DataSource.class, " dataSource;");
    w.println();

    w.println("  private ", Const.APPLICATION_CONTEXT, " applicationContext;");
    w.println();

    w.println("  @Override");
    w.println("  public void setApplicationContext(final ", Const.APPLICATION_CONTEXT, " applicationContext) throws ",
        Const.BEANS_EXCEPTION, " {");
    w.println("    this.applicationContext = applicationContext;");
//    w.println("    this.sqlSession.getConfiguration().setObjectFactory(this.springBeanObjectFactory);");
    w.println("  }");
    w.println();

    w.println("  private ", LiveSQLContext.class, " context;");
    w.println();

    w.println("  @", Const.POST_CONSTRUCT);
    w.println("  public void initializeContext() {");
    w.println("    this.context = new ", LiveSQLContext.class, "(this.liveSQLDialect, this.dataSource, new ",
        TypeSolver.class, "(null, this.liveSQLDialect));");
    w.println("  }");

  }

  private void writeInsert() throws ControlledException {

    w.println();
    w.println("  // INSERT");

    KeyMetadata pk = this.metadata.getPK();

    // Limitations
    // 1. This version supports autogeneration for a single-column PK
    // 2. Does not retrieve DEFAULT columns
    // 3. Retrieved value can only be numeric up to LONG (no NUMBER(19) or UUID)
    // 4. Only retrieves a single value for a single-row INSERT (no multi-inserts)

    List<ColumnMetadata> sequences = new ArrayList<>();
    List<ColumnMetadata> identities = new ArrayList<>();
    List<ColumnMetadata> defaults = new ArrayList<>();
    for (ColumnMetadata cm : this.metadata.getColumns()) {
      if (cm.belongsToPK() && cm.getSequenceId() != null) {
        sequences.add(cm);
      }
      if (cm.belongsToPK() && cm.getAutogenerationType() != null && cm.getAutogenerationType().isIdentity()) {
        identities.add(cm);
      }
      if (cm.getColumnDefault() != null) {
        defaults.add(cm);
      }
    }

    InsertMechanics mechanics = computeInsertMechanics(sequences, identities, defaults);

    log.info("mechanics: " + mechanics);

    w.println();
    w.println("  private final ", DynamicInsertQuery.class, " insert = builder");

    w.println("      .literaln(\"INSERT INTO ", SUtil.escapeJavaString(this.metadata.getId().getRenderedSQLName()),
        " (\")");
    int coln = this.metadata.getColumns().size();
    int n = 1;
    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String memId = cm.getId().getJavaMemberName();
      String sqlId = cm.getId().getRenderedSQLName();

      // Always include column
      if (!cm.belongsToPK()) {
        w.println("      .literaln(\"  " + SUtil.escapeJavaString(sqlId) + (n < coln ? "," : "") + "\")");
      }
      if (cm.belongsToPK() && cm.getSequenceId() != null) {
        w.println("      .literaln(\"  " + SUtil.escapeJavaString(sqlId) + (n < coln ? "," : "") + "\")");
      }
      if (cm.belongsToPK() && cm.getSequenceId() == null && cm.getAutogenerationType() == null) {
        w.println("      .literaln(\"  " + SUtil.escapeJavaString(sqlId) + (n < coln ? "," : "") + "\")");
      }

      // Never include column
      if (cm.belongsToPK() && cm.getAutogenerationType() == AutogenerationType.IDENTITY_ALWAYS) {
        // nothing to do
      }

      // Conditionally include column
      if (cm.belongsToPK() && cm.getAutogenerationType() == AutogenerationType.IDENTITY_BY_DEFAULT) {
        w.println("      .ifPart(\"m." + SUtil.escapeJavaString(memId) + " != null\", builder.literal(\""
            + SUtil.escapeJavaString(sqlId) + (n < coln ? "," : "") + "\\n\").end())");
      }

      n++;
    }

    w.println("      .literaln(\") VALUES (\")");
    n = 1;
    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String memId = cm.getId().getJavaMemberName();
      String jdbcType = cm.getType().getJDBCShortType();

      // Always include column
      if (!cm.belongsToPK()) {
        w.println("      .literal(\"  \").parameter(\"m." + SUtil.escapeJavaString(memId) + "\", ", Types.class,
            "." + jdbcType + ")" + (n < coln ? ".literaln(\",\")" : ""));
      }
      if (cm.belongsToPK() && cm.getSequenceId() != null) {
        if (mechanics.getMode() == PrimaryKeyRetrievalMode.SEQUENCE_PREFETCH) {
          w.println("      .literal(\"  \").parameter(\"m." + SUtil.escapeJavaString(memId) + "\", ", Types.class,
              "." + jdbcType + ")" + (n < coln ? ".literaln(\",\")" : ""));
        } else {
          String si = mechanics.getSequenceInlineSQL();
          w.println("      .literal(\"  " + SUtil.escapeJavaString(si) + "\")" + (n < coln ? ".literaln(\",\")" : ""));
        }
      }
      if (cm.belongsToPK() && cm.getSequenceId() == null && cm.getAutogenerationType() == null) {
        w.println("      .literal(\"  \").parameter(\"m." + SUtil.escapeJavaString(memId) + "\", ", Types.class,
            "." + jdbcType + ")" + (n < coln ? ".literaln(\",\")" : ""));
      }

      // Never include column
      if (cm.belongsToPK() && cm.getAutogenerationType() == AutogenerationType.IDENTITY_ALWAYS) {
        // nothing to do
      }

      // Conditionally include column
      if (cm.belongsToPK() && cm.getAutogenerationType() == AutogenerationType.IDENTITY_BY_DEFAULT) {
        w.println("      .ifPart(\"m." + SUtil.escapeJavaString(memId) + " != null\", builder.parameter(\"m."
            + SUtil.escapeJavaString(memId) + "\", Types." + jdbcType + ")" + (n < coln ? ".literal(\", \")" : "")
            + ".end())");
      }

      n++;
    }
    w.println("      .literal(\")\")");

    if (mechanics.getMode() == PrimaryKeyRetrievalMode.SEQUENCE_PREFETCH) {
      w.print("      .endInsertQuery(", PrimaryKeyRetrievalMode.class,
          "." + mechanics.getMode() + ", \"" + SUtil.escapeJavaString(mechanics.getSequencePreFetchSQL()) + "\", \"m." //
              + SUtil.escapeJavaString(mechanics.getPrimaryKeyMemberName()) //
              + "\"");
    } else {
      w.print("      .endInsertQuery(", PrimaryKeyRetrievalMode.class, "." + mechanics.getMode());
    }

    if (mechanics.getGeneratedKeysNames() != null && mechanics.getGeneratedKeysNames().length > 0) {
      w.print(", null, null");
      for (String gkn : mechanics.getGeneratedKeysNames()) {
        w.print(", \"" + SUtil.escapeJavaString(gkn) + "\"");
      }
    }

    w.println(");");

    ExternalClass em = ExternalClass.of(this.model.getFullClassName());
    w.println();
    w.print("  public void insert(", em, " m");
    w.println(") throws ", DynamicExpressionException.class, ", ", SQLException.class, " {");

    w.println("    ", ParameterContext.class, " context = this.factory.newParameterContext();");
    w.println("    context.add(\"m\", m);");
    w.println("    ", PreparedInsertQuery.class, " preparedQuery = this.insert.prepare(context);");

    fragmentLogging();

    w.println("    try (", Connection.class, " conn = this.dataSource.getConnection()) {");
    if (mechanics.getMode() == PrimaryKeyRetrievalMode.NO_RETRIEVAL) {
      w.println("      preparedQuery.execute(conn);");
    } else {
      String targetClass = pk.getColumns().get(0).getType().getJavaClassName();
      String pkCast = GenUtils.convertPropertyType(Long.class.getName(), targetClass, "pk");
      w.println("      Long pk = preparedQuery.execute(conn);");
      w.println("      m.setId(" + pkCast + ");");
    }
    w.println("    }");

    w.println("  }");

  }

  private InsertMechanics computeInsertMechanics(List<ColumnMetadata> sequences, List<ColumnMetadata> identities,
      List<ColumnMetadata> defaults) throws ControlledException {

    // Identity

    if (identities.size() > 0) {
      if (identities.size() == 1) {
        @SuppressWarnings("unused")
        ColumnMetadata cm = identities.get(0);
        if (this.adapter.getInsertIntegration().integratesIdentities()) {
          if (this.adapter.getInsertIntegration().identitiesMustDeclarePKColumns()) {
            String[] pkcols = this.metadata.getPK().getColumns().stream().map(c -> c.getId().getRenderedSQLName())
                .toArray(String[]::new);
            return new InsertMechanics(PrimaryKeyRetrievalMode.IDENTITY_INLINE_KEYS_RESULTSET, null, null, null,
                pkcols);
          } else {
            return new InsertMechanics(PrimaryKeyRetrievalMode.IDENTITY_INLINE_KEYS_RESULTSET);
          }
        } else {
          return new InsertMechanics(PrimaryKeyRetrievalMode.NO_RETRIEVAL);
        }
      } else { // Implement in the future
        throw new ControlledException(
            "HotRod does not support multiple columns generated as IDENTITY in the same table: table '"
                + this.metadata.getId().getRenderedSQLName() + "'");
      }
    }

    // Sequence

    if (sequences.size() > 0) {
      if (sequences.size() == 1) {
        ColumnMetadata cm = sequences.get(0);
        String sequenceInlineSQL = null;
        String sequencePreFetchSQL = null;
        try {
          sequenceInlineSQL = this.adapter.renderInlineSequenceOnInsert(cm);
          sequencePreFetchSQL = this.adapter.renderSelectSequence(cm);
        } catch (SequencesNotSupportedException e) {
          throw new ControlledException(e.getMessage());
        }
        if (this.adapter.getInsertIntegration().integratesSequencesKeysResultSet()) {
          if (this.adapter.getInsertIntegration().identitiesMustDeclarePKColumns()) {
            String[] pkcols = this.metadata.getPK().getColumns().stream().map(c -> c.getId().getRenderedSQLName())
                .toArray(String[]::new);
            return new InsertMechanics(PrimaryKeyRetrievalMode.SEQUENCE_INLINE_KEYS_RESULTSET, null, null,
                sequenceInlineSQL, pkcols);
          } else {
            return new InsertMechanics(PrimaryKeyRetrievalMode.SEQUENCE_INLINE_KEYS_RESULTSET, null, null,
                sequenceInlineSQL);
          }
        } else if (this.adapter.getInsertIntegration().integratesSequencesStandardResultSet()) {
          return new InsertMechanics(PrimaryKeyRetrievalMode.SEQUENCE_INLINE_STANDARD_RESULTSET, null, null,
              sequenceInlineSQL);
        } else {
          return new InsertMechanics(PrimaryKeyRetrievalMode.SEQUENCE_PREFETCH, sequencePreFetchSQL,
              cm.getId().getJavaMemberName(), null);
        }
      } else { // Implement in the future
        throw new ControlledException("HotRod does not support multiple columns generated using sequences: table '"
            + this.metadata.getId().getRenderedSQLName() + "'");
      }
    }

    // No Identities and no columns populated by sequences

    return new InsertMechanics(PrimaryKeyRetrievalMode.NO_RETRIEVAL);

  }

  private void writeUpdateByPK() {

    KeyMetadata pk = this.metadata.getPK();

    if (pk == null) {
      w.println();
      w.println("  // UPDATE BY PK -- Not available since the table does not have a primary key.");
    } else {

      w.println();
      w.println("  // UPDATE BY PK");

      w.println();
      w.println("  private final ", DynamicModificationQuery.class, " updateByPK = builder");
      w.println("    .literal(\"UPDATE " + this.metadata.getId().getRenderedSQLName() + "\")");
      fragmentSet();
      fragmentWherePK(pk, "m");
      w.println("    .endModificationQuery();");
      w.println();

      ExternalClass em = ExternalClass.of(this.model.getFullClassName());
      w.print("  public int update(", em, " m");
      w.println(") throws ", DynamicExpressionException.class, ", ", SQLException.class, " {");

      for (ColumnMetadata cm : pk.getColumns()) {
        String getter = cm.getId().getJavaGetter();
        w.println("    if (m." + getter + "() == null) return 0;");
      }

      w.println("    ", ParameterContext.class, " context = this.factory.newParameterContext();");
      w.println("    context.add(\"m\", m);");
      w.println("    ", PreparedModificationQuery.class, " preparedQuery = this.updateByPK.prepare(context);");

      fragmentLogging();
      fragmentExecuteModification();

      w.println("  }");

    }

  }

  private void writeDeleteByPK() {

    KeyMetadata pk = this.metadata.getPK();

    if (pk == null) {
      w.println();
      w.println("  // DELETE BY PK -- Not available since the table does not have a primary key.");
    } else {

      w.println();
      w.println("  // DELETE BY PK");

      w.println();
      w.println("  private final ", DynamicModificationQuery.class, " deleteByPK = builder");
      w.println("    .literaln(\"DELETE FROM " + this.metadata.getId().getRenderedSQLName() + "\")");
      fragmentWherePK(pk);
      w.println("    .endModificationQuery();");
      w.println();

      w.print("  public int delete(");
      fragmentPKParameters(pk);
      w.println(") throws ", DynamicExpressionException.class, ", ", SQLException.class, " {");

      for (ColumnMetadata cm : pk.getColumns()) {
        String m = cm.getId().getJavaMemberName();
        w.println("    if (" + m + " == null) return 0;");
      }

      ExternalClass em = ExternalClass.of(this.model.getFullClassName());
      w.println("    ", em, " filter = new ", em, "();");
      for (ColumnMetadata cm : pk.getColumns()) {
        String m = cm.getId().getJavaMemberName();
        String setter = cm.getId().getJavaSetter();
        w.println("    filter." + setter + "(" + m + ");");
      }

      w.println("    ", ParameterContext.class, " context = this.factory.newParameterContext();");
      w.println("    context.add(\"f\", filter);");
      w.println("    ", PreparedModificationQuery.class, " preparedQuery = this.deleteByPK.prepare(context);");

      fragmentLogging();
      fragmentExecuteModification();

      w.println("  }");

    }

  }

  private void writeUpdateByExample() {

    w.println();
    w.println("  // UPDATE BY EXAMPLE");

    w.println();
    w.println("  private final ", DynamicModificationQuery.class, " updateByExample = builder");
    w.println("      .literal(\"UPDATE FROM " + this.metadata.getId().getRenderedSQLName() + "\")");
    fragmentSet();
    fragmentWhereExample();
    w.println("      .endModificationQuery();");
    w.println();

    ExternalClass em = ExternalClass.of(this.model.getFullClassName());
    w.print("  public int delete(", em, " filter, ", em, " updateValues");
    w.println(") throws ", DynamicExpressionException.class, ", ", SQLException.class, " {");

    w.println("    ", ParameterContext.class, " context = this.factory.newParameterContext();");
    w.println("    context.add(\"f\", filter);");
    w.println("    context.add(\"u\", updateValues);");
    w.println("    ", PreparedModificationQuery.class, " preparedQuery = this.updateByExample.prepare(context);");

    fragmentLogging();
    fragmentExecuteModification();

    w.println("  }");

  }

  private void writeDeleteByExample() {

    w.println();
    w.println("  // DELETE BY EXAMPLE");

    w.println();
    w.println("  private final ", DynamicModificationQuery.class, " deleteByExample = builder");
    w.println("      .literal(\"DELETE FROM " + this.metadata.getId().getRenderedSQLName() + "\")");
    fragmentWhereExample();
    w.println("      .endModificationQuery();");
    w.println();

    ExternalClass em = ExternalClass.of(this.model.getFullClassName());
    w.print("  public int delete(", em, " filter");
    w.println(") throws ", DynamicExpressionException.class, ", ", SQLException.class, " {");

    w.println("    ", ParameterContext.class, " context = this.factory.newParameterContext();");
    w.println("    context.add(\"f\", filter);");
    w.println("    ", PreparedModificationQuery.class, " preparedQuery = this.deleteByExample.prepare(context);");

    fragmentLogging();
    fragmentExecuteModification();

    w.println("  }");

  }

  private void fragmentSet() {
    w.println("      .set(builder.ifs()");
    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String memId = cm.getId().getJavaMemberName();
      String sqlId = cm.getId().getRenderedSQLName();
      String jdbcType = cm.getType().getJDBCShortType();
      w.println("          .ifPart(\"m." + SUtil.escapeJavaString(memId) + " != null\", builder.literal(\""
          + SUtil.escapeJavaString(sqlId) + " = \").parameter(\"m." + SUtil.escapeJavaString(memId) + "\", Types."
          + jdbcType + ").end())");
    }
    w.println("          .end())");
  }

  private void fragmentPKParameters(KeyMetadata pk) {
    Separator sep = new Separator(", ");
    for (ColumnMetadata cm : pk.getColumns()) {
      w.print(sep.render());
      EnumDataSetMetadata em = cm.getEnumMetadata();
      String javaClassName;
      if (em != null) {
        EnumClass ec = this.generator.getEnum(em);
        javaClassName = ec.getFullClassName();
      } else {
        javaClassName = cm.getType().getJavaClassName();
      }
      w.print(ExternalClass.of(javaClassName), " ", cm.getId().getJavaMemberName());
    }
  }

  private void fragmentWherePK(KeyMetadata pk) {
    this.fragmentWherePK(pk, "f");
  }

  private void fragmentWherePK(KeyMetadata pk, String objname) {
    Separator sep = Separator.of("WHERE ", "  AND ");
    for (ColumnMetadata cm : pk.getColumns()) {
      String memId = cm.getId().getJavaMemberName();
      String sqlId = cm.getId().getRenderedSQLName();
      String jdbcType = cm.getType().getJDBCShortType();
      w.println(
          "    .literal(\"" + SUtil.escapeJavaString(sep.render()) + "\" + \"" + SUtil.escapeJavaString(sqlId)
              + " = \").parameter(\"" + objname + "." + SUtil.escapeJavaString(memId) + "\", ",
          Types.class, "." + jdbcType + ")");
    }
  }

  private void fragmentWhereExample() {
    w.println("      .where(\"AND\", builder.ifs()");
    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String memId = cm.getId().getJavaMemberName();
      String sqlId = cm.getId().getRenderedSQLName();
      String jdbcType = cm.getType().getJDBCShortType();
      w.println("          .ifPart(\"f." + memId + " != null\", builder.literal(\"" + SUtil.escapeJavaString(sqlId)
          + " = \").parameter(\"f." + memId + "\", ", Types.class, "." + jdbcType + ").end())");
    }
    w.println("          .end())");
  }

  private void fragmentLogging() {
    w.println("    if (log.isLoggable(", Level.class, ".FINER)) {");
    w.println("      log.finer(\"SQL: \" + preparedQuery.getPreview(true));");
    w.println("    } else if (log.isLoggable(", Level.class, ".FINE)) {");
    w.println("      log.fine(\"SQL: \" + preparedQuery.getPreview());");
    w.println("    }");
  }

  private void fragmentExecuteModification() {
    w.println("    try (", Connection.class, " conn = this.dataSource.getConnection()) {");
    w.println("      int rows = preparedQuery.execute(conn);");
    w.println("      return rows;");
    w.println("    }");
  }

  private void writeClassFooter() throws IOException {
    w.println();
    w.println("}");
  }

  // Utils

  private Map<DataSetMetadata, LinkedHashSet<ForeignKeyMetadata>> compileDistinctFKs(
      final List<ForeignKeyMetadata> fks) {

    List<ForeignKeyMetadata> sortedFKs = new ArrayList<ForeignKeyMetadata>(fks);
    sortedFKs.sort((a, b) -> {
      int c = a.getRemote().toCamelCase(".").compareTo(b.getRemote().toCamelCase("."));
      if (c != 0) {
        return c;
      }
      return a.getLocal().toCamelCase(".").compareTo(b.getLocal().toCamelCase("."));
    });

    Map<DataSetMetadata, LinkedHashSet<ForeignKeyMetadata>> fkSelectors = new LinkedHashMap<DataSetMetadata, LinkedHashSet<ForeignKeyMetadata>>();
    for (ForeignKeyMetadata fk : sortedFKs) {
      DataSetMetadata ds = fk.getRemote().getTableMetadata();
      LinkedHashSet<ForeignKeyMetadata> fkSelector = fkSelectors.get(ds);
      if (fkSelector == null) {
        fkSelector = new LinkedHashSet<ForeignKeyMetadata>();
        fkSelectors.put(ds, fkSelector);
      }
      fkSelector.add(fk);
    }

    return fkSelectors;
  }

  public boolean isTable() {
    return this.daoType == DAOType.TABLE;
  }

  public String getClassName() {
    return this.myBatisTag.getDaos().generateDAOName(this.metadata.getId());
  }

  public String getFullClassName() {
    return this.classPackage.getFullClassName(getClassName());
  }

  public String getMemberName() {
    return SUtil.lowerFirst(this.getClassName());
  }

}
