package org.hotrod.generator.jdbc;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import org.hotrod.config.Constants;
import org.hotrod.config.HotRodFragmentConfigTag;
import org.hotrod.config.JDBCTag;
import org.hotrod.exceptions.ErrorMessageException;
import org.hotrod.exceptions.FaultException;
import org.hotrod.generator.DAOType;
import org.hotrod.generator.FileGenerator;
import org.hotrod.generator.FileGenerator.TextWriter;
import org.hotrod.json.JSONObject;
import org.hotrod.metadata.ColumnMetadata;
import org.hotrod.metadata.DataSetMetadata;
import org.hotrod.typesolver.UnresolvableDataTypeException;
import org.hotrod.utils.AbstractClassWriter.ExternalClass;
import org.hotrod.utils.ClassPackage;
import org.hotrod.utils.ClassWriter;
import org.nocrala.tools.lang.collector.listcollector.ListWriter;

public class Layout {

  private static final Logger log = Logger.getLogger(Layout.class.getName());

  private DataSetMetadata metadata;
  private JDBCTag jdbcTag;
  private JDBCGenerator generator;
  private DAOType daoType;
  private HotRodFragmentConfigTag fragmentConfig;
  private ClassPackage fragmentPackage;

  private ClassPackage classPackage;

  private ClassWriter w;

  // Constructor

  public Layout(final DataSetMetadata metadata, final JDBCGenerator generator, final DAOType daoType,
      final JDBCTag jdbcTag) {
    super();
    log.fine("init");

    this.metadata = metadata;
    this.jdbcTag = jdbcTag;
    this.generator = generator;
    if (daoType == null) {
      throw new RuntimeException("VOType cannot be null.");
    }
//    metadata.getDaoTag().addGeneratableObject(this);
    this.daoType = daoType;
    this.fragmentConfig = metadata.getFragmentConfig();
    this.fragmentPackage = this.fragmentConfig != null && this.fragmentConfig.getFragmentPackage() != null
        ? this.fragmentConfig.getFragmentPackage()
        : null;

    this.classPackage = this.jdbcTag.getLayoutPackage(this.fragmentPackage);
  }

  // Getters

  public void generate(final FileGenerator fileGenerator) throws FaultException, ErrorMessageException {

    String className = this.getClassName() + ".java";
    File dir = this.jdbcTag.getLayoutPackageDir(this.fragmentPackage);
    File f = new File(dir, className);

    ClassPackage cp = this.jdbcTag.getLayoutPackage(this.fragmentPackage);

    this.w = new ClassWriter(cp, "// Autogenerated by " + Constants.TOOL_NAME + " -- Do not edit.", "");

    try (TextWriter tw = fileGenerator.createWriter(f)) {

      writeClassHeader();

      writeProperties();

      writeGettersAndSetters();

      writeToString();

      writeToJSON();

      writeClassFooter();

      this.w.writeTo(tw);

    } catch (IOException e) {
      throw new FaultException(
          "Could not generate DAO primitives class: could not write to file '" + f.getName() + "'.", e);
    } catch (UnresolvableDataTypeException e) {
      throw new ErrorMessageException("Could not generate DAO primitives for table '" + e.getColumnMetadata().getTable()
          + "'. Could not handle columns '" + e.getColumnMetadata().getName() + "' type: "
          + e.getColumnMetadata().getTypeName());
    }

  }

  private void writeClassHeader() throws IOException {

    // Signature

    w.println("public class " + this.getClassName() + " implements ", Serializable.class, " {");

    w.println();

    // Serial Version UID

    w.println("  private static final long serialVersionUID = 1L;");
    w.println();

  }

  private void writeProperties() throws IOException, UnresolvableDataTypeException {

    w.println("  // Layout Properties ("
        + (this.daoType == DAOType.TABLE ? "table" : this.daoType == DAOType.VIEW ? "view" : "select") + " columns)");
    w.println();
    writeColumnProperties(this.metadata.getColumns());

  }

  private void writeColumnProperties(final List<ColumnMetadata> columns) throws IOException {
    for (ColumnMetadata cm : columns) {
      String javaType = resolveType(cm);
      w.println("  protected ", ExternalClass.of(javaType),
          " " + cm.getId().getJavaMemberName() + " = null; // " + cm.getTypeName());
    }
    w.println();
  }

  private String resolveType(final ColumnMetadata cm) {
    EnumClass ec = this.generator.getEnum(cm.getEnumMetadata());
    return ec != null ? ec.getFullClassName() : cm.getType().getJavaClassName();
  }

  private void writeGettersAndSetters() throws IOException, UnresolvableDataTypeException {

    w.println("  // getters & setters");
    w.println();

    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String javaType = resolveType(cm);
      String m = cm.getId().getJavaMemberName();
      writeGetter(cm, javaType, m);
      writeSetter(cm, javaType, m);
    }

  }

  private void writeGetter(ColumnMetadata cm, String javaType, String m) throws IOException {
    w.println("  public ", ExternalClass.of(javaType), " " + cm.getId().getJavaGetter() + "() {");
    w.println("    return this." + m + ";");
    w.println("  }");
    w.println();
  }

  private void writeSetter(final ColumnMetadata cm, final String javaType, final String m) throws IOException {
    String setter = cm.getId().getJavaSetter();
    w.println("  public void " + setter + "(final ", ExternalClass.of(javaType), " " + m + ") {");
    w.println("    this." + m + " = " + m + ";");
    w.println("  }");
    w.println();
  }

  private void writeToString() throws IOException, UnresolvableDataTypeException {
    w.println("  // to string");
    w.println();

    w.println("  public String toString() {");
    w.println("    ", StringBuilder.class, " sb = new ", java.lang.StringBuilder.class, "();");

    if (this.jdbcTag.getProperties().isMultilineTostring()) {
      w.println("    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + \"\\n\");");

      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \"\\n\");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.metadata.getColumns()) {
        String prop = cm.getId().getJavaMemberName();
        lw.add("\"- " + prop + "=\" + this." + prop);
      }
      w.println(lw.toString());

    } else {
      w.println("    sb.append(\"[\");");

      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \", \");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.metadata.getColumns()) {
        String prop = cm.getId().getJavaMemberName();
        lw.add("\"" + prop + "=\" + this." + prop);
      }
      w.println(lw.toString());

      w.println("    sb.append(\"]\");");
    }

    w.println("    return sb.toString();");
    w.println("  }");
    w.println();

  }

  private void writeToJSON() throws IOException, UnresolvableDataTypeException {
    w.println("  // to JSON Object");
    w.println();

    w.println("  public ", JSONObject.class, " toJSONObject() {");
    w.println("    ", JSONObject.class, " obj = new ", JSONObject.class, "();");

    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String prop = cm.getId().getJavaMemberName();
      w.println("    obj.addProperty(\"" + prop + "\", " + "this." + prop + ");");
    }

    w.println("    return obj;");
    w.println("  }");
    w.println();

    w.println("  // to JSON String");
    w.println();
    w.println("  public String toJSON() {");
    w.println("    return toJSONObject().render();");
    w.println("  }");
    w.println();
  }

  private void writeClassFooter() throws IOException {
    w.println("}");
  }

  DataSetMetadata getMetadata() {
    return metadata;
  }

  // Identifiers & File Paths

  public String getFullClassName() {
    return this.classPackage.getFullClassName(getClassName());
  }

  public String getClassName() {
    return this.jdbcTag.getLayoutName(this.metadata.getId());
  }

  // Helpers

  @SuppressWarnings("unused")
  private String toLowerInitial(final String txt) {
    if (txt == null || txt.length() < 1) {
      return txt;
    }
    return txt.substring(0, 1).toLowerCase() + txt.substring(1);
  }

}
