package org.hotrod.generator.jdbc;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import org.hotrod.config.Constants;
import org.hotrod.config.JDBCTag;
import org.hotrod.exceptions.ErrorMessageException;
import org.hotrod.exceptions.FaultException;
import org.hotrod.generator.FileGenerator;
import org.hotrod.generator.FileGenerator.TextWriter;
import org.hotrod.json.JSONArray;
import org.hotrod.json.JSONObject;
import org.hotrod.metadata.ColumnMetadata;
import org.hotrod.metadata.VOMetadata;
import org.hotrod.metadata.VOMetadata.VOMember;
import org.hotrod.metadata.VORegistry.SelectVOClass;
import org.hotrod.typesolver.UnresolvableDataTypeException;
import org.hotrod.utils.AbstractClassWriter.ExternalClass;
import org.hotrod.utils.ClassPackage;
import org.hotrod.utils.ClassWriter;
import org.nocrala.tools.lang.collector.listcollector.ListWriter;

public class SelectLayoutWriter {

  // Constants

  private static final Logger log = Logger.getLogger(SelectLayoutWriter.class.getName());

  // Properties

  private JDBCTag jdbcTag;

  private String name;
  private ClassPackage classPackage;
  private File dir;

  private List<ColumnMetadata> columns;
  private List<VOMember> associationMembers;
  private List<VOMember> collectionMembers;

  private String superClassName;

  private ClassWriter w;

  // Constructors

  // From a solo VO
  public SelectLayoutWriter(final SelectVOClass abstractSoloVO, final JDBCTag jdbcTag) {
    log.fine("init");
    this.jdbcTag = jdbcTag;

    this.name = abstractSoloVO.getName();
    this.classPackage = this.jdbcTag.getLayoutPackage(abstractSoloVO.getFragmentPackage());
    this.dir = this.jdbcTag.getLayoutPackageDir(abstractSoloVO.getFragmentPackage());

    this.columns = new ArrayList<ColumnMetadata>(abstractSoloVO.getColumnsByName().values());
    log.fine("Name: " + this.name + " this.columns.size()=" + this.columns.size());

    this.associationMembers = abstractSoloVO.getAssociations();
    this.collectionMembers = new ArrayList<VOMember>();

//    this.superClassPackage = null;
    this.superClassName = null;
  }

  // From a connected VO
  public SelectLayoutWriter(final VOMetadata vo, final JDBCTag jdbcTag) {
    this.jdbcTag = jdbcTag;

    this.name = vo.getAbstractName();
    this.classPackage = this.jdbcTag.getLayoutPackage(vo.getClassPackage());
    this.dir = this.jdbcTag.getLayoutPackageDir(vo.getClassPackage());

    this.columns = new ArrayList<ColumnMetadata>();
    log.fine("vo.getDeclaredColumns().size()=" + vo.getDeclaredColumns().size());
    for (ColumnMetadata cm : vo.getDeclaredColumns()) {
      this.columns.add(cm);
    }
    this.associationMembers = vo.getAssociationMembers();
    this.collectionMembers = vo.getCollectionMembers();

//    this.superClassPackage = vo.getSuperClass().getClassPackage();
    this.superClassName = vo.getSuperClass().getName();
  }

  // Getters

  public void generate(final FileGenerator fileGenerator) throws FaultException, ErrorMessageException {

    String className = this.name + ".java";

    File f = new File(this.dir, className);

    try (TextWriter tw = fileGenerator.createWriter(f)) {

      this.w = new ClassWriter(this.classPackage, "// Autogenerated by " + Constants.TOOL_NAME + " -- Do not edit.",
          "");
      writeBody();
      w.writeTo(tw);

    } catch (IOException e) {
      throw new FaultException(
          "Could not generate DAO primitives class: could not write to file '" + f.getName() + "'.", e);
    } catch (UnresolvableDataTypeException e) {
      throw new ErrorMessageException("Could not generate DAO primitives for table '" + e.getColumnMetadata().getTable()
          + "'. Could not handle columns '" + e.getColumnMetadata().getName() + "' type: "
          + e.getColumnMetadata().getTypeName());
    }

  }

  private void writeBody() throws IOException, UnresolvableDataTypeException {
    writeClassHeader();

    writeProperties();

    writeGettersAndSetters();

    writeToString();

    writeToJSON();

    writeClassFooter();
  }

  private void writeClassHeader() throws IOException {

    w.print("public class " + this.getName() + " ");
    if (this.superClassName == null) {
      w.print("implements ", Serializable.class, " ");
    } else {
      w.print(" extends ", ExternalClass.of(this.superClassName));
    }
    w.println("{");

    w.println();

    // Serial Version UID

    w.println("  private static final long serialVersionUID = 1L;");
    w.println();

  }

  private void writeProperties() throws IOException {

    if (!this.columns.isEmpty()) {
      w.println("  // Expression properties");
      w.println();
      for (ColumnMetadata cm : this.columns) {
        if (!cm.reusesMemberFromSuperClass()) {
          ExternalClass jt = ExternalClass.of(cm.getType().getJavaClassName());
          w.println("  protected ", jt, " " + cm.getId().getJavaMemberName() + " = null; // Type Name: "
              + cm.getTypeName() + " - Type Resolved By: " + cm.getType().getTypeSource());
        }
      }
      w.println();
    }

    if (!this.associationMembers.isEmpty()) {
      w.println("  // Association properties");
      w.println();
      for (VOMember a : this.associationMembers) {
        w.println("  protected ", ExternalClass.of(a.getName()), " " + a.getProperty() + " = null;");
      }
      w.println();
    }

    if (!this.collectionMembers.isEmpty()) {
      w.println("  // Collection properties");
      w.println();
      for (VOMember c : this.collectionMembers) {
        w.println("  protected ", List.class, "<", ExternalClass.of(c.getName()), "> " + c.getProperty() + " = null;");
      }
      w.println();
    }

  }

  private void writeGettersAndSetters() throws IOException, UnresolvableDataTypeException {
    w.println("  // getters & setters");
    w.println();

    for (ColumnMetadata cm : this.columns) {
      if (!cm.reusesMemberFromSuperClass()) {
        String javaType = cm.getType().getJavaClassName();
        String property = cm.getId().getJavaMemberName();

        w.println("  public final ", ExternalClass.of(javaType), " " + cm.getId().getJavaGetter() + "() {");
        w.println("    return this." + property + ";");
        w.println("  }");
        w.println();

        String setter = cm.getId().getJavaSetter();
        writeSetter(property, javaType, false, setter);
      }
    }

    for (VOMember a : this.associationMembers) {
      String javaType = a.getFullClassName();
      String property = a.getProperty();

      w.println("  public final ", ExternalClass.of(javaType), " " + a.getId().getJavaGetter() + "() {");
      w.println("    return this." + property + ";");
      w.println("  }");
      w.println();

      String setter = a.getId().getJavaSetter();
      writeSetter(property, javaType, false, setter);
    }

    for (VOMember c : this.collectionMembers) {
      String javaType = c.getFullClassName();
      String property = c.getProperty();

      w.println("  public final ", List.class, "<", ExternalClass.of(javaType),
          "> " + c.getId().getJavaGetter() + "() {");
      w.println("    return this." + property + ";");
      w.println("  }");
      w.println();

      String setter = c.getId().getJavaSetter();
      writeSetter(property, javaType, true, setter);
    }

  }

  private void writeSetter(final String property, final String javaType, final boolean isList, final String setter)
      throws IOException {
    w.print("  public final void " + setter + "(final ");
    if (isList) {
      w.print(List.class, "<" + javaType + ">");
    } else {
      w.print(javaType);
    }
    w.println(" " + property + ") {");
    w.println("    this." + property + " = " + property + ";");
    w.println("  }");
    w.println();
  }

  private void writeToString() throws IOException, UnresolvableDataTypeException {
    w.println("  // to string");
    w.println();

    w.println("  public String toString() {");
    w.println("    ", StringBuilder.class, " sb = new ", StringBuilder.class, "();");

    w.println("    sb.append(super.toString() + \"\\n\");");
    if (!this.columns.isEmpty()) {
      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \"\\n\");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.columns) {
        String prop = cm.getId().getJavaMemberName();
        lw.add("\"- " + prop + "=\" + this." + prop);
      }
      w.println(lw.toString());
    }

    w.println("    return sb.toString();");
    w.println("  }");
    w.println();

  }

  private void writeToJSON() throws IOException, UnresolvableDataTypeException {
    w.println("  // to JSON Object");
    w.println();
    w.println("  public ", JSONObject.class, " toJSONObject() {");

    // Entity Properties

    w.println("    ", JSONObject.class, " obj = new ", JSONObject.class, "();");

    // Expressions

    for (ColumnMetadata cm : this.columns) {
      String prop = cm.getId().getJavaMemberName();
      w.println("    obj.addProperty(\"" + prop + "\", " + "this." + prop + ");");
    }

    // Associations

    for (VOMember a : this.associationMembers) {
      String prop = a.getProperty();
      w.println("    obj.addProperty(\"" + prop + "\", " + "this." + prop + ".toJSONObject());");
    }

    // Collections

    for (VOMember c : this.collectionMembers) {
      String prop = c.getProperty();
      w.println("    obj.addProperty(\"" + prop + "\", this." + prop + ".stream().map(e -> e.toJSONObject()).collect(",
          JSONArray.class, ".toJSONArray()));");
    }

    w.println("    return obj;");
    w.println("  }");
    w.println();

    w.println("  // to JSON String");
    w.println();
    w.println("  public String toJSON() {");
    w.println("    return toJSONObject().render();");
    w.println("  }");
    w.println();
  }

  private void writeClassFooter() throws IOException {
    w.println("}");
  }

  // Identifiers & File Paths

  public ClassPackage getClassPackage() {
    return this.classPackage;
  }

  public String getFullClassName() {
    return this.classPackage.getFullClassName(getName());
  }

  public String getName() {
    return this.name;
  }

}
