// Generated by HotRod 5.1.12-SNAPSHOT on Feb 21, 2026 at 09:55:21

package app.persistence;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import app.persistence.dao.DataDAO;
import app.persistence.layout.DataLayout;

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class Data extends DataLayout {

  private static final long serialVersionUID = 1L;

  @SuppressWarnings("unused")
  @Autowired
  private DataDAO dataDAO;

  // Add custom code below.

}
