package tests;

import java.io.IOException;
import java.sql.SQLException;

import hotrod.test.generation.HouseDAO;
import hotrod.test.generation.VehicleDAO;
import hotrod.test.generation.primitives.SequenceGenerator;

public class AutogeneratedColumnTests {

  public static void main(final String[] args) throws IOException, SQLException {
    sequenceTest();
    identityTest();
    retrieveSequence();
  }

  private static void sequenceTest() throws SQLException {
    HouseDAO c = new HouseDAO();
    c.setId(1000);
    c.setAddress("123 House Rd");
    int rows = c.insert();

    System.out.println("inserted rows=" + rows);
    System.out.println("id=" + c.getId());
    System.out.println("row: " + c);
  }

  private static void identityTest() throws SQLException {
    VehicleDAO v = new VehicleDAO();
    v.setId(1000);
    v.setName("Volvo 4z");
    v.setMileage(1000);
    v.setVersionNumber(0L);
    int rows = v.insert();

    System.out.println("inserted rows=" + rows);
    System.out.println("id=" + v.getId());
    System.out.println("row: " + v);
  }

  private static void retrieveSequence() throws SQLException {
    long seq = SequenceGenerator.selectSequenceSeqHouse();
    System.out.println("seq: " + seq);
  }

}
