// Generated by HotRod 5.1.18 on Apr 11, 2026 at 23:56:23

package app.persistence.model;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import app.persistence.dao.OrderTypeADAO;
import app.persistence.layout.OrderTypeALayout;

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class OrderTypeA extends OrderTypeALayout {

  private static final long serialVersionUID = 1L;

  @SuppressWarnings("unused")
  @Autowired
  private OrderTypeADAO orderTypeADAO;

  // Add custom code below.

}
