// Autogenerated by HotRod -- Do not edit.

package test.persistence.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import test.persistence.primitives.CursorExample1;
import test.persistence.CursorExample1VO;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.SQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class CursorExample1DAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private SQLDialect sqlDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<test.persistence.CursorExample1VO> selectByExample(final test.persistence.primitives.CursorExample1 example, final CursorExample1OrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.primitives.CursorExample1, CursorExample1OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("test.persistence.primitives.cursorExample1.selectByExample", dwo);
  }

  public Cursor<test.persistence.CursorExample1VO> selectByExampleCursor(final test.persistence.primitives.CursorExample1 example, final CursorExample1OrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.primitives.CursorExample1, CursorExample1OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<test.persistence.CursorExample1VO>(this.sqlSession.selectCursor("test.persistence.primitives.cursorExample1.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<test.persistence.CursorExample1VO> selectByCriteria(final CursorExample1DAO.CursorExample1Table from,
      final Predicate predicate) {
    return new CriteriaWherePhase<test.persistence.CursorExample1VO>(from, this.sqlDialect, this.sqlSession,
        predicate, "test.persistence.primitives.cursorExample1.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public test.persistence.CursorExample1VO insert(final test.persistence.primitives.CursorExample1 vo) {
    String id = "test.persistence.primitives.cursorExample1.insert";
    this.sqlSession.insert(id, vo);
    test.persistence.CursorExample1VO mo = new test.persistence.CursorExample1VO();
    mo.setId(vo.getId());
    mo.setData(vo.getData());
    return mo;
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int updateByExample(final test.persistence.primitives.CursorExample1 example, final test.persistence.primitives.CursorExample1 updateValues) {
    UpdateByExampleDao<test.persistence.primitives.CursorExample1> fvd = //
      new UpdateByExampleDao<test.persistence.primitives.CursorExample1>(example, updateValues);
    return this.sqlSession.update("test.persistence.primitives.cursorExample1.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final test.persistence.primitives.CursorExample1 example) {
    return this.sqlSession.delete("test.persistence.primitives.cursorExample1.deleteByExample", example);
  }

  // DAO ordering

  public enum CursorExample1OrderBy implements OrderBy {

    ID("cursor_example1", "id", true), //
    ID$DESC("cursor_example1", "id", false), //
    DATA("cursor_example1", "data", true), //
    DATA$DESC("cursor_example1", "data", false), //
    DATA$CASEINSENSITIVE("cursor_example1", "lower(data)", true), //
    DATA$CASEINSENSITIVE_STABLE_FORWARD("cursor_example1", "lower(data), data", true), //
    DATA$CASEINSENSITIVE_STABLE_REVERSE("cursor_example1", "lower(data), data", false), //
    DATA$DESC_CASEINSENSITIVE("cursor_example1", "lower(data)", false), //
    DATA$DESC_CASEINSENSITIVE_STABLE_FORWARD("cursor_example1", "lower(data), data", false), //
    DATA$DESC_CASEINSENSITIVE_STABLE_REVERSE("cursor_example1", "lower(data), data", true);

    private CursorExample1OrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static CursorExample1Table newTable() {
    return new CursorExample1Table();
  }

  public static CursorExample1Table newTable(final String alias) {
    return new CursorExample1Table(alias);
  }

  public static class CursorExample1Table extends Table {

    // Properties

    public NumberColumn id;
    public StringColumn data;

    // Constructors

    CursorExample1Table() {
      super(null, null, "cursor_example1", "Table", null);
      initialize();
    }

    CursorExample1Table(final String alias) {
      super(null, null, "cursor_example1", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "id", "id");
      this.data = new StringColumn(this, "data", "data");
    }

  }

}
