// Autogenerated by HotRod -- Do not edit.

package test.persistence.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import test.persistence.FederalBranchVO;
import test.persistence.ClientVO;
import test.persistence.primitives.ClientDAO.ClientOrderBy;
import test.persistence.primitives.ClientDAO;
import test.persistence.TransactionVO;
import test.persistence.primitives.TransactionDAO.TransactionOrderBy;
import test.persistence.primitives.TransactionDAO;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.SQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class FederalBranchDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Lazy
  @Autowired
  private ClientDAO clientDAO;

  @Lazy
  @Autowired
  private TransactionDAO transactionDAO;

  @Autowired
  private SQLDialect sqlDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // select by primary key

  public test.persistence.FederalBranchVO selectByPK(final java.lang.Integer id) {
    if (id == null)
      return null;
    test.persistence.FederalBranchVO vo = new test.persistence.FederalBranchVO();
    vo.setId(id);
    return this.sqlSession.selectOne("test.persistence.primitives.federalBranch.selectByPK", vo);
  }

  // select by unique indexes: no unique indexes found (besides the PK) -- skipped

  // select by example

  public List<test.persistence.FederalBranchVO> selectByExample(final test.persistence.FederalBranchVO example, final FederalBranchOrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.FederalBranchVO, FederalBranchOrderBy> dwo = //
        new DaoWithOrder<test.persistence.FederalBranchVO, FederalBranchOrderBy>(example, orderBies);
    return this.sqlSession.selectList("test.persistence.primitives.federalBranch.selectByExample", dwo);
  }

  public Cursor<test.persistence.FederalBranchVO> selectByExampleCursor(final test.persistence.FederalBranchVO example, final FederalBranchOrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.FederalBranchVO, FederalBranchOrderBy> dwo = //
        new DaoWithOrder<test.persistence.FederalBranchVO, FederalBranchOrderBy>(example, orderBies);
    return new MyBatisCursor<test.persistence.FederalBranchVO>(this.sqlSession.selectCursor("test.persistence.primitives.federalBranch.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<test.persistence.FederalBranchVO> selectByCriteria(final FederalBranchDAO.FederalBranchTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<test.persistence.FederalBranchVO>(from, this.sqlDialect, this.sqlSession,
        predicate, "test.persistence.primitives.federalBranch.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs

  public SelectChildrenClientPhase selectChildrenClientOf(final FederalBranchVO vo) {
    return new SelectChildrenClientPhase(vo);
  }

  public class SelectChildrenClientPhase {

    private FederalBranchVO vo;

    SelectChildrenClientPhase(final FederalBranchVO vo) {
      this.vo = vo;
    }

    public SelectChildrenClientFromIdPhase fromId() {
      return new SelectChildrenClientFromIdPhase(this.vo);
    }

  }

  public class SelectChildrenClientFromIdPhase {

    private FederalBranchVO vo;

    SelectChildrenClientFromIdPhase(final FederalBranchVO vo) {
      this.vo = vo;
    }

    public List<ClientVO> toBranchId(final ClientOrderBy... orderBies) {
      ClientVO example = new ClientVO();
      example.setBranchId(this.vo.getId());
      return clientDAO.selectByExample(example, orderBies);
    }

    public Cursor<ClientVO> cursorToBranchId(final ClientOrderBy... orderBies) {
      ClientVO example = new ClientVO();
      example.setBranchId(this.vo.getId());
      return clientDAO.selectByExampleCursor(example, orderBies);
    }

  }

  public SelectChildrenTransactionPhase selectChildrenTransactionOf(final FederalBranchVO vo) {
    return new SelectChildrenTransactionPhase(vo);
  }

  public class SelectChildrenTransactionPhase {

    private FederalBranchVO vo;

    SelectChildrenTransactionPhase(final FederalBranchVO vo) {
      this.vo = vo;
    }

    public SelectChildrenTransactionFromIdPhase fromId() {
      return new SelectChildrenTransactionFromIdPhase(this.vo);
    }

  }

  public class SelectChildrenTransactionFromIdPhase {

    private FederalBranchVO vo;

    SelectChildrenTransactionFromIdPhase(final FederalBranchVO vo) {
      this.vo = vo;
    }

    public List<TransactionVO> toFedBranchId(final TransactionOrderBy... orderBies) {
      TransactionVO example = new TransactionVO();
      example.setFedBranchId((this.vo.getId() == null) ? null : Long.valueOf(this.vo.getId().longValue()));
      return transactionDAO.selectByExample(example, orderBies);
    }

    public Cursor<TransactionVO> cursorToFedBranchId(final TransactionOrderBy... orderBies) {
      TransactionVO example = new TransactionVO();
      example.setFedBranchId((this.vo.getId() == null) ? null : Long.valueOf(this.vo.getId().longValue()));
      return transactionDAO.selectByExampleCursor(example, orderBies);
    }

  }

  // insert

  public int insert(final test.persistence.FederalBranchVO vo) {
    String id = "test.persistence.primitives.federalBranch.insert";
    return this.sqlSession.insert(id, vo);
  }

  // update by PK

  public int update(final test.persistence.FederalBranchVO vo) {
    if (vo.id == null) return 0;
    return this.sqlSession.update("test.persistence.primitives.federalBranch.updateByPK", vo);
  }

  // delete by PK

  public int delete(final test.persistence.FederalBranchVO vo) {
    if (vo.id == null) return 0;
    return this.sqlSession.delete("test.persistence.primitives.federalBranch.deleteByPK", vo);
  }

  // update by example

  public int updateByExample(final test.persistence.FederalBranchVO example, final test.persistence.FederalBranchVO updateValues) {
    UpdateByExampleDao<test.persistence.FederalBranchVO> fvd = //
      new UpdateByExampleDao<test.persistence.FederalBranchVO>(example, updateValues);
    return this.sqlSession.update("test.persistence.primitives.federalBranch.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final test.persistence.FederalBranchVO example) {
    return this.sqlSession.delete("test.persistence.primitives.federalBranch.deleteByExample", example);
  }

  // DAO ordering

  public enum FederalBranchOrderBy implements OrderBy {

    ID("federal_branch", "id", true), //
    ID$DESC("federal_branch", "id", false), //
    NAME("federal_branch", "name", true), //
    NAME$DESC("federal_branch", "name", false), //
    NAME$CASEINSENSITIVE("federal_branch", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("federal_branch", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("federal_branch", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("federal_branch", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("federal_branch", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("federal_branch", "lower(name), name", true);

    private FederalBranchOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static FederalBranchTable newTable() {
    return new FederalBranchTable();
  }

  public static FederalBranchTable newTable(final String alias) {
    return new FederalBranchTable(alias);
  }

  public static class FederalBranchTable extends Table {

    // Properties

    public NumberColumn id;
    public StringColumn name;

    // Constructors

    FederalBranchTable() {
      super(null, null, "federal_branch", "Table", null);
      initialize();
    }

    FederalBranchTable(final String alias) {
      super(null, null, "federal_branch", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "id", "id");
      this.name = new StringColumn(this, "name", "name");
    }

  }

}
