// Autogenerated by HotRod -- Do not edit.

package test.persistence.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import test.persistence.primitives.TestDefault1;
import test.persistence.TestDefault1VO;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.SQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class TestDefault1DAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private SQLDialect sqlDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<test.persistence.TestDefault1VO> selectByExample(final test.persistence.primitives.TestDefault1 example, final TestDefault1OrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.primitives.TestDefault1, TestDefault1OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("test.persistence.primitives.testDefault1.selectByExample", dwo);
  }

  public Cursor<test.persistence.TestDefault1VO> selectByExampleCursor(final test.persistence.primitives.TestDefault1 example, final TestDefault1OrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.primitives.TestDefault1, TestDefault1OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<test.persistence.TestDefault1VO>(this.sqlSession.selectCursor("test.persistence.primitives.testDefault1.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<test.persistence.TestDefault1VO> selectByCriteria(final TestDefault1DAO.TestDefault1Table from,
      final Predicate predicate) {
    return new CriteriaWherePhase<test.persistence.TestDefault1VO>(from, this.sqlDialect, this.sqlSession,
        predicate, "test.persistence.primitives.testDefault1.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public test.persistence.TestDefault1VO insert(final test.persistence.primitives.TestDefault1 vo) {
    return insert(vo, false);
  }

  public test.persistence.TestDefault1VO insert(final test.persistence.primitives.TestDefault1 vo, final boolean retrieveDefaults) {
    String id = retrieveDefaults ? "test.persistence.primitives.testDefault1.insertRetrievingDefaults" : "test.persistence.primitives.testDefault1.insert";
    this.sqlSession.insert(id, vo);
    test.persistence.TestDefault1VO mo = new test.persistence.TestDefault1VO();
    mo.setName(vo.getName());
    mo.setPrice(vo.getPrice());
    return mo;
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int updateByExample(final test.persistence.primitives.TestDefault1 example, final test.persistence.primitives.TestDefault1 updateValues) {
    UpdateByExampleDao<test.persistence.primitives.TestDefault1> fvd = //
      new UpdateByExampleDao<test.persistence.primitives.TestDefault1>(example, updateValues);
    return this.sqlSession.update("test.persistence.primitives.testDefault1.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final test.persistence.primitives.TestDefault1 example) {
    return this.sqlSession.delete("test.persistence.primitives.testDefault1.deleteByExample", example);
  }

  // DAO ordering

  public enum TestDefault1OrderBy implements OrderBy {

    NAME("test_default1", "name", true), //
    NAME$DESC("test_default1", "name", false), //
    NAME$CASEINSENSITIVE("test_default1", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("test_default1", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("test_default1", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("test_default1", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("test_default1", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("test_default1", "lower(name), name", true), //
    PRICE("test_default1", "price", true), //
    PRICE$DESC("test_default1", "price", false);

    private TestDefault1OrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static TestDefault1Table newTable() {
    return new TestDefault1Table();
  }

  public static TestDefault1Table newTable(final String alias) {
    return new TestDefault1Table(alias);
  }

  public static class TestDefault1Table extends Table {

    // Properties

    public StringColumn name;
    public NumberColumn price;

    // Constructors

    TestDefault1Table() {
      super(null, null, "test_default1", "Table", null);
      initialize();
    }

    TestDefault1Table(final String alias) {
      super(null, null, "test_default1", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.name = new StringColumn(this, "name", "name");
      this.price = new NumberColumn(this, "price", "price");
    }

  }

}
