// Autogenerated by HotRod -- Do not edit.

package test.persistence.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import test.persistence.TestIdentity1VO;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.SQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class TestIdentity1DAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private SQLDialect sqlDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<test.persistence.TestIdentity1VO> selectByExample(final test.persistence.TestIdentity1VO example, final TestIdentity1OrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.TestIdentity1VO, TestIdentity1OrderBy> dwo = //
        new DaoWithOrder<test.persistence.TestIdentity1VO, TestIdentity1OrderBy>(example, orderBies);
    return this.sqlSession.selectList("test.persistence.primitives.testIdentity1.selectByExample", dwo);
  }

  public Cursor<test.persistence.TestIdentity1VO> selectByExampleCursor(final test.persistence.TestIdentity1VO example, final TestIdentity1OrderBy... orderBies)
      {
    DaoWithOrder<test.persistence.TestIdentity1VO, TestIdentity1OrderBy> dwo = //
        new DaoWithOrder<test.persistence.TestIdentity1VO, TestIdentity1OrderBy>(example, orderBies);
    return new MyBatisCursor<test.persistence.TestIdentity1VO>(this.sqlSession.selectCursor("test.persistence.primitives.testIdentity1.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<test.persistence.TestIdentity1VO> selectByCriteria(final TestIdentity1DAO.TestIdentity1Table from,
      final Predicate predicate) {
    return new CriteriaWherePhase<test.persistence.TestIdentity1VO>(from, this.sqlDialect, this.sqlSession,
        predicate, "test.persistence.primitives.testIdentity1.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public int insert(final test.persistence.TestIdentity1VO vo) {
    String id = "test.persistence.primitives.testIdentity1.insert";
    int rows = this.sqlSession.insert(id, vo);
    return rows;
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int updateByExample(final test.persistence.TestIdentity1VO example, final test.persistence.TestIdentity1VO updateValues) {
    UpdateByExampleDao<test.persistence.TestIdentity1VO> fvd = //
      new UpdateByExampleDao<test.persistence.TestIdentity1VO>(example, updateValues);
    return this.sqlSession.update("test.persistence.primitives.testIdentity1.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final test.persistence.TestIdentity1VO example) {
    return this.sqlSession.delete("test.persistence.primitives.testIdentity1.deleteByExample", example);
  }

  // DAO ordering

  public enum TestIdentity1OrderBy implements OrderBy {

    ID("test_identity1", "id", true), //
    ID$DESC("test_identity1", "id", false), //
    NAME("test_identity1", "name", true), //
    NAME$DESC("test_identity1", "name", false), //
    NAME$CASEINSENSITIVE("test_identity1", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("test_identity1", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("test_identity1", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("test_identity1", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("test_identity1", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("test_identity1", "lower(name), name", true);

    private TestIdentity1OrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static TestIdentity1Table newTable() {
    return new TestIdentity1Table();
  }

  public static TestIdentity1Table newTable(final String alias) {
    return new TestIdentity1Table(alias);
  }

  public static class TestIdentity1Table extends Table {

    // Properties

    public NumberColumn id;
    public StringColumn name;

    // Constructors

    TestIdentity1Table() {
      super(null, null, "test_identity1", "Table", null);
      initialize();
    }

    TestIdentity1Table(final String alias) {
      super(null, null, "test_identity1", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "id", "id");
      this.name = new StringColumn(this, "name", "name");
    }

  }

}
