// Autogenerated by HotRod -- Do not edit.

package test.persistence.primitives;

import java.io.Serializable;
import org.hotrod.runtime.json.*;

public class TypesNumeric implements Serializable {

  private static final long serialVersionUID = 1L;

  // VO Properties (table columns)

  protected java.lang.Short int1 = null;
  protected java.lang.Integer int2 = null;
  protected java.lang.Long int3 = null;
  protected java.lang.Object int4 = null;
  protected java.lang.Integer int5 = null;
  protected java.lang.Long int6 = null;
  protected java.math.BigDecimal dec1 = null;
  protected java.math.BigDecimal dec2 = null;
  protected java.lang.Byte dec3 = null;
  protected java.lang.Short dec4 = null;
  protected java.lang.Integer dec5 = null;
  protected java.lang.Long dec6 = null;
  protected java.math.BigInteger dec7 = null;
  protected java.lang.Float flo1 = null;
  protected java.lang.Double flo2 = null;

  // getters & setters

  public java.lang.Short getInt1() {
    return this.int1;
  }

  public void setInt1(final java.lang.Short int1) {
    this.int1 = int1;
    this.getPropertiesChangeLog().int1WasSet = true;
  }

  public java.lang.Integer getInt2() {
    return this.int2;
  }

  public void setInt2(final java.lang.Integer int2) {
    this.int2 = int2;
    this.getPropertiesChangeLog().int2WasSet = true;
  }

  public java.lang.Long getInt3() {
    return this.int3;
  }

  public void setInt3(final java.lang.Long int3) {
    this.int3 = int3;
    this.getPropertiesChangeLog().int3WasSet = true;
  }

  public java.lang.Object getInt4() {
    return this.int4;
  }

  public void setInt4(final java.lang.Object int4) {
    this.int4 = int4;
    this.getPropertiesChangeLog().int4WasSet = true;
  }

  public java.lang.Integer getInt5() {
    return this.int5;
  }

  public void setInt5(final java.lang.Integer int5) {
    this.int5 = int5;
    this.getPropertiesChangeLog().int5WasSet = true;
  }

  public java.lang.Long getInt6() {
    return this.int6;
  }

  public void setInt6(final java.lang.Long int6) {
    this.int6 = int6;
    this.getPropertiesChangeLog().int6WasSet = true;
  }

  public java.math.BigDecimal getDec1() {
    return this.dec1;
  }

  public void setDec1(final java.math.BigDecimal dec1) {
    this.dec1 = dec1;
    this.getPropertiesChangeLog().dec1WasSet = true;
  }

  public java.math.BigDecimal getDec2() {
    return this.dec2;
  }

  public void setDec2(final java.math.BigDecimal dec2) {
    this.dec2 = dec2;
    this.getPropertiesChangeLog().dec2WasSet = true;
  }

  public java.lang.Byte getDec3() {
    return this.dec3;
  }

  public void setDec3(final java.lang.Byte dec3) {
    this.dec3 = dec3;
    this.getPropertiesChangeLog().dec3WasSet = true;
  }

  public java.lang.Short getDec4() {
    return this.dec4;
  }

  public void setDec4(final java.lang.Short dec4) {
    this.dec4 = dec4;
    this.getPropertiesChangeLog().dec4WasSet = true;
  }

  public java.lang.Integer getDec5() {
    return this.dec5;
  }

  public void setDec5(final java.lang.Integer dec5) {
    this.dec5 = dec5;
    this.getPropertiesChangeLog().dec5WasSet = true;
  }

  public java.lang.Long getDec6() {
    return this.dec6;
  }

  public void setDec6(final java.lang.Long dec6) {
    this.dec6 = dec6;
    this.getPropertiesChangeLog().dec6WasSet = true;
  }

  public java.math.BigInteger getDec7() {
    return this.dec7;
  }

  public void setDec7(final java.math.BigInteger dec7) {
    this.dec7 = dec7;
    this.getPropertiesChangeLog().dec7WasSet = true;
  }

  public java.lang.Float getFlo1() {
    return this.flo1;
  }

  public void setFlo1(final java.lang.Float flo1) {
    this.flo1 = flo1;
    this.getPropertiesChangeLog().flo1WasSet = true;
  }

  public java.lang.Double getFlo2() {
    return this.flo2;
  }

  public void setFlo2(final java.lang.Double flo2) {
    this.flo2 = flo2;
    this.getPropertiesChangeLog().flo2WasSet = true;
  }

  // to string

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- int1=" + this.int1 + "\n");
    sb.append("- int2=" + this.int2 + "\n");
    sb.append("- int3=" + this.int3 + "\n");
    sb.append("- int4=" + this.int4 + "\n");
    sb.append("- int5=" + this.int5 + "\n");
    sb.append("- int6=" + this.int6 + "\n");
    sb.append("- dec1=" + this.dec1 + "\n");
    sb.append("- dec2=" + this.dec2 + "\n");
    sb.append("- dec3=" + this.dec3 + "\n");
    sb.append("- dec4=" + this.dec4 + "\n");
    sb.append("- dec5=" + this.dec5 + "\n");
    sb.append("- dec6=" + this.dec6 + "\n");
    sb.append("- dec7=" + this.dec7 + "\n");
    sb.append("- flo1=" + this.flo1 + "\n");
    sb.append("- flo2=" + this.flo2);
    return sb.toString();
  }

  // to JSON

  public String toJSON() {
    JSONObject obj = new JSONObject();
    obj.addProperty("int1", this.int1);
    obj.addProperty("int2", this.int2);
    obj.addProperty("int3", this.int3);
    obj.addProperty("int4", this.int4);
    obj.addProperty("int5", this.int5);
    obj.addProperty("int6", this.int6);
    obj.addProperty("dec1", this.dec1);
    obj.addProperty("dec2", this.dec2);
    obj.addProperty("dec3", this.dec3);
    obj.addProperty("dec4", this.dec4);
    obj.addProperty("dec5", this.dec5);
    obj.addProperty("dec6", this.dec6);
    obj.addProperty("dec7", this.dec7);
    obj.addProperty("flo1", this.flo1);
    obj.addProperty("flo2", this.flo2);
    return obj.render();
  }

  // Properties change log

  private PropertiesChangeLog propertiesChangeLog = new PropertiesChangeLog();

  protected PropertiesChangeLog getPropertiesChangeLog() {
    return propertiesChangeLog;
  }

  protected class PropertiesChangeLog {
    public boolean int1WasSet = false;
    public boolean int2WasSet = false;
    public boolean int3WasSet = false;
    public boolean int4WasSet = false;
    public boolean int5WasSet = false;
    public boolean int6WasSet = false;
    public boolean dec1WasSet = false;
    public boolean dec2WasSet = false;
    public boolean dec3WasSet = false;
    public boolean dec4WasSet = false;
    public boolean dec5WasSet = false;
    public boolean dec6WasSet = false;
    public boolean dec7WasSet = false;
    public boolean flo1WasSet = false;
    public boolean flo2WasSet = false;
  }

}
