// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import org.hotrod.runtime.json.*;

public class AbstractVehicleVO implements Serializable {

  private static final long serialVersionUID = 1L;

  // VO Properties (table columns)

  protected java.lang.Integer id = null;
  protected java.lang.String name = null;
  protected java.lang.Integer mileage = null;
  protected java.lang.Short versionNumber = null;
  protected java.lang.Integer vtype = null;

  // getters & setters

  public java.lang.Integer getId() {
    return this.id;
  }

  public void setId(final java.lang.Integer id) {
    this.id = id;
  }

  public java.lang.String getName() {
    return this.name;
  }

  public void setName(final java.lang.String name) {
    this.name = name;
  }

  public java.lang.Integer getMileage() {
    return this.mileage;
  }

  public void setMileage(final java.lang.Integer mileage) {
    this.mileage = mileage;
  }

  public java.lang.Short getVersionNumber() {
    return this.versionNumber;
  }

  public void setVersionNumber(final java.lang.Short versionNumber) {
    this.versionNumber = versionNumber;
  }

  public java.lang.Integer getVtype() {
    return this.vtype;
  }

  public void setVtype(final java.lang.Integer vtype) {
    this.vtype = vtype;
  }

  // to string

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- id=" + this.id + "\n");
    sb.append("- name=" + this.name + "\n");
    sb.append("- mileage=" + this.mileage + "\n");
    sb.append("- versionNumber=" + this.versionNumber + "\n");
    sb.append("- vtype=" + this.vtype);
    return sb.toString();
  }

  // to JSON

  public String toJSON() {
    JSONObject obj = new JSONObject();
    obj.addProperty("id", this.id);
    obj.addProperty("name", this.name);
    obj.addProperty("mileage", this.mileage);
    obj.addProperty("versionNumber", this.versionNumber);
    obj.addProperty("vtype", this.vtype);
    return obj.render();
  }

}
