// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import org.hotrod.runtime.json.*;

public class AbstractTxBranchVO implements Serializable {

  private static final long serialVersionUID = 1L;

  // VO Properties (view columns)

  protected java.lang.Integer accountId = null;
  protected java.lang.Integer branchId = null;
  protected java.lang.String branchName = null;
  protected java.lang.Integer amount = null;

  // getters & setters

  public java.lang.Integer getAccountId() {
    return this.accountId;
  }

  public void setAccountId(final java.lang.Integer accountId) {
    this.accountId = accountId;
  }

  public java.lang.Integer getBranchId() {
    return this.branchId;
  }

  public void setBranchId(final java.lang.Integer branchId) {
    this.branchId = branchId;
  }

  public java.lang.String getBranchName() {
    return this.branchName;
  }

  public void setBranchName(final java.lang.String branchName) {
    this.branchName = branchName;
  }

  public java.lang.Integer getAmount() {
    return this.amount;
  }

  public void setAmount(final java.lang.Integer amount) {
    this.amount = amount;
  }

  // to string

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- accountId=" + this.accountId + "\n");
    sb.append("- branchId=" + this.branchId + "\n");
    sb.append("- branchName=" + this.branchName + "\n");
    sb.append("- amount=" + this.amount);
    return sb.toString();
  }

  // to JSON

  public String toJSON() {
    JSONObject obj = new JSONObject();
    obj.addProperty("accountId", this.accountId);
    obj.addProperty("branchId", this.branchId);
    obj.addProperty("branchName", this.branchName);
    obj.addProperty("amount", this.amount);
    return obj.render();
  }

}
