// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import org.hotrod.runtime.json.*;

public class AbstractHolidayVO implements Serializable {

  private static final long serialVersionUID = 1L;

  // VO Properties (table columns)

  protected java.sql.Date d = null;

  // getters & setters

  public java.sql.Date getD() {
    return this.d;
  }

  public void setD(final java.sql.Date d) {
    this.d = d;
  }

  // to string

  public String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- d=" + this.d);
    return sb.toString();
  }

  // to JSON

  public String toJSON() {
    JSONObject obj = new JSONObject();
    obj.addProperty("d", this.d);
    return obj.render();
  }

}
