// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import app.daos.primitives.Employee;
import app.daos.EmployeeVO;

import java.util.Map;
import java.util.HashMap;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.queries.DeleteWherePhase;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class EmployeeDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // select by primary key

  public app.daos.EmployeeVO select(final java.lang.Integer id) {
    if (id == null)
      return null;
    app.daos.EmployeeVO vo = new app.daos.EmployeeVO();
    vo.setId(id);
    return this.sqlSession.selectOne("mappers.employee.selectByPK", vo);
  }

  // select by unique indexes: no unique indexes found (besides the PK) -- skipped

  // select by example

  public List<app.daos.EmployeeVO> select(final app.daos.primitives.Employee example, final EmployeeOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.Employee, EmployeeOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("mappers.employee.selectByExample", dwo);
  }

  public Cursor<app.daos.EmployeeVO> selectCursor(final app.daos.primitives.Employee example, final EmployeeOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.Employee, EmployeeOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.EmployeeVO>(this.sqlSession.selectCursor("mappers.employee.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.EmployeeVO> select(final EmployeeDAO.EmployeeTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.EmployeeVO>(from, this.liveSQLDialect, this.sqlSession,
        predicate, "mappers.employee.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public app.daos.EmployeeVO insert(final app.daos.primitives.Employee vo) {
    String id = "mappers.employee.insert";
    int rows = this.sqlSession.insert(id, vo);
    app.daos.EmployeeVO mo = new app.daos.EmployeeVO();
    mo.setId(vo.getId());
    mo.setName(vo.getName());
    mo.setBranchId(vo.getBranchId());
    mo.setSalary(vo.getSalary());
    return mo;
  }

  // update by PK

  public int update(final app.daos.EmployeeVO vo) {
    if (vo.id == null) return 0;
    return this.sqlSession.update("mappers.employee.updateByPK", vo);
  }

  // delete by PK

  public int delete(final java.lang.Integer id) {
    if (id == null) return 0;
    app.daos.EmployeeVO vo = new app.daos.EmployeeVO();
    vo.setId(id);
    if (vo.id == null) return 0;
    return this.sqlSession.delete("mappers.employee.deleteByPK", vo);
  }

  // update by example

  public int update(final app.daos.primitives.Employee example, final app.daos.primitives.Employee updateValues) {
    UpdateByExampleDao<app.daos.primitives.Employee> fvd = //
      new UpdateByExampleDao<app.daos.primitives.Employee>(example, updateValues);
    return this.sqlSession.update("mappers.employee.updateByExample", fvd);
  }

  // update by criteria

  public UpdateSetCompletePhase update(final app.daos.primitives.Employee updateValues, final EmployeeDAO.EmployeeTable tableOrView, final Predicate predicate) {
    Map<String, Object> values = new HashMap<>();
    if (updateValues.getId() != null) values.put("id", updateValues.getId());
    if (updateValues.getName() != null) values.put("name", updateValues.getName());
    if (updateValues.getBranchId() != null) values.put("branch_id", updateValues.getBranchId());
    if (updateValues.getSalary() != null) values.put("salary", updateValues.getSalary());
    return new UpdateSetCompletePhase(tableOrView, this.liveSQLDialect, this.sqlSession,
      "mappers.employee.updateByCriteria", predicate, values);
  }


  // delete by example

  public int delete(final app.daos.primitives.Employee example) {
    return this.sqlSession.delete("mappers.employee.deleteByExample", example);
  }

  // delete by criteria

  public DeleteWherePhase delete(final EmployeeDAO.EmployeeTable from, final Predicate predicate) {
    return new DeleteWherePhase(from, this.liveSQLDialect, this.sqlSession,
      "mappers.employee.deleteByCriteria", predicate);
  }

  // DAO ordering

  public enum EmployeeOrderBy implements OrderBy {

    ID("public.employee", "id", true), //
    ID$DESC("public.employee", "id", false), //
    NAME("public.employee", "name", true), //
    NAME$DESC("public.employee", "name", false), //
    NAME$CASEINSENSITIVE("public.employee", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("public.employee", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("public.employee", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("public.employee", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("public.employee", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("public.employee", "lower(name), name", true), //
    BRANCH_ID("public.employee", "branch_id", true), //
    BRANCH_ID$DESC("public.employee", "branch_id", false), //
    SALARY("public.employee", "salary", true), //
    SALARY$DESC("public.employee", "salary", false);

    private EmployeeOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static EmployeeTable newTable() {
    return new EmployeeTable();
  }

  public static EmployeeTable newTable(final String alias) {
    return new EmployeeTable(alias);
  }

  public static class EmployeeTable extends Table {

    // Properties

    public NumberColumn id;
    public StringColumn name;
    public NumberColumn branchId;
    public NumberColumn salary;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.id, this.name, this.branchId, this.salary);
    }

    // Constructors

    EmployeeTable() {
      super(null, "PUBLIC", "EMPLOYEE", "Table", null);
      initialize();
    }

    EmployeeTable(final String alias) {
      super(null, "PUBLIC", "EMPLOYEE", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "ID", "id", "INTEGER", 32, 0);
      this.name = new StringColumn(this, "NAME", "name", "CHARACTER VARYING", 20, 0);
      this.branchId = new NumberColumn(this, "BRANCH_ID", "branchId", "INTEGER", 32, 0);
      this.salary = new NumberColumn(this, "SALARY", "salary", "INTEGER", 32, 0);
    }

  }

}
