// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import app.daos.primitives.AbstractLogVO;
import app.daos.LogVO;

import java.util.Map;
import java.util.HashMap;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.queries.DeleteWherePhase;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class LogDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<app.daos.LogVO> select(final app.daos.primitives.AbstractLogVO example, final LogOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractLogVO, LogOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("mappers.log.selectByExample", dwo);
  }

  public Cursor<app.daos.LogVO> selectCursor(final app.daos.primitives.AbstractLogVO example, final LogOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractLogVO, LogOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.LogVO>(this.sqlSession.selectCursor("mappers.log.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.LogVO> select(final LogDAO.LogTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.LogVO>(from, this.liveSQLDialect, this.sqlSession,
        predicate, "mappers.log.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public app.daos.LogVO insert(final app.daos.primitives.AbstractLogVO vo) {
    String id = "mappers.log.insert";
    this.sqlSession.insert(id, vo);
    app.daos.LogVO mo = new app.daos.LogVO();
    mo.setRecordedAt(vo.getRecordedAt());
    mo.setNotes(vo.getNotes());
    return mo;
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int update(final app.daos.primitives.AbstractLogVO example, final app.daos.primitives.AbstractLogVO updateValues) {
    UpdateByExampleDao<app.daos.primitives.AbstractLogVO> fvd = //
      new UpdateByExampleDao<app.daos.primitives.AbstractLogVO>(example, updateValues);
    return this.sqlSession.update("mappers.log.updateByExample", fvd);
  }

  // update by criteria

  public UpdateSetCompletePhase update(final app.daos.primitives.AbstractLogVO updateValues, final LogDAO.LogTable tableOrView, final Predicate predicate) {
    Map<String, Object> values = new HashMap<>();
    if (updateValues.getRecordedAt() != null) values.put("recorded_at", updateValues.getRecordedAt());
    if (updateValues.getNotes() != null) values.put("notes", updateValues.getNotes());
    return new UpdateSetCompletePhase(tableOrView, this.liveSQLDialect, this.sqlSession,
      "mappers.log.updateByCriteria", predicate, values);
  }


  // delete by example

  public int delete(final app.daos.primitives.AbstractLogVO example) {
    return this.sqlSession.delete("mappers.log.deleteByExample", example);
  }

  // delete by criteria

  public DeleteWherePhase delete(final LogDAO.LogTable from, final Predicate predicate) {
    return new DeleteWherePhase(from, this.liveSQLDialect, this.sqlSession,
      "mappers.log.deleteByCriteria", predicate);
  }

  // DAO ordering

  public enum LogOrderBy implements OrderBy {

    RECORDED_AT("public.log", "recorded_at", true), //
    RECORDED_AT$DESC("public.log", "recorded_at", false), //
    NOTES("public.log", "notes", true), //
    NOTES$DESC("public.log", "notes", false), //
    NOTES$CASEINSENSITIVE("public.log", "lower(notes)", true), //
    NOTES$CASEINSENSITIVE_STABLE_FORWARD("public.log", "lower(notes), notes", true), //
    NOTES$CASEINSENSITIVE_STABLE_REVERSE("public.log", "lower(notes), notes", false), //
    NOTES$DESC_CASEINSENSITIVE("public.log", "lower(notes)", false), //
    NOTES$DESC_CASEINSENSITIVE_STABLE_FORWARD("public.log", "lower(notes), notes", false), //
    NOTES$DESC_CASEINSENSITIVE_STABLE_REVERSE("public.log", "lower(notes), notes", true);

    private LogOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static LogTable newTable() {
    return new LogTable();
  }

  public static LogTable newTable(final String alias) {
    return new LogTable(alias);
  }

  public static class LogTable extends Table {

    // Properties

    public DateTimeColumn recordedAt;
    public StringColumn notes;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.recordedAt, this.notes);
    }

    // Constructors

    LogTable() {
      super(null, "public", "log", "Table", null);
      initialize();
    }

    LogTable(final String alias) {
      super(null, "public", "log", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.recordedAt = new DateTimeColumn(this, "recorded_at", "recordedAt", "timestamp", 29, 6);
      this.notes = new StringColumn(this, "notes", "notes", "varchar", 100, 0);
    }

  }

}
