// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import app.daos.primitives.AbstractTestIdentity1VO;
import app.daos.TestIdentity1VO;

import java.util.Map;
import java.util.HashMap;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.queries.DeleteWherePhase;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class TestIdentity1DAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<app.daos.TestIdentity1VO> select(final app.daos.primitives.AbstractTestIdentity1VO example, final TestIdentity1OrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractTestIdentity1VO, TestIdentity1OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("mappers.testIdentity1.selectByExample", dwo);
  }

  public Cursor<app.daos.TestIdentity1VO> selectCursor(final app.daos.primitives.AbstractTestIdentity1VO example, final TestIdentity1OrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractTestIdentity1VO, TestIdentity1OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.TestIdentity1VO>(this.sqlSession.selectCursor("mappers.testIdentity1.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.TestIdentity1VO> select(final TestIdentity1DAO.TestIdentity1Table from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.TestIdentity1VO>(from, this.liveSQLDialect, this.sqlSession,
        predicate, "mappers.testIdentity1.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public app.daos.TestIdentity1VO insert(final app.daos.primitives.AbstractTestIdentity1VO vo) {
    String id = "mappers.testIdentity1.insert";
    int rows = this.sqlSession.insert(id, vo);
    app.daos.TestIdentity1VO mo = new app.daos.TestIdentity1VO();
    mo.setId(vo.getId());
    mo.setName(vo.getName());
    return mo;
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int update(final app.daos.primitives.AbstractTestIdentity1VO example, final app.daos.primitives.AbstractTestIdentity1VO updateValues) {
    UpdateByExampleDao<app.daos.primitives.AbstractTestIdentity1VO> fvd = //
      new UpdateByExampleDao<app.daos.primitives.AbstractTestIdentity1VO>(example, updateValues);
    return this.sqlSession.update("mappers.testIdentity1.updateByExample", fvd);
  }

  // update by criteria

  public UpdateSetCompletePhase update(final app.daos.primitives.AbstractTestIdentity1VO updateValues, final TestIdentity1DAO.TestIdentity1Table tableOrView, final Predicate predicate) {
    Map<String, Object> values = new HashMap<>();
    if (updateValues.getId() != null) values.put("id", updateValues.getId());
    if (updateValues.getName() != null) values.put("name", updateValues.getName());
    return new UpdateSetCompletePhase(tableOrView, this.liveSQLDialect, this.sqlSession,
      "mappers.testIdentity1.updateByCriteria", predicate, values);
  }


  // delete by example

  public int delete(final app.daos.primitives.AbstractTestIdentity1VO example) {
    return this.sqlSession.delete("mappers.testIdentity1.deleteByExample", example);
  }

  // delete by criteria

  public DeleteWherePhase delete(final TestIdentity1DAO.TestIdentity1Table from, final Predicate predicate) {
    return new DeleteWherePhase(from, this.liveSQLDialect, this.sqlSession,
      "mappers.testIdentity1.deleteByCriteria", predicate);
  }

  // DAO ordering

  public enum TestIdentity1OrderBy implements OrderBy {

    ID("public.test_identity1", "id", true), //
    ID$DESC("public.test_identity1", "id", false), //
    NAME("public.test_identity1", "name", true), //
    NAME$DESC("public.test_identity1", "name", false), //
    NAME$CASEINSENSITIVE("public.test_identity1", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("public.test_identity1", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("public.test_identity1", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("public.test_identity1", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("public.test_identity1", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("public.test_identity1", "lower(name), name", true);

    private TestIdentity1OrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static TestIdentity1Table newTable() {
    return new TestIdentity1Table();
  }

  public static TestIdentity1Table newTable(final String alias) {
    return new TestIdentity1Table(alias);
  }

  public static class TestIdentity1Table extends Table {

    // Properties

    public NumberColumn id;
    public StringColumn name;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.id, this.name);
    }

    // Constructors

    TestIdentity1Table() {
      super(null, "public", "test_identity1", "Table", null);
      initialize();
    }

    TestIdentity1Table(final String alias) {
      super(null, "public", "test_identity1", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "id", "id", "int4", 10, 0);
      this.name = new StringColumn(this, "name", "name", "varchar", 40, 0);
    }

  }

}
