// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;
import org.hotrod.runtime.interfaces.Selectable;

import app.daos.primitives.V2;
import app.daos.V2VO;

import java.util.Map;
import java.util.HashMap;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.queries.DeleteWherePhase;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class V2DAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // Row Parser

  public app.daos.V2VO parseRow(Map<String, Object> m) {
    app.daos.V2VO mo = this.applicationContext.getBean(app.daos.V2VO.class);
    mo.setId((java.lang.Integer) m.get("id"));
    mo.setName((java.lang.String) m.get("name"));
    return mo;
  }

  // select by example

  public List<app.daos.V2VO> select(final app.daos.primitives.V2 example, final V2OrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.V2, V2OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("mappers.v2.selectByExample", dwo);
  }

  public Cursor<app.daos.V2VO> selectCursor(final app.daos.primitives.V2 example, final V2OrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.V2, V2OrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.V2VO>(this.sqlSession.selectCursor("mappers.v2.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.V2VO> select(final V2DAO.V2View from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.V2VO>(from, this.liveSQLDialect, this.sqlSession,
        predicate, "mappers.v2.selectByCriteria");
  }

  // insert by example

  public int insertByExample(final app.daos.primitives.V2 example) {
    return sqlSession.insert("mappers.v2.insertByExample", example);
  }

  // update by example

  public int update(final app.daos.primitives.V2 example, final app.daos.primitives.V2 updateValues) {
    UpdateByExampleDao<app.daos.primitives.V2> fvd = //
      new UpdateByExampleDao<app.daos.primitives.V2>(example, updateValues);
    return this.sqlSession.update("mappers.v2.updateByExample", fvd);
  }

  // update by criteria

  public UpdateSetCompletePhase update(final app.daos.primitives.V2 updateValues, final V2DAO.V2View tableOrView, final Predicate predicate) {
    Map<String, Object> values = new HashMap<>();
    if (updateValues.getId() != null) values.put("id", updateValues.getId());
    if (updateValues.getName() != null) values.put("name", updateValues.getName());
    return new UpdateSetCompletePhase(tableOrView, this.liveSQLDialect, this.sqlSession,
      "mappers.v2.updateByCriteria", predicate, values);
  }


  // delete by example

  public int delete(final app.daos.primitives.V2 example) {
    return this.sqlSession.delete("mappers.v2.deleteByExample", example);
  }

  // delete by criteria

  public DeleteWherePhase delete(final V2DAO.V2View from, final Predicate predicate) {
    return new DeleteWherePhase(from, this.liveSQLDialect, this.sqlSession,
      "mappers.v2.deleteByCriteria", predicate);
  }

  // DAO ordering

  public enum V2OrderBy implements OrderBy {

    ID("public.v2", "id", true), //
    ID$DESC("public.v2", "id", false), //
    NAME("public.v2", "name", true), //
    NAME$DESC("public.v2", "name", false), //
    NAME$CASEINSENSITIVE("public.v2", "lower(name)", true), //
    NAME$CASEINSENSITIVE_STABLE_FORWARD("public.v2", "lower(name), name", true), //
    NAME$CASEINSENSITIVE_STABLE_REVERSE("public.v2", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE("public.v2", "lower(name)", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_FORWARD("public.v2", "lower(name), name", false), //
    NAME$DESC_CASEINSENSITIVE_STABLE_REVERSE("public.v2", "lower(name), name", true);

    private V2OrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database View metadata

  public static V2View newView() {
    return new V2View();
  }

  public static V2View newView(final String alias) {
    return new V2View(alias);
  }

  public static class V2View extends View {

    // Properties

    public NumberColumn id;
    public StringColumn name;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.id, this.name);
    }

    // Constructors

    V2View() {
      super(null, "PUBLIC", "V2", "View", null);
      initialize();
    }

    V2View(final String alias) {
      super(null, "PUBLIC", "V2", "View", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      this.id = new NumberColumn(this, "ID", "id", "INTEGER", 32, 0);
      this.name = new StringColumn(this, "NAME", "name", "CHARACTER VARYING", 20, 0);
    }

  }

}
