// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import app.daos.primitives.AbstractCharsVO;
import app.daos.CharsVO;

import java.lang.Override;
import java.util.ArrayList;
import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.livesql.dialects.SQLDialect;
import org.hotrod.runtime.livesql.util.CastUtil;
import org.hotrod.runtime.livesql.metadata.Column;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class CharsDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private SQLDialect sqlDialect;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // Row Parser

  public app.daos.CharsVO parseRow(Map<String, Object> m) {
    app.daos.CharsVO mo = this.applicationContext.getBean(app.daos.CharsVO.class);
    mo.setCha1((java.lang.String) m.get("cha1"));
    mo.setCha2((java.lang.String) m.get("cha2"));
    mo.setCha3((java.lang.String) m.get("cha3"));
    return mo;
  }

  // no select by PK generated, since the table does not have a PK.

  // select by unique indexes: no unique indexes found -- skipped

  // select by example

  public List<app.daos.CharsVO> selectByExample(final app.daos.primitives.AbstractCharsVO example, final CharsOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractCharsVO, CharsOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("bc.chars.selectByExample", dwo);
  }

  public Cursor<app.daos.CharsVO> selectByExampleCursor(final app.daos.primitives.AbstractCharsVO example, final CharsOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractCharsVO, CharsOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.CharsVO>(this.sqlSession.selectCursor("bc.chars.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.CharsVO> selectByCriteria(final CharsDAO.CharsTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.CharsVO>(from, this.sqlDialect, this.sqlSession,
        predicate, "bc.chars.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public app.daos.CharsVO insert(final app.daos.primitives.AbstractCharsVO vo) {
    String id = "bc.chars.insert";
    this.sqlSession.insert(id, vo);
    app.daos.CharsVO mo = new app.daos.CharsVO();
    mo.setCha1(vo.getCha1());
    mo.setCha2(vo.getCha2());
    mo.setCha3(vo.getCha3());
    return mo;
  }

  // no update by PK generated, since the table does not have a PK.

  // no delete by PK generated, since the table does not have a PK.

  // update by example

  public int updateByExample(final app.daos.primitives.AbstractCharsVO example, final app.daos.primitives.AbstractCharsVO updateValues) {
    UpdateByExampleDao<app.daos.primitives.AbstractCharsVO> fvd = //
      new UpdateByExampleDao<app.daos.primitives.AbstractCharsVO>(example, updateValues);
    return this.sqlSession.update("bc.chars.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final app.daos.primitives.AbstractCharsVO example) {
    return this.sqlSession.delete("bc.chars.deleteByExample", example);
  }

  // DAO ordering

  public enum CharsOrderBy implements OrderBy {

    CHA1("chars", "cha1", true), //
    CHA1$DESC("chars", "cha1", false), //
    CHA1$CASEINSENSITIVE("chars", "lower(cha1)", true), //
    CHA1$CASEINSENSITIVE_STABLE_FORWARD("chars", "lower(cha1), cha1", true), //
    CHA1$CASEINSENSITIVE_STABLE_REVERSE("chars", "lower(cha1), cha1", false), //
    CHA1$DESC_CASEINSENSITIVE("chars", "lower(cha1)", false), //
    CHA1$DESC_CASEINSENSITIVE_STABLE_FORWARD("chars", "lower(cha1), cha1", false), //
    CHA1$DESC_CASEINSENSITIVE_STABLE_REVERSE("chars", "lower(cha1), cha1", true), //
    CHA2("chars", "cha2", true), //
    CHA2$DESC("chars", "cha2", false), //
    CHA2$CASEINSENSITIVE("chars", "lower(cha2)", true), //
    CHA2$CASEINSENSITIVE_STABLE_FORWARD("chars", "lower(cha2), cha2", true), //
    CHA2$CASEINSENSITIVE_STABLE_REVERSE("chars", "lower(cha2), cha2", false), //
    CHA2$DESC_CASEINSENSITIVE("chars", "lower(cha2)", false), //
    CHA2$DESC_CASEINSENSITIVE_STABLE_FORWARD("chars", "lower(cha2), cha2", false), //
    CHA2$DESC_CASEINSENSITIVE_STABLE_REVERSE("chars", "lower(cha2), cha2", true), //
    CHA3("chars", "cha3", true), //
    CHA3$DESC("chars", "cha3", false), //
    CHA3$CASEINSENSITIVE("chars", "lower(cha3)", true), //
    CHA3$CASEINSENSITIVE_STABLE_FORWARD("chars", "lower(cha3), cha3", true), //
    CHA3$CASEINSENSITIVE_STABLE_REVERSE("chars", "lower(cha3), cha3", false), //
    CHA3$DESC_CASEINSENSITIVE("chars", "lower(cha3)", false), //
    CHA3$DESC_CASEINSENSITIVE_STABLE_FORWARD("chars", "lower(cha3), cha3", false), //
    CHA3$DESC_CASEINSENSITIVE_STABLE_REVERSE("chars", "lower(cha3), cha3", true);

    private CharsOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static CharsTable newTable() {
    return new CharsTable();
  }

  public static CharsTable newTable(final String alias) {
    return new CharsTable(alias);
  }

  public static class CharsTable extends Table {

    // Properties

    public StringColumn cha1;
    public StringColumn cha2;
    public StringColumn cha3;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.cha1, this.cha2, this.cha3);
    }

    // Constructors

    CharsTable() {
      super(null, null, "chars", "Table", null);
      initialize();
    }

    CharsTable(final String alias) {
      super(null, null, "chars", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      super.columns = new ArrayList<>();
      this.cha1 = new StringColumn(this, "cha1", "cha1", "bpchar", 10, 0);
      super.columns.add(this.cha1);
      this.cha2 = new StringColumn(this, "cha2", "cha2", "varchar", 10, 0);
      super.columns.add(this.cha2);
      this.cha3 = new StringColumn(this, "cha3", "cha3", "text", 2147483647, 0);
      super.columns.add(this.cha3);
    }

  }

}
