// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import app.daos.primitives.AbstractInvoiceVO;
import app.daos.InvoiceVO;

import java.lang.Override;
import java.util.Map;
import java.util.ArrayList;
import java.util.HashMap;

import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.spring.SpringBeanObjectFactory;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.util.CastUtil;
import org.hotrod.runtime.livesql.metadata.Column;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.queries.DeleteWherePhase;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class InvoiceDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  @Autowired
  private SpringBeanObjectFactory springBeanObjectFactory;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
    this.sqlSession.getConfiguration().setObjectFactory(this.springBeanObjectFactory);
  }

  // Row Parser

  public app.daos.InvoiceVO parseRow(Map<String, Object> m) {
    return parseRow(m, null, null);
  }

  public app.daos.InvoiceVO parseRow(Map<String, Object> m, String prefix) {
    return parseRow(m, prefix, null);
  }

  public app.daos.InvoiceVO parseRow(Map<String, Object> m, String prefix, String suffix) {
    app.daos.InvoiceVO mo = this.applicationContext.getBean(app.daos.InvoiceVO.class);
    String p = prefix == null ? "": prefix;
    String s = suffix == null ? "": suffix;
    mo.setId(CastUtil.toInteger((Number) m.get(p + "id" + s)));
    mo.setAmount(CastUtil.toInteger((Number) m.get(p + "amount" + s)));
    mo.setBranchId(CastUtil.toInteger((Number) m.get(p + "branchId" + s)));
    return mo;
  }

  // select by primary key

  public app.daos.InvoiceVO select(final java.lang.Integer id) {
    if (id == null)
      return null;
    app.daos.InvoiceVO vo = new app.daos.InvoiceVO();
    vo.setId(id);
    return this.sqlSession.selectOne("mappers.invoice.selectByPK", vo);
  }

  // select by unique indexes: no unique indexes found (besides the PK) -- skipped

  // select by example

  public List<app.daos.InvoiceVO> select(final app.daos.primitives.AbstractInvoiceVO example, final InvoiceOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractInvoiceVO, InvoiceOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("mappers.invoice.selectByExample", dwo);
  }

  public Cursor<app.daos.InvoiceVO> selectCursor(final app.daos.primitives.AbstractInvoiceVO example, final InvoiceOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractInvoiceVO, InvoiceOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.InvoiceVO>(this.sqlSession.selectCursor("mappers.invoice.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.InvoiceVO> select(final InvoiceDAO.InvoiceTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.InvoiceVO>(from, this.liveSQLDialect, this.sqlSession,
        predicate, "mappers.invoice.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public app.daos.InvoiceVO insert(final app.daos.primitives.AbstractInvoiceVO vo) {
    String id = "mappers.invoice.insert";
    this.sqlSession.insert(id, vo);
    app.daos.InvoiceVO mo = new app.daos.InvoiceVO();
    mo.setId(vo.getId());
    mo.setAmount(vo.getAmount());
    mo.setBranchId(vo.getBranchId());
    return mo;
  }

  // update by PK

  public int update(final app.daos.InvoiceVO vo) {
    if (vo.id == null) return 0;
    return this.sqlSession.update("mappers.invoice.updateByPK", vo);
  }

  // delete by PK

  public int delete(final java.lang.Integer id) {
    if (id == null) return 0;
    app.daos.InvoiceVO vo = new app.daos.InvoiceVO();
    vo.setId(id);
    if (vo.id == null) return 0;
    return this.sqlSession.delete("mappers.invoice.deleteByPK", vo);
  }

  // update by example

  public int update(final app.daos.primitives.AbstractInvoiceVO example, final app.daos.primitives.AbstractInvoiceVO updateValues) {
    UpdateByExampleDao<app.daos.primitives.AbstractInvoiceVO> fvd = //
      new UpdateByExampleDao<app.daos.primitives.AbstractInvoiceVO>(example, updateValues);
    return this.sqlSession.update("mappers.invoice.updateByExample", fvd);
  }

  // update by criteria

  public UpdateSetCompletePhase update(final app.daos.primitives.AbstractInvoiceVO updateValues, final InvoiceDAO.InvoiceTable tableOrView, final Predicate predicate) {
    Map<String, Object> values = new HashMap<>();
    if (updateValues.getId() != null) values.put("id", updateValues.getId());
    if (updateValues.getAmount() != null) values.put("amount", updateValues.getAmount());
    if (updateValues.getBranchId() != null) values.put("branch_id", updateValues.getBranchId());
    return new UpdateSetCompletePhase(tableOrView, this.liveSQLDialect, this.sqlSession,
      "mappers.invoice.updateByCriteria", predicate, values);
  }


  // delete by example

  public int delete(final app.daos.primitives.AbstractInvoiceVO example) {
    return this.sqlSession.delete("mappers.invoice.deleteByExample", example);
  }

  // delete by criteria

  public DeleteWherePhase delete(final InvoiceDAO.InvoiceTable from, final Predicate predicate) {
    return new DeleteWherePhase(from, this.liveSQLDialect, this.sqlSession,
      "mappers.invoice.deleteByCriteria", predicate);
  }

  // DAO ordering

  public enum InvoiceOrderBy implements OrderBy {

    ID("public.invoice", "id", true), //
    ID$DESC("public.invoice", "id", false), //
    AMOUNT("public.invoice", "amount", true), //
    AMOUNT$DESC("public.invoice", "amount", false), //
    BRANCH_ID("public.invoice", "branch_id", true), //
    BRANCH_ID$DESC("public.invoice", "branch_id", false);

    private InvoiceOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static InvoiceTable newTable() {
    return new InvoiceTable();
  }

  public static InvoiceTable newTable(final String alias) {
    return new InvoiceTable(alias);
  }

  public static class InvoiceTable extends Table {

    // Properties

    public NumberColumn id;
    public NumberColumn amount;
    public NumberColumn branchId;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.id, this.amount, this.branchId);
    }

    // Constructors

    InvoiceTable() {
      super(null, "PUBLIC", "INVOICE", "Table", null);
      initialize();
    }

    InvoiceTable(final String alias) {
      super(null, "PUBLIC", "INVOICE", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      super.columns = new ArrayList<>();
      this.id = new NumberColumn(this, "ID", "id", "INTEGER", 32, 0);
      super.columns.add(this.id);
      this.amount = new NumberColumn(this, "AMOUNT", "amount", "INTEGER", 32, 0);
      super.columns.add(this.amount);
      this.branchId = new NumberColumn(this, "BRANCH_ID", "branchId", "INTEGER", 32, 0);
      super.columns.add(this.branchId);
    }

  }

}
