// Autogenerated by HotRod -- Do not edit.

package app.daos.primitives;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.SqlSession;
import org.hotrod.runtime.cursors.Cursor;
import org.hotrod.runtime.livesql.queries.select.MyBatisCursor;

import org.hotrod.runtime.interfaces.DaoWithOrder;
import org.hotrod.runtime.interfaces.UpdateByExampleDao;
import org.hotrod.runtime.interfaces.OrderBy;

import app.daos.primitives.AbstractOthersVO;
import app.daos.OthersVO;

import java.lang.Override;
import java.util.ArrayList;
import org.hotrod.runtime.livesql.expressions.ResultSetColumn;
import org.hotrod.runtime.spring.SpringBeanObjectFactory;
import org.hotrod.runtime.livesql.dialects.SQLDialect;
import org.hotrod.runtime.livesql.util.CastUtil;
import org.hotrod.runtime.livesql.metadata.Column;
import org.hotrod.runtime.livesql.metadata.NumberColumn;
import org.hotrod.runtime.livesql.metadata.StringColumn;
import org.hotrod.runtime.livesql.metadata.DateTimeColumn;
import org.hotrod.runtime.livesql.metadata.BooleanColumn;
import org.hotrod.runtime.livesql.metadata.ByteArrayColumn;
import org.hotrod.runtime.livesql.metadata.ObjectColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.metadata.View;

import org.springframework.stereotype.Component;
import org.springframework.beans.BeansException;
import org.springframework.context.annotation.Lazy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Component
public class OthersDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  @Autowired
  private SqlSession sqlSession;

  @Autowired
  private SQLDialect sqlDialect;

  @Autowired
  private SpringBeanObjectFactory springBeanObjectFactory;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
    this.sqlSession.getConfiguration().setObjectFactory(this.springBeanObjectFactory);
  }

  // Row Parser

  public app.daos.OthersVO parseRow(Map<String, Object> m) {
    return parseRow(m, null, null);
  }

  public app.daos.OthersVO parseRow(Map<String, Object> m, String prefix) {
    return parseRow(m, prefix, null);
  }

  public app.daos.OthersVO parseRow(Map<String, Object> m, String prefix, String suffix) {
    app.daos.OthersVO mo = this.applicationContext.getBean(app.daos.OthersVO.class);
    String p = prefix == null ? "": prefix;
    String s = suffix == null ? "": suffix;
    mo.setId(CastUtil.toInteger((Number)  m.get(p + "id" + s)));
    mo.setGeo1(m.get(p + "geo1" + s));
    mo.setGeo2(m.get(p + "geo2" + s));
    mo.setGeo3(m.get(p + "geo3" + s));
    mo.setGeo4(m.get(p + "geo4" + s));
    mo.setGeo5(m.get(p + "geo5" + s));
    mo.setGeo6(m.get(p + "geo6" + s));
    mo.setGeo7(m.get(p + "geo7" + s));
    mo.setNet1(m.get(p + "net1" + s));
    mo.setNet2(m.get(p + "net2" + s));
    mo.setNet3(m.get(p + "net3" + s));
    mo.setUui1(m.get(p + "uui1" + s));
    mo.setJso1(m.get(p + "jso1" + s));
    mo.setJso2(m.get(p + "jso2" + s));
    mo.setArr1(m.get(p + "arr1" + s));
    mo.setArr2(m.get(p + "arr2" + s));
    mo.setArr3(m.get(p + "arr3" + s));
    mo.setCom1(m.get(p + "com1" + s));
    mo.setRan1(m.get(p + "ran1" + s));
    mo.setRan2(m.get(p + "ran2" + s));
    mo.setRan3(m.get(p + "ran3" + s));
    mo.setRan4(m.get(p + "ran4" + s));
    mo.setRan5(m.get(p + "ran5" + s));
    mo.setRan6(m.get(p + "ran6" + s));
    return mo;
  }

  // select by primary key

  public app.daos.OthersVO selectByPK(final java.lang.Integer id) {
    if (id == null)
      return null;
    app.daos.OthersVO vo = new app.daos.OthersVO();
    vo.setId(id);
    return this.sqlSession.selectOne("bc.others.selectByPK", vo);
  }

  // select by unique indexes: no unique indexes found (besides the PK) -- skipped

  // select by example

  public List<app.daos.OthersVO> selectByExample(final app.daos.primitives.AbstractOthersVO example, final OthersOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractOthersVO, OthersOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return this.sqlSession.selectList("bc.others.selectByExample", dwo);
  }

  public Cursor<app.daos.OthersVO> selectByExampleCursor(final app.daos.primitives.AbstractOthersVO example, final OthersOrderBy... orderBies)
      {
    DaoWithOrder<app.daos.primitives.AbstractOthersVO, OthersOrderBy> dwo = //
        new DaoWithOrder<>(example, orderBies);
    return new MyBatisCursor<app.daos.OthersVO>(this.sqlSession.selectCursor("bc.others.selectByExample", dwo));
  }

  // select by criteria

  public CriteriaWherePhase<app.daos.OthersVO> selectByCriteria(final OthersDAO.OthersTable from,
      final Predicate predicate) {
    return new CriteriaWherePhase<app.daos.OthersVO>(from, this.sqlDialect, this.sqlSession,
        predicate, "bc.others.selectByCriteria");
  }

  // select parent(s) by FKs: no imported keys found -- skipped

  // select children by FKs: no exported FKs found -- skipped

  // insert

  public app.daos.OthersVO insert(final app.daos.primitives.AbstractOthersVO vo) {
    String id = "bc.others.insert";
    this.sqlSession.insert(id, vo);
    app.daos.OthersVO mo = new app.daos.OthersVO();
    mo.setId(vo.getId());
    mo.setGeo1(vo.getGeo1());
    mo.setGeo2(vo.getGeo2());
    mo.setGeo3(vo.getGeo3());
    mo.setGeo4(vo.getGeo4());
    mo.setGeo5(vo.getGeo5());
    mo.setGeo6(vo.getGeo6());
    mo.setGeo7(vo.getGeo7());
    mo.setNet1(vo.getNet1());
    mo.setNet2(vo.getNet2());
    mo.setNet3(vo.getNet3());
    mo.setUui1(vo.getUui1());
    mo.setJso1(vo.getJso1());
    mo.setJso2(vo.getJso2());
    mo.setArr1(vo.getArr1());
    mo.setArr2(vo.getArr2());
    mo.setArr3(vo.getArr3());
    mo.setCom1(vo.getCom1());
    mo.setRan1(vo.getRan1());
    mo.setRan2(vo.getRan2());
    mo.setRan3(vo.getRan3());
    mo.setRan4(vo.getRan4());
    mo.setRan5(vo.getRan5());
    mo.setRan6(vo.getRan6());
    return mo;
  }

  // update by PK

  public int update(final app.daos.OthersVO vo) {
    if (vo.id == null) return 0;
    return this.sqlSession.update("bc.others.updateByPK", vo);
  }

  // delete by PK

  public int delete(final app.daos.OthersVO vo) {
    if (vo.id == null) return 0;
    return this.sqlSession.delete("bc.others.deleteByPK", vo);
  }

  // update by example

  public int updateByExample(final app.daos.primitives.AbstractOthersVO example, final app.daos.primitives.AbstractOthersVO updateValues) {
    UpdateByExampleDao<app.daos.primitives.AbstractOthersVO> fvd = //
      new UpdateByExampleDao<app.daos.primitives.AbstractOthersVO>(example, updateValues);
    return this.sqlSession.update("bc.others.updateByExample", fvd);
  }

  // delete by example

  public int deleteByExample(final app.daos.primitives.AbstractOthersVO example) {
    return this.sqlSession.delete("bc.others.deleteByExample", example);
  }

  // DAO ordering

  public enum OthersOrderBy implements OrderBy {

    ID("others", "id", true), //
    ID$DESC("others", "id", false), //
    GEO1("others", "geo1", true), //
    GEO1$DESC("others", "geo1", false), //
    GEO2("others", "geo2", true), //
    GEO2$DESC("others", "geo2", false), //
    GEO3("others", "geo3", true), //
    GEO3$DESC("others", "geo3", false), //
    GEO4("others", "geo4", true), //
    GEO4$DESC("others", "geo4", false), //
    GEO5("others", "geo5", true), //
    GEO5$DESC("others", "geo5", false), //
    GEO6("others", "geo6", true), //
    GEO6$DESC("others", "geo6", false), //
    GEO7("others", "geo7", true), //
    GEO7$DESC("others", "geo7", false), //
    NET1("others", "net1", true), //
    NET1$DESC("others", "net1", false), //
    NET2("others", "net2", true), //
    NET2$DESC("others", "net2", false), //
    NET3("others", "net3", true), //
    NET3$DESC("others", "net3", false), //
    UUI1("others", "uui1", true), //
    UUI1$DESC("others", "uui1", false), //
    JSO1("others", "jso1", true), //
    JSO1$DESC("others", "jso1", false), //
    JSO2("others", "jso2", true), //
    JSO2$DESC("others", "jso2", false), //
    ARR1("others", "arr1", true), //
    ARR1$DESC("others", "arr1", false), //
    ARR2("others", "arr2", true), //
    ARR2$DESC("others", "arr2", false), //
    ARR3("others", "arr3", true), //
    ARR3$DESC("others", "arr3", false), //
    COM1("others", "com1", true), //
    COM1$DESC("others", "com1", false), //
    RAN1("others", "ran1", true), //
    RAN1$DESC("others", "ran1", false), //
    RAN2("others", "ran2", true), //
    RAN2$DESC("others", "ran2", false), //
    RAN3("others", "ran3", true), //
    RAN3$DESC("others", "ran3", false), //
    RAN4("others", "ran4", true), //
    RAN4$DESC("others", "ran4", false), //
    RAN5("others", "ran5", true), //
    RAN5$DESC("others", "ran5", false), //
    RAN6("others", "ran6", true), //
    RAN6$DESC("others", "ran6", false);

    private OthersOrderBy(final String tableName, final String columnName,
        boolean ascending) {
      this.tableName = tableName;
      this.columnName = columnName;
      this.ascending = ascending;
    }

    private String tableName;
    private String columnName;
    private boolean ascending;

    public String getTableName() {
      return this.tableName;
    }

    public String getColumnName() {
      return this.columnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database Table metadata

  public static OthersTable newTable() {
    return new OthersTable();
  }

  public static OthersTable newTable(final String alias) {
    return new OthersTable(alias);
  }

  public static class OthersTable extends Table {

    // Properties

    public NumberColumn id;
    public ObjectColumn geo1;
    public ObjectColumn geo2;
    public ObjectColumn geo3;
    public ObjectColumn geo4;
    public ObjectColumn geo5;
    public ObjectColumn geo6;
    public ObjectColumn geo7;
    public ObjectColumn net1;
    public ObjectColumn net2;
    public ObjectColumn net3;
    public ObjectColumn uui1;
    public ObjectColumn jso1;
    public ObjectColumn jso2;
    public ObjectColumn arr1;
    public ObjectColumn arr2;
    public ObjectColumn arr3;
    public ObjectColumn com1;
    public ObjectColumn ran1;
    public ObjectColumn ran2;
    public ObjectColumn ran3;
    public ObjectColumn ran4;
    public ObjectColumn ran5;
    public ObjectColumn ran6;

    // Getters

    public AllColumns star() {
      return new AllColumns(this, this.id, this.geo1, this.geo2, this.geo3, this.geo4, this.geo5, this.geo6, this.geo7, this.net1, this.net2, this.net3, this.uui1, this.jso1, this.jso2, this.arr1, this.arr2, this.arr3, this.com1, this.ran1, this.ran2, this.ran3, this.ran4, this.ran5, this.ran6);
    }

    // Constructors

    OthersTable() {
      super(null, null, "others", "Table", null);
      initialize();
    }

    OthersTable(final String alias) {
      super(null, null, "others", "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      super.columns = new ArrayList<>();
      this.id = new NumberColumn(this, "id", "id", "int4", 10, 0);
      super.columns.add(this.id);
      this.geo1 = new ObjectColumn(this, "geo1", "geo1", "point", 2147483647, 0);
      super.columns.add(this.geo1);
      this.geo2 = new ObjectColumn(this, "geo2", "geo2", "line", 2147483647, 0);
      super.columns.add(this.geo2);
      this.geo3 = new ObjectColumn(this, "geo3", "geo3", "lseg", 2147483647, 0);
      super.columns.add(this.geo3);
      this.geo4 = new ObjectColumn(this, "geo4", "geo4", "box", 2147483647, 0);
      super.columns.add(this.geo4);
      this.geo5 = new ObjectColumn(this, "geo5", "geo5", "path", 2147483647, 0);
      super.columns.add(this.geo5);
      this.geo6 = new ObjectColumn(this, "geo6", "geo6", "polygon", 2147483647, 0);
      super.columns.add(this.geo6);
      this.geo7 = new ObjectColumn(this, "geo7", "geo7", "circle", 2147483647, 0);
      super.columns.add(this.geo7);
      this.net1 = new ObjectColumn(this, "net1", "net1", "cidr", 2147483647, 0);
      super.columns.add(this.net1);
      this.net2 = new ObjectColumn(this, "net2", "net2", "inet", 2147483647, 0);
      super.columns.add(this.net2);
      this.net3 = new ObjectColumn(this, "net3", "net3", "macaddr", 2147483647, 0);
      super.columns.add(this.net3);
      this.uui1 = new ObjectColumn(this, "uui1", "uui1", "uuid", 2147483647, 0);
      super.columns.add(this.uui1);
      this.jso1 = new ObjectColumn(this, "jso1", "jso1", "json", 2147483647, 0);
      super.columns.add(this.jso1);
      this.jso2 = new ObjectColumn(this, "jso2", "jso2", "jsonb", 2147483647, 0);
      super.columns.add(this.jso2);
      this.arr1 = new ObjectColumn(this, "arr1", "arr1", "_int4", 10, 0);
      super.columns.add(this.arr1);
      this.arr2 = new ObjectColumn(this, "arr2", "arr2", "_bpchar", 1, 0);
      super.columns.add(this.arr2);
      this.arr3 = new ObjectColumn(this, "arr3", "arr3", "_int4", 10, 0);
      super.columns.add(this.arr3);
      this.com1 = new ObjectColumn(this, "com1", "com1", "complex", 2147483647, 0);
      super.columns.add(this.com1);
      this.ran1 = new ObjectColumn(this, "ran1", "ran1", "int4range", 2147483647, 0);
      super.columns.add(this.ran1);
      this.ran2 = new ObjectColumn(this, "ran2", "ran2", "int8range", 2147483647, 0);
      super.columns.add(this.ran2);
      this.ran3 = new ObjectColumn(this, "ran3", "ran3", "numrange", 2147483647, 0);
      super.columns.add(this.ran3);
      this.ran4 = new ObjectColumn(this, "ran4", "ran4", "tsrange", 2147483647, 0);
      super.columns.add(this.ran4);
      this.ran5 = new ObjectColumn(this, "ran5", "ran5", "tstzrange", 2147483647, 0);
      super.columns.add(this.ran5);
      this.ran6 = new ObjectColumn(this, "ran6", "ran6", "daterange", 2147483647, 0);
      super.columns.add(this.ran6);
    }

  }

}
