package tests;

import java.io.IOException;
import java.sql.SQLException;

import hotrod.test.generation.TestIdentityDAO;
import hotrod.test.generation.TestSequenceDAO;

public class AutogeneratedPKTests {

  public static void main(final String[] args) throws IOException, SQLException {
    testTypes();
  }

  private static void testTypes() throws SQLException {
    // identityPKTest();
    sequencePKTest();
  }

  private static void identityPKTest() throws SQLException {
    TestIdentityDAO.deleteByExample(new TestIdentityDAO());

    TestIdentityDAO n = new TestIdentityDAO();
    n.setId(1000);
    n.setName("Toyota");
    n.insert();

    System.out.println("id=" + n.getId());
  }

  private static void sequencePKTest() throws SQLException {
    TestSequenceDAO.deleteByExample(new TestSequenceDAO());

    TestSequenceDAO n = new TestSequenceDAO();
    n.setId(1000);
    n.setName("Aston Martin");
    int rows = n.insert();

    System.out.println("inserted rows=" + rows);
    System.out.println("id=" + n.getId());
    System.out.println("row: " + n);
  }

}
