// Autogenerated by HotRod -- Do not edit.

package app.persistence2.dao;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.hotrod.dynamicsql.DynamicExpressionException;
import org.hotrod.dynamicsql.DynamicInsertQuery;
import org.hotrod.dynamicsql.DynamicModificationQuery;
import org.hotrod.dynamicsql.DynamicSelectQuery;
import org.hotrod.dynamicsql.Parameters;
import org.hotrod.dynamicsql.PreparedModificationQuery;
import org.hotrod.dynamicsql.PreparedQuery;
import org.hotrod.dynamicsql.PreparedSelectQuery;
import org.hotrod.dynamicsql.RowReader;
import org.hotrod.dynamicsql.assembler.DynamicSQL;
import org.hotrod.dynamicsql.insert.PreparedInsertQuery;
import org.hotrod.dynamicsql.insert.PrimaryKeyRetrievalMode;
import org.hotrod.interfaces.OrderBy;
import org.hotrod.livesql.DynamicSQLBean;
import org.hotrod.livesql.LiveSQL;
import org.hotrod.livesql.dialects.LiveSQLDialect;
import org.hotrod.livesql.expressions.predicates.GeneralBooleanExpression;
import org.hotrod.livesql.metadata.AllColumns;
import org.hotrod.livesql.metadata.Name;
import org.hotrod.livesql.metadata.NumberEntityColumn;
import org.hotrod.livesql.metadata.StringEntityColumn;
import org.hotrod.livesql.metadata.Table;
import org.hotrod.livesql.queries.DeleteWherePhase;
import org.hotrod.livesql.queries.LiveSQLContext;
import org.hotrod.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.livesql.queries.UpdateSetCompletePhase.Setter;
import org.hotrod.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.livesql.queries.typesolver.TypeHandler;
import org.hotrod.livesql.queries.typesolver.TypeSolver;
import org.hotrod.livesql.queries.typesolver.TypeSource;
import org.hotrod.utils.SQLUtil;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

import app.persistence2.model.Invoice;

@Component
public class InvoiceDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  private static final Logger log = Logger.getLogger(InvoiceDAO.class.getName());

  @Autowired
  @Qualifier("liveSQLDialect2")
  private LiveSQLDialect liveSQLDialect;

  @Autowired
  private DynamicSQLBean dynamicSQLBean;

  private DynamicSQL dyn;

  @Autowired
  @Qualifier("dataSource2")
  private DataSource dataSource;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  @Autowired
  @Qualifier("liveSQL2")
  private LiveSQL sql;

  private LiveSQLContext context;

  // ROW READER

  private final RowReader<Invoice> rowReader = new RowReader<Invoice>() {

    @Override
    public Invoice readRowFrom(ResultSet rs, Connection conn) throws SQLException {
      Invoice row = applicationContext.getBean(Invoice.class);

      Integer col1 = rs.getInt("ID"); // ID
      if (rs.wasNull())
        col1 = null;
      row.setId(col1);

      String col2 = rs.getString("CLIENT"); // CLIENT
      row.setClient(col2);

      Integer col3 = rs.getInt("AMOUNT"); // AMOUNT
      if (rs.wasNull())
        col3 = null;
      row.setAmount(col3);

      return row;
    }

  };

  // BASELINE

  public class InvoiceBaseline {

    private Integer id;
    private String client;
    private Integer amount;

    public Integer getId() {
      return this.id;
    }

    public String getClient() {
      return this.client;
    }

    public Integer getAmount() {
      return this.amount;
    }

  }

  public InvoiceBaseline baseline(Invoice model) {
    InvoiceBaseline b = new InvoiceBaseline();
    b.id = model.getId();
    b.client = model.getClient();
    b.amount = model.getAmount();
    return b;
  };

  // SELECT BY PRIMARY KEY

  private DynamicSelectQuery selectByPrimaryKey;

  private void initializeSelectbyprimarykey() {
    this.selectByPrimaryKey = dyn.literaln("SELECT").literaln("  id,").literaln("  client,").literaln("  amount")
        .literaln("FROM invoice").literaln("WHERE " + "id = ").parameter("f.id").endSelectQuery();
  }

  public Invoice select(Integer id) throws DynamicExpressionException, SQLException {
    if (id == null)
      return null;
    Invoice filter = new Invoice();
    filter.setId(id);
    Parameters context = this.dyn.newParameters();
    context.add("f", filter);
    PreparedSelectQuery<Invoice> preparedQuery = this.selectByPrimaryKey.prepare(context, this.rowReader);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<Invoice> rows = preparedQuery.execute(conn);
      if (rows.size() == 0)
        return null;
      if (rows.size() == 1)
        return rows.get(0);
      throw new RuntimeException("A single row at most was expected but received " + rows.size() + " rows.");
    }
  }

  // SELECT BY EXAMPLE

  private DynamicSelectQuery selectByExample;

  private void initializeSelectbyexample() {
    this.selectByExample = dyn.literaln("SELECT").literaln("  id,").literaln("  client,").literaln("  amount")
        .literaln("FROM invoice").where("AND").if_("f.id != null").literal("id = ").parameter("f.id").endif()
        .if_("f.client != null").literal("client = ").parameter("f.client").endif().if_("f.amount != null")
        .literal("amount = ").parameter("f.amount").endif().endwhere().parameterInjection("ordering").endSelectQuery();
  }

  public List<Invoice> select(Invoice filter, InvoiceOrderBy... orderBies)
      throws DynamicExpressionException, SQLException {
    Parameters context = this.dyn.newParameters();
    context.add("f", filter);
    String ordering = SQLUtil.render(orderBies);
    context.add("ordering", ordering);
    PreparedSelectQuery<Invoice> preparedQuery = this.selectByExample.prepare(context, this.rowReader);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<Invoice> rows = preparedQuery.execute(conn);
      return rows;
    }
  }

  // SELECT BY CRITERIA

  public CriteriaWherePhase<Invoice> select(final InvoiceTable from, final GeneralBooleanExpression predicate) {
    return new CriteriaWherePhase<Invoice>(this.context, from, predicate, this.rowReader);
  }

  // INSERT

  private DynamicInsertQuery insert;

  private void initializeInsert() {
    this.insert = dyn.literaln("INSERT INTO invoice (").literaln("  id,").literaln("  client,").literaln("  amount")
        .literaln(")").literaln("VALUES(").literal("  ").parameterNullable("m.id", Types.INTEGER).literaln(",")
        .literal("  ").parameterNullable("m.client", Types.VARCHAR).literaln(",").literal("  ")
        .parameterNullable("m.amount", Types.INTEGER).literal(")").endInsertQuery(PrimaryKeyRetrievalMode.NO_RETRIEVAL);
  }

  public void insert(Invoice model) throws DynamicExpressionException, SQLException {
    Parameters context = this.dyn.newParameters();
    context.add("m", model);
    PreparedInsertQuery preparedQuery = this.insert.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      preparedQuery.execute(conn);
    }
  }

  // INSERT BY EXAMPLE

  private DynamicInsertQuery insertByExample;

  private void initializeInsertbyexample() {
    this.insertByExample = dyn.literaln("INSERT INTO invoice (").if_("m.id != null").literal("id,\n").endif()
        .if_("m.client != null").literal("client,\n").endif().if_("m.amount != null").literal("amount\n").endif()
        .literaln(")").literaln("VALUES(").if_("m.id != null").parameter("m.id").literal(", ").endif()
        .if_("m.client != null").parameter("m.client").literal(", ").endif().if_("m.amount != null")
        .parameter("m.amount").endif().literal(")").endInsertQuery(PrimaryKeyRetrievalMode.NO_RETRIEVAL);
  }

  public void insertByExample(Invoice model) throws DynamicExpressionException, SQLException {
    Parameters context = this.dyn.newParameters();
    context.add("m", model);
    PreparedInsertQuery preparedQuery = this.insertByExample.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      preparedQuery.execute(conn);
    }
  }

  // UPDATE BY PRIMARY KEY

  private DynamicModificationQuery updateByPK;

  private void initializeUpdatebypk() {
    this.updateByPK = dyn.literaln("UPDATE invoice").literaln("SET").literal("  id = ")
        .parameterNullable("m.id", Types.INTEGER).literaln(",").literal("  client = ")
        .parameterNullable("m.client", Types.VARCHAR).literaln(",").literal("  amount = ")
        .parameterNullable("m.amount", Types.INTEGER).literaln("WHERE " + "id = ").parameter("m.id")
        .endModificationQuery();
  }

  public int update(Invoice model) throws DynamicExpressionException, SQLException {
    if (model.getId() == null)
      return 0;
    Parameters context = this.dyn.newParameters();
    context.add("m", model);
    PreparedModificationQuery preparedQuery = this.updateByPK.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // UPDATE BY EXAMPLE

  private DynamicModificationQuery updateByExample;

  private void initializeUpdatebyexample() {
    this.updateByExample = dyn.literal("UPDATE invoice").set().if_("v.id != null").literal("id = ").parameter("v.id")
        .endif().if_("v.client != null").literal("client = ").parameter("v.client").endif().if_("v.amount != null")
        .literal("amount = ").parameter("v.amount").endif().endset().where("AND").if_("e.id != null").literal("id = ")
        .parameter("e.id").endif().if_("e.client != null").literal("client = ").parameter("e.client").endif()
        .if_("e.amount != null").literal("amount = ").parameter("e.amount").endif().endwhere().endModificationQuery();
  }

  public int update(Invoice example, Invoice values) throws DynamicExpressionException, SQLException {
    Parameters context = this.dyn.newParameters();
    context.add("e", example);
    context.add("v", values);
    PreparedModificationQuery preparedQuery = this.updateByExample.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // UPDATE BY CRITERIA

  public UpdateSetCompletePhase update(final Invoice values, final InvoiceTable tableOrView,
      final GeneralBooleanExpression predicate) {
    List<Setter> setters = new ArrayList<>();
    if (values.getId() != null)
      setters.add(new Setter(tableOrView.id, sql.val(values.getId())));
    if (values.getClient() != null)
      setters.add(new Setter(tableOrView.client, sql.val(values.getClient())));
    if (values.getAmount() != null)
      setters.add(new Setter(tableOrView.amount, sql.val(values.getAmount())));
    return new UpdateSetCompletePhase(this.context, tableOrView, setters, predicate);
  }

  // DELETE BY PRIMARY KEY

  private DynamicModificationQuery deleteByPK;

  private void initializeDeletebypk() {
    this.deleteByPK = dyn.literaln("DELETE FROM invoice").literaln("WHERE " + "id = ").parameter("f.id")
        .endModificationQuery();
  }

  public int delete(Integer id) throws DynamicExpressionException, SQLException {
    if (id == null)
      return 0;
    Invoice filter = new Invoice();
    filter.setId(id);
    Parameters context = this.dyn.newParameters();
    context.add("f", filter);
    PreparedModificationQuery preparedQuery = this.deleteByPK.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // DELETE BY EXAMPLE

  private DynamicModificationQuery deleteByExample;

  private void initializeDeletebyexample() {
    this.deleteByExample = dyn.literal("DELETE FROM invoice").where("AND").if_("e.id != null").literal("id = ")
        .parameter("e.id").endif().if_("e.client != null").literal("client = ").parameter("e.client").endif()
        .if_("e.amount != null").literal("amount = ").parameter("e.amount").endif().endwhere().endModificationQuery();
  }

  public int delete(Invoice example) throws DynamicExpressionException, SQLException {
    Parameters context = this.dyn.newParameters();
    context.add("e", example);
    PreparedModificationQuery preparedQuery = this.deleteByExample.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // DELETE BY CRITERIA

  public DeleteWherePhase delete(final InvoiceTable from, final GeneralBooleanExpression predicate) {
    return new DeleteWherePhase(this.context, from, predicate);
  }

  // ORDER BY

  public enum InvoiceOrderBy implements OrderBy {

    ID("id", true), ID$DESC("id", false), CLIENT("client", true), CLIENT$DESC("client", false), AMOUNT("amount", true),
    AMOUNT$DESC("amount", false);

    private String sqlColumnName;
    private boolean ascending;

    private InvoiceOrderBy(String sqlColumnName, boolean ascending) {
      this.sqlColumnName = sqlColumnName;
      this.ascending = ascending;
    }

    public String getSQLColumnName() {
      return this.sqlColumnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database class org.hotrod.livesql.metadata.Table metadata

  public InvoiceTable newTable() {
    return new InvoiceTable();
  }

  public InvoiceTable newTable(final String alias) {
    return new InvoiceTable(alias);
  }

  public static class InvoiceTable extends Table {

    // Properties

    public final NumberEntityColumn id = new NumberEntityColumn(this, "ID", "id", "INTEGER", 32, 0,
        TypeHandler.forClass(Integer.class, TypeSource.ENTITY_COLUMN));
    public final StringEntityColumn client = new StringEntityColumn(this, "CLIENT", "client", "CHARACTER VARYING", 50,
        0, TypeHandler.forClass(String.class, TypeSource.ENTITY_COLUMN));
    public final NumberEntityColumn amount = new NumberEntityColumn(this, "AMOUNT", "amount", "INTEGER", 32, 0,
        TypeHandler.forClass(Integer.class, TypeSource.ENTITY_COLUMN));

    // Getters

    public AllColumns star() {
      return new AllColumns(this.id, this.client, this.amount);
    }

    // Constructors

    InvoiceTable() {
      super(null, null, Name.of("INVOICE", false), "Table", null);
      initialize();
    }

    InvoiceTable(final String alias) {
      super(null, null, Name.of("INVOICE", false), "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      super.columns = new ArrayList<>();
      super.columns.add(this.id);
      super.columns.add(this.client);
      super.columns.add(this.amount);
    }

  }

  @PostConstruct
  public void initializeContext() {
    this.context = new LiveSQLContext(this.liveSQLDialect, this.dataSource, new TypeSolver(null, this.liveSQLDialect),
        log);
    this.dyn = this.dynamicSQLBean.getDynamicSQL();
    this.initializeSelectbyprimarykey();
    this.initializeSelectbyexample();
    this.initializeInsert();
    this.initializeInsertbyexample();
    this.initializeUpdatebypk();
    this.initializeUpdatebyexample();
    this.initializeDeletebypk();
    this.initializeDeletebyexample();
  }

  private void logQuery(PreparedQuery preparedQuery) {
    if (log.isLoggable(Level.FINER)) {
      log.finest("SQL:\n" + preparedQuery.getPreview(true));
    } else if (log.isLoggable(Level.FINE)) {
      log.fine("SQL:\n" + preparedQuery.getPreview());
    }
  }

}
