package org.hotrod.runtime.livesql.queries.typesolver;

//LIVESQL_DESIGNATED
//LIVESQL_LAYER_RULE:5
//LIVESQL_DIALECT_DEFAULT
//JDBC_DRIVER_DEFAULT

//ENTITY_DESIGNATED
//ENTITY_LAYER_RULE:5
//ENTITY_DIALECT_DEFAULT

public enum TypeSource {
  DESIGNATED_IN_LIVESQL, LIVESQL_RULES, LAYER_RULES, DIALECT_RULES, ENTITY_COLUMN, JDBC_DRIVER
};
