package examples;

import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;

import daos.BranchVO;
import daos.ClientVO;
import daos.DailyReportVO;
import daos.VehicleVO;
import daos.VisitVO;
import daos.primitives.BranchDAO;
import daos.primitives.ClientDAO;
import daos.primitives.DailyReportDAO;
import daos.primitives.VehicleDAO;
import daos.primitives.VisitDAO;

/**
 * Example 02 - Insert Using Sequences and Identity PKs
 * 
 * @author Vladimir Alarcon
 * 
 */
public class Example02 {

  public static void main(String[] args) throws SQLException {

    System.out.println("=== Running Example 02 - Insert Using Sequences and Identity PKs ===");

    int rows;

    // 1. Insert into a table with no PK

    VisitVO vi = new VisitVO();
    vi.setRecordedAt(Timestamp.valueOf("2017-03-01 11:30:00"));
    vi.setBranchId(105);
    vi.setNotes("This is a note of the visit");
    rows = VisitDAO.insert(vi);
    System.out.println(" ");
    System.out.println("1. Visit inserted (table with no PK). Rows inserted=" + rows);

    // 2. Insert into table with PK, but no auto-generation

    DailyReportVO r = new DailyReportVO();
    r.setBranchId(104); // PK column 1
    r.setReportDate(Date.valueOf("2017-02-28")); // PK column 2
    r.setTotalSold(524850L);
    DailyReportDAO.insert(r);
    System.out.println(" ");
    System.out.println("2. Daily Report inserted (table with PK, but no auto-generation). Rows inserted=" + rows);

    // 3. Insert into a table with identity-generated PK

    VehicleVO v = new VehicleVO();
    v.setId(123); // ignored: the DB will generate the PK
    v.setBrand("Skoda");
    v.setModel("Octavia");
    v.setType("CAR");
    v.setVin("VN4408");
    v.setEngineNumber("EN9401");
    v.setMileage(12100);
    v.setPurchasedOn(Date.valueOf("2017-02-17"));
    v.setBranchId(102);
    v.setListPrice(22400);
    v.setSold(false);
    rows = VehicleDAO.insert(v);
    System.out.println(" ");
    System.out.println("3. Vehicle inserted (identity PK). ID=" + v.getId() + ". Rows inserted=" + rows);

    // 4. Insert into a table with sequence-generated PK

    ClientVO c = new ClientVO();
    c.setId(123); // ignored: the PK value will be generated by the sequence
    c.setCreatedAt(Timestamp.valueOf("2017-02-22 18:15:21"));
    c.setName("Lee Van Cliff");
    c.setState("NM");
    c.setDriversLicense("TB1583-4530-KV");
    c.setReferredById(null);
    c.setTotalPurchased(0L);
    c.setVip(false);
    rows = ClientDAO.insert(c);
    System.out.println(" ");
    System.out.println("4. Client inserted (using sequence). ID=" + c.getId() + ". Rows inserted=" + rows);

    // 5.a) Insert using into a table with optional identity PK (not specified)

    BranchVO b = new BranchVO();
    b.setId(null); // null: the DB will generate the PK
    b.setName("Wichita");
    b.setCurrentCash(0);
    rows = BranchDAO.insert(b);
    System.out.println(" ");
    System.out.println("5.a) Branch inserted (identity PK not specified). ID=" + b.getId() + ". Rows inserted=" + rows);

    // 5.b) Insert using into a table with optional identity PK (specified)

    b = new BranchVO();
    b.setId(144); // specified value: this value will be used for the PK
    b.setName("Cincinnati");
    b.setCurrentCash(0);
    rows = BranchDAO.insert(b);
    System.out.println(" ");
    System.out.println("5.b) Branch inserted (identity PK specified). ID=" + b.getId() + ". Rows inserted=" + rows);

    System.out.println(" ");
    System.out.println("=== Example 02 Complete ===");

  }

}
