// Autogenerated by HotRod -- Do not edit.

package app.persistence.dao;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.hotrod.dynamicsql.DynamicExpressionException;
import org.hotrod.dynamicsql.DynamicInsertQuery;
import org.hotrod.dynamicsql.DynamicModificationQuery;
import org.hotrod.dynamicsql.DynamicSelectQuery;
import org.hotrod.dynamicsql.ParameterContext;
import org.hotrod.dynamicsql.PreparedModificationQuery;
import org.hotrod.dynamicsql.PreparedQuery;
import org.hotrod.dynamicsql.PreparedSelectQuery;
import org.hotrod.dynamicsql.RowReader;
import org.hotrod.dynamicsql.assembler.QueryAssembler;
import org.hotrod.dynamicsql.insert.PreparedInsertQuery;
import org.hotrod.dynamicsql.insert.PrimaryKeyRetrievalMode;
import org.hotrod.interfaces.OrderBy;
import org.hotrod.runtime.livesql.LiveSQL;
import org.hotrod.runtime.livesql.dialects.LiveSQLDialect;
import org.hotrod.runtime.livesql.expressions.predicates.GeneralBooleanExpression;
import org.hotrod.runtime.livesql.metadata.AllColumns;
import org.hotrod.runtime.livesql.metadata.Name;
import org.hotrod.runtime.livesql.metadata.NumberEntityColumn;
import org.hotrod.runtime.livesql.metadata.StringEntityColumn;
import org.hotrod.runtime.livesql.metadata.Table;
import org.hotrod.runtime.livesql.queries.DeleteWherePhase;
import org.hotrod.runtime.livesql.queries.LiveSQLContext;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase;
import org.hotrod.runtime.livesql.queries.UpdateSetCompletePhase.Setter;
import org.hotrod.runtime.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.runtime.livesql.queries.typesolver.TypeHandler;
import org.hotrod.runtime.livesql.queries.typesolver.TypeHandler.TypeSource;
import org.hotrod.runtime.livesql.queries.typesolver.TypeSolver;
import org.hotrod.runtime.livesql.util.QueryAssemblerBean;
import org.hotrod.utils.SQLUtil;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

import app.persistence.model.Account;

@Component
public class AccountDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  private static final Logger log = Logger.getLogger(AccountDAO.class.getName());

  @Autowired
  private LiveSQLDialect liveSQLDialect;

  @Autowired
  private QueryAssemblerBean assemblerBean;

  private QueryAssembler assembler;

  @Autowired
  private DataSource dataSource;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  @Autowired
  private LiveSQL sql;

  private LiveSQLContext context;

  // ROW READER

  private final RowReader<Account> rowReader = new RowReader<Account>() {

    @Override
    public Account readRowFrom(ResultSet rs, Connection conn) throws SQLException {
      Account row = applicationContext.getBean(Account.class);

      Integer col1 = rs.getInt(1); // id
      if (rs.wasNull()) col1 = null;
      row.setId(col1);

      String col2 = rs.getString(2); // name
      row.setName(col2);

      String col3 = rs.getString(3); // type
      row.setType(col3);

      Integer col4 = rs.getInt(4); // balance
      if (rs.wasNull()) col4 = null;
      row.setBalance(col4);

      return row;
    }

  };

  // BASELINE

  public class AccountBaseline {

    private Integer id;
    private String name;
    private String type;
    private Integer balance;

    public Integer getId() {
      return this.id;
    }

    public String getName() {
      return this.name;
    }

    public String getType() {
      return this.type;
    }

    public Integer getBalance() {
      return this.balance;
    }

  }

  public AccountBaseline baseline(Account model) {
    AccountBaseline b = new AccountBaseline();
    b.id = model.getId();
    b.name = model.getName();
    b.type = model.getType();
    b.balance = model.getBalance();
    return b;
  };

  // SELECT BY PRIMARY KEY

  private DynamicSelectQuery selectByPrimaryKey;

  private void initializeSelectbyprimarykey() {
    this.selectByPrimaryKey = assembler
      .literaln("SELECT")
      .literaln("  id,")
      .literaln("  name,")
      .literaln("  type,")
      .literaln("  balance")
      .literaln("FROM account")
      .literaln("\nWHERE " + "id = ").parameter("f.id", Types.INTEGER)
      .endSelectQuery();
  }

  public Account select(Integer id) throws DynamicExpressionException, SQLException {
    if (id == null) return null;
    Account filter = new Account();
    filter.setId(id);
    ParameterContext context = this.assembler.newParameterContext();
    context.add("f", filter);
    PreparedSelectQuery<Account> preparedQuery = this.selectByPrimaryKey.prepare(context, Account.class);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<Account> rows = preparedQuery.execute(conn, this.rowReader);
      if (rows.size() == 0) return null;
      if (rows.size() == 1) return rows.get(0);
      throw new RuntimeException("A single row at most was expected but received " + rows.size() + " rows.");
    }
  }

  // SELECT BY EXAMPLE

  private DynamicSelectQuery selectByExample;

  private void initializeSelectbyexample() {
    this.selectByExample = assembler
      .literaln("SELECT")
      .literaln("  id,")
      .literaln("  name,")
      .literaln("  type,")
      .literaln("  balance")
      .literaln("FROM account")
      .where("AND", assembler.ifs()
        .if_("f.id != null", assembler.literal("id = ").parameter("f.id", Types.INTEGER).end())
        .if_("f.name != null", assembler.literal("name = ").parameter("f.name", Types.VARCHAR).end())
        .if_("f.type != null", assembler.literal("type = ").parameter("f.type", Types.VARCHAR).end())
        .if_("f.balance != null", assembler.literal("balance = ").parameter("f.balance", Types.INTEGER).end())
        .end())
      .parameterInjection("ordering")
      .endSelectQuery();
  }

  public List<Account> select(Account filter, AccountOrderBy... orderBies) throws DynamicExpressionException, SQLException {
    ParameterContext context = this.assembler.newParameterContext();
    context.add("f", filter);
    String ordering = SQLUtil.render(orderBies);
    context.add("ordering", ordering);
    PreparedSelectQuery<Account> preparedQuery = this.selectByExample.prepare(context, Account.class);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<Account> rows = preparedQuery.execute(conn, this.rowReader);
      return rows;
    }
  }

  // SELECT BY CRITERIA

  public CriteriaWherePhase<Account> select(final AccountTable from, final GeneralBooleanExpression predicate) {
    return new CriteriaWherePhase<Account>(this.context, from, predicate, this.rowReader);
  }

  // INSERT

  private DynamicInsertQuery insert;

  private void initializeInsert() {
    this.insert = assembler
      .literaln("INSERT INTO account (")
      .literaln("  id,")
      .literaln("  name,")
      .literaln("  type,")
      .literaln("  balance")
      .literaln(")")
      .literaln("VALUES(")
      .literal("  NEXTVAL('seq_account')").literaln(",")
      .literal("  ").parameter("m.name", Types.VARCHAR).literaln(",")
      .literal("  ").parameter("m.type", Types.VARCHAR).literaln(",")
      .literal("  ").parameter("m.balance", Types.INTEGER)
      .literal(")")
      .endInsertQuery(PrimaryKeyRetrievalMode.SEQUENCE_INLINE_KEYS_RESULTSET);
  }

  public void insert(Account model) throws DynamicExpressionException, SQLException {
    ParameterContext context = this.assembler.newParameterContext();
    context.add("m", model);
    PreparedInsertQuery preparedQuery = this.insert.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      Long pk = preparedQuery.execute(conn);
      model.setId((pk == null) ? null : Integer.valueOf(pk.intValue()));
    }
  }

  // INSERT BY EXAMPLE

  private DynamicInsertQuery insertByExample;

  private void initializeInsertbyexample() {
    this.insertByExample = assembler
      .literaln("INSERT INTO account (")
      .if_("m.id != null", assembler.literal("id,\n").end())
      .if_("m.name != null", assembler.literal("name,\n").end())
      .if_("m.type != null", assembler.literal("type,\n").end())
      .if_("m.balance != null", assembler.literal("balance\n").end())
      .literaln(")")
      .literaln("VALUES(")
      .if_("m.id != null", assembler.parameter("m.id", Types.INTEGER).literal(", ").end())
      .if_("m.name != null", assembler.parameter("m.name", Types.VARCHAR).literal(", ").end())
      .if_("m.type != null", assembler.parameter("m.type", Types.VARCHAR).literal(", ").end())
      .if_("m.balance != null", assembler.parameter("m.balance", Types.INTEGER).end())
      .literal(")")
      .endInsertQuery(PrimaryKeyRetrievalMode.SEQUENCE_INLINE_KEYS_RESULTSET);
  }

  public void insertByExample(Account model) throws DynamicExpressionException, SQLException {
    ParameterContext context = this.assembler.newParameterContext();
    context.add("m", model);
    PreparedInsertQuery preparedQuery = this.insertByExample.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      Long pk = preparedQuery.execute(conn);
      model.setId((pk == null) ? null : Integer.valueOf(pk.intValue()));
    }
  }

  // UPDATE BY PRIMARY KEY

  private DynamicModificationQuery updateByPK;

  private void initializeUpdatebypk() {
    this.updateByPK = assembler
      .literaln("UPDATE account")
      .literaln("SET")
      .literal("  id = ").parameter("m.id", Types.INTEGER).literaln(",")
      .literal("  name = ").parameter("m.name", Types.VARCHAR).literaln(",")
      .literal("  type = ").parameter("m.type", Types.VARCHAR).literaln(",")
      .literal("  balance = ").parameter("m.balance", Types.INTEGER)
      .literaln("\nWHERE " + "id = ").parameter("m.id", Types.INTEGER)
    .endModificationQuery();
  }

  public int update(Account model) throws DynamicExpressionException, SQLException {
    if (model.getId() == null) return 0;
    ParameterContext context = this.assembler.newParameterContext();
    context.add("m", model);
    PreparedModificationQuery preparedQuery = this.updateByPK.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // UPDATE BY EXAMPLE

  private DynamicModificationQuery updateByExample;

  private void initializeUpdatebyexample() {
    this.updateByExample = assembler
      .literal("UPDATE account")
      .set(assembler.ifs()
        .if_("v.id != null", assembler.literal("id = ").parameter("v.id", Types.INTEGER).end())
        .if_("v.name != null", assembler.literal("name = ").parameter("v.name", Types.VARCHAR).end())
        .if_("v.type != null", assembler.literal("type = ").parameter("v.type", Types.VARCHAR).end())
        .if_("v.balance != null", assembler.literal("balance = ").parameter("v.balance", Types.INTEGER).end())
        .end())
      .where("AND", assembler.ifs()
        .if_("e.id != null", assembler.literal("id = ").parameter("e.id", Types.INTEGER).end())
        .if_("e.name != null", assembler.literal("name = ").parameter("e.name", Types.VARCHAR).end())
        .if_("e.type != null", assembler.literal("type = ").parameter("e.type", Types.VARCHAR).end())
        .if_("e.balance != null", assembler.literal("balance = ").parameter("e.balance", Types.INTEGER).end())
        .end())
      .endModificationQuery();
  }

  public int update(Account example, Account values) throws DynamicExpressionException, SQLException {
    ParameterContext context = this.assembler.newParameterContext();
    context.add("e", example);
    context.add("v", values);
    PreparedModificationQuery preparedQuery = this.updateByExample.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // UPDATE BY CRITERIA

  public UpdateSetCompletePhase update(final Account values, final AccountTable tableOrView,
      final GeneralBooleanExpression predicate) {
    List<Setter> setters = new ArrayList<>();
    if (values.getId() != null) setters.add(new Setter(tableOrView.id, sql.val(values.getId())));
    if (values.getName() != null) setters.add(new Setter(tableOrView.name, sql.val(values.getName())));
    if (values.getType() != null) setters.add(new Setter(tableOrView.type, sql.val(values.getType())));
    if (values.getBalance() != null) setters.add(new Setter(tableOrView.balance, sql.val(values.getBalance())));
    return new UpdateSetCompletePhase(this.context, tableOrView, setters, predicate);
  }

  // DELETE BY PRIMARY KEY

  private DynamicModificationQuery deleteByPK;

  private void initializeDeletebypk() {
    this.deleteByPK = assembler
      .literaln("DELETE FROM account")
      .literaln("\nWHERE " + "id = ").parameter("f.id", Types.INTEGER)
      .endModificationQuery();
  }

  public int delete(Integer id) throws DynamicExpressionException, SQLException {
    if (id == null) return 0;
    Account filter = new Account();
    filter.setId(id);
    ParameterContext context = this.assembler.newParameterContext();
    context.add("f", filter);
    PreparedModificationQuery preparedQuery = this.deleteByPK.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // DELETE BY EXAMPLE

  private DynamicModificationQuery deleteByExample;

  private void initializeDeletebyexample() {
    this.deleteByExample = assembler
      .literal("DELETE FROM account")
      .where("AND", assembler.ifs()
        .if_("e.id != null", assembler.literal("id = ").parameter("e.id", Types.INTEGER).end())
        .if_("e.name != null", assembler.literal("name = ").parameter("e.name", Types.VARCHAR).end())
        .if_("e.type != null", assembler.literal("type = ").parameter("e.type", Types.VARCHAR).end())
        .if_("e.balance != null", assembler.literal("balance = ").parameter("e.balance", Types.INTEGER).end())
        .end())
      .endModificationQuery();
  }

  public int delete(Account example) throws DynamicExpressionException, SQLException {
    ParameterContext context = this.assembler.newParameterContext();
    context.add("e", example);
    PreparedModificationQuery preparedQuery = this.deleteByExample.prepare(context);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    }
  }

  // DELETE BY CRITERIA

  public DeleteWherePhase delete(final AccountTable from, final GeneralBooleanExpression predicate) {
    return new DeleteWherePhase(this.context, from, predicate);
  }

  // ORDER BY

  public enum AccountOrderBy implements OrderBy {

    ID("id", true),
    ID$DESC("id", false),
    NAME("name", true),
    NAME$DESC("name", false),
    TYPE("type", true),
    TYPE$DESC("type", false),
    BALANCE("balance", true),
    BALANCE$DESC("balance", false);

    private String sqlColumnName;
    private boolean ascending;

    private AccountOrderBy(String sqlColumnName, boolean ascending) {
      this.sqlColumnName = sqlColumnName;
      this.ascending = ascending;
    }

    public String getSQLColumnName() {
      return this.sqlColumnName;
    }

    public boolean isAscending() {
      return this.ascending;
    }

  }

  // Database class org.hotrod.runtime.livesql.metadata.Table metadata

  public AccountTable newTable() {
    return new AccountTable();
  }

  public AccountTable newTable(final String alias) {
    return new AccountTable(alias);
  }

  public static class AccountTable extends Table {

    // Properties

    public final NumberEntityColumn id = new NumberEntityColumn(this,
      "id", "id", "int4", 10, 0, TypeHandler.of(Integer.class, TypeSource.ENTITY_COLUMN));
    public final StringEntityColumn name = new StringEntityColumn(this,
      "name", "name", "varchar", 20, 0, TypeHandler.of(String.class, TypeSource.ENTITY_COLUMN));
    public final StringEntityColumn type = new StringEntityColumn(this,
      "type", "type", "varchar", 3, 0, TypeHandler.of(String.class, TypeSource.ENTITY_COLUMN));
    public final NumberEntityColumn balance = new NumberEntityColumn(this,
      "balance", "balance", "int4", 10, 0, TypeHandler.of(Integer.class, TypeSource.ENTITY_COLUMN));

    // Getters

    public AllColumns star() {
      return new AllColumns(this.id, this.name, this.type, this.balance);
    }

    // Constructors

    AccountTable() {
      super(null, null, Name.of("account", false), "Table", null);
      initialize();
    }

    AccountTable(final String alias) {
      super(null, null, Name.of("account", false), "Table", alias);
      initialize();
    }

    // Initialization

    private void initialize() {
      super.columns = new ArrayList<>();
      super.columns.add(this.id);
      super.columns.add(this.name);
      super.columns.add(this.type);
      super.columns.add(this.balance);
    }

  }

  @PostConstruct
  public void initializeContext() {
    this.context = new LiveSQLContext(this.liveSQLDialect, this.dataSource, new TypeSolver(null, this.liveSQLDialect));
    this.assembler = this.assemblerBean.getAssembler();
    this.initializeSelectbyprimarykey();
    this.initializeSelectbyexample();
    this.initializeInsert();
    this.initializeInsertbyexample();
    this.initializeUpdatebypk();
    this.initializeUpdatebyexample();
    this.initializeDeletebypk();
    this.initializeDeletebyexample();
  }

  private void logQuery(PreparedQuery preparedQuery) {
    if (log.isLoggable(Level.FINER)) {
      log.finer("SQL: " + preparedQuery.getPreview(true));
    } else if (log.isLoggable(Level.FINE)) {
      log.fine("SQL: " + preparedQuery.getPreview());
    }
  }

}
