// Generated by HotRod 5.1.12-SNAPSHOT on Feb 26, 2026 at 20:27:41

package app.persistence.dao;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.hotrod.dynamicsql.DynamicInsertQuery;
import org.hotrod.dynamicsql.DynamicModificationQuery;
import org.hotrod.dynamicsql.DynamicSelectQuery;
import org.hotrod.dynamicsql.Parameters;
import org.hotrod.dynamicsql.PreparedModificationQuery;
import org.hotrod.dynamicsql.PreparedQuery;
import org.hotrod.dynamicsql.PreparedSelectQuery;
import org.hotrod.dynamicsql.RowReader;
import org.hotrod.dynamicsql.assembler.DynamicSQL;
import org.hotrod.dynamicsql.insert.PreparedInsertQuery;
import org.hotrod.dynamicsql.insert.PrimaryKeyRetrievalMode;
import org.hotrod.exceptions.PersistenceException;
import org.hotrod.interfaces.OrderBy;
import org.hotrod.livesql.LShield;
import org.hotrod.livesql.LiveSQL;
import org.hotrod.livesql.LiveSQLLogging;
import org.hotrod.livesql.dialects.LiveSQLDialect;
import org.hotrod.livesql.metadata.AllColumns;
import org.hotrod.livesql.metadata.CharEntityColumn;
import org.hotrod.livesql.metadata.CharEntityColumnMetaData;
import org.hotrod.livesql.metadata.Name;
import org.hotrod.livesql.metadata.NumericEntityColumn;
import org.hotrod.livesql.metadata.NumericEntityColumnMetaData;
import org.hotrod.livesql.metadata.Table;
import org.hotrod.livesql.queries.DeleteWherePhase;
import org.hotrod.livesql.queries.LiveSQLContext;
import org.hotrod.livesql.queries.UpdateSetCompletePhase.Setter;
import org.hotrod.livesql.queries.UpdateWherePhase;
import org.hotrod.livesql.queries.select.CriteriaWherePhase;
import org.hotrod.livesql.queries.typesolver.RuntimeTypeSolver;
import org.hotrod.livesql.queries.typesolver.TypeHandler;
import org.hotrod.livesql.queries.typesolver.TypeSource;
import org.hotrod.livesql.util.CastUtil;
import org.hotrod.runtime.livesql.expressions.predicates.Predicate;
import org.hotrod.utils.SQLUtil;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

import app.persistence.layout.LocalHouseLayout;
import app.persistence.model.LocalHouse;

@Component
public class LocalHouseDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  private static final Logger log = Logger.getLogger(LocalHouseDAO.class.getName());

  private static final LiveSQLLogging livesql_log = LiveSQLLogging.of(
      () -> log.isLoggable(Level.FINE), msg -> log.fine(msg),
      () -> log.isLoggable(Level.FINER), msg -> log.finer(msg)
    );

  @Autowired
  private DataSource dataSource;

  @Autowired
  private LiveSQL sql;

  private DynamicSQL dyn;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  private LiveSQLContext context;

  // ROW READER

  private final RowReader<LocalHouse> rowReader = new RowReader<LocalHouse>() {

    @Override
    public LocalHouse readRowFrom(ResultSet rs, Connection conn) throws SQLException {
      LocalHouse row = applicationContext.getBean(LocalHouse.class);

      Long col1 = rs.getLong("ID"); // ID
      if (rs.wasNull()) col1 = null;
      row.setId(col1);

      String col2 = rs.getString("ADDRESS"); // ADDRESS
      row.setAddress(col2);

      return row;
    }

  };

  // PARSE ROW

  public LocalHouse parseRow(Map<String, Object> row) {
    return parseRow(row, null, null);
  }

  public LocalHouse parseRow(Map<String, Object> row, String prefix) {
    return parseRow(row, prefix, null);
  }

  public LocalHouse parseRow(Map<String, Object> row, String prefix, String suffix) {
    LocalHouse m = applicationContext.getBean(LocalHouse.class);
    String p = prefix == null ? "": prefix;
    String s = suffix == null ? "": suffix;
    m.setId(CastUtil.toLong((Number) row.get(p + "id" + s)));
    m.setAddress((String) row.get(p + "address" + s));
    return m;
  }

  // BASELINE

  public class LocalHouseBaseline {

    private Long id;
    private String address;

    public Long getId() {
      return this.id;
    }

    public String getAddress() {
      return this.address;
    }

  }

  public LocalHouseBaseline baseline(LocalHouse model) {
    LocalHouseBaseline b = new LocalHouseBaseline();
    b.id = model.getId();
    b.address = model.getAddress();
    return b;
  };

  // CLONE

  public LocalHouse clone(LocalHouseLayout layout) {
    LocalHouse m = this.applicationContext.getBean(LocalHouse.class);
    m.setId(layout.getId());
    m.setAddress(layout.getAddress());
    return m;
  };

  // SELECT BY PRIMARY KEY

  private DynamicSelectQuery selectByPrimaryKey;

  private void initializeSelectbyprimarykey() {
    this.selectByPrimaryKey = dyn
      .literaln("SELECT")
      .literaln("  id,")
      .literaln("  address")
      .literaln("FROM \"LOCAL_House\"")
      .literal("WHERE id = ").parameter("f.id").literaln()
      .endSelectQuery();
  }

  public LocalHouse select(Long id) {
    if (id == null) return null;
    LocalHouse filter = new LocalHouse();
    filter.setId(id);
    Parameters params = this.dyn.newParameters();
    params.add("f", filter);
    PreparedSelectQuery<LocalHouse> preparedQuery = this.selectByPrimaryKey.prepare(params, this.rowReader);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<LocalHouse> rows = preparedQuery.execute(conn);
      if (rows.size() == 0) return null;
      if (rows.size() == 1) return rows.get(0);
      throw new PersistenceException("A single row at most was expected but received " + rows.size() + " rows.");
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // SELECT BY EXAMPLE

  private DynamicSelectQuery selectByExample;

  private void initializeSelectbyexample() {
    this.selectByExample = dyn
      .literaln("SELECT")
      .literaln("  id,")
      .literaln("  address")
      .literaln("FROM \"LOCAL_House\"")
      .where("AND")
        .if_("e.id != null").literal("id = ").parameter("e.id").endif()
        .if_("e.address != null").literal("address = ").parameter("e.address").endif()
      .endwhere()
      .parameterInjection("ordering")
      .endSelectQuery();
  }

  public List<LocalHouse> select(LocalHouseLayout example, LocalHouseOrderBy... orderBies) {
    Parameters params = this.dyn.newParameters();
    params.add("e", example);
    String ordering = SQLUtil.render(orderBies);
    params.add("ordering", ordering);
    PreparedSelectQuery<LocalHouse> preparedQuery = this.selectByExample.prepare(params, this.rowReader);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<LocalHouse> rows = preparedQuery.execute(conn);
      return rows;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // SELECT BY CRITERIA

  public CriteriaWherePhase<LocalHouse> select(final LocalHouseTable from, final Predicate predicate) {
    return new CriteriaWherePhase<LocalHouse>(this.context, from, predicate, this.rowReader, livesql_log);
  }

  // INSERT

  private DynamicInsertQuery insert;

  private void initializeInsert() {
    this.insert = dyn
      .literal("INSERT INTO \"LOCAL_House\"")
      .trim(" (\n  ", ",\n  ", "\n) ")
        .literal("id")
        .literal("address")
      .endtrim()
      .literal("VALUES")
      .trim(" (\n  ", ",\n  ", "\n)")
        .parameterNullable("l.id", Types.BIGINT)
        .parameterNullable("l.address", Types.VARCHAR)
      .endtrim()
      .endInsertQuery(PrimaryKeyRetrievalMode.NO_RETRIEVAL);
  }

  public LocalHouse insert(LocalHouseLayout layout) {
    Parameters params = this.dyn.newParameters();
    params.add("l", layout);
    PreparedInsertQuery preparedQuery = this.insert.prepare(params);
    logQuery(preparedQuery);
    LocalHouse model = this.clone(layout);
    try (Connection conn = this.dataSource.getConnection()) {
      preparedQuery.execute(conn);
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
    return model;
  }

  // INSERT BY EXAMPLE

  private DynamicInsertQuery insertByExample;

  private void initializeInsertbyexample() {
    this.insertByExample = dyn
      .literal("INSERT INTO \"LOCAL_House\"")
      .trim(" (\n  ", ",\n  ", "\n) ")
        .if_("e.id != null").literal("id").endif()
        .if_("e.address != null").literal("address").endif()
      .endtrim()
      .literal("VALUES")
      .trim(" (\n  ", ",\n  ", "\n)")
        .if_("e.id != null").parameter("e.id").endif()
        .if_("e.address != null").parameter("e.address").endif()
      .endtrim()
      .endInsertQuery(PrimaryKeyRetrievalMode.NO_RETRIEVAL);
  }

  public LocalHouse insertByExample(LocalHouseLayout example) {
    Parameters params = this.dyn.newParameters();
    params.add("e", example);
    PreparedInsertQuery preparedQuery = this.insertByExample.prepare(params);
    logQuery(preparedQuery);
    LocalHouse model = this.clone(example);
    try (Connection conn = this.dataSource.getConnection()) {
      preparedQuery.execute(conn);
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
    return model;
  }

  // UPDATE BY PRIMARY KEY

  private DynamicModificationQuery updateByPK;

  private void initializeUpdatebypk() {
    this.updateByPK = dyn
      .literaln("UPDATE \"LOCAL_House\"")
      .literaln("SET")
      .literal("  id = ").parameterNullable("m.id", Types.BIGINT).literaln(",")
      .literal("  address = ").parameterNullable("m.address", Types.VARCHAR).literaln()
      .literal("WHERE id = ").parameter("m.id").literaln()
    .endModificationQuery();
  }

  public int update(LocalHouse model) {
    if (model.getId() == null) return 0;
    Parameters params = this.dyn.newParameters();
    params.add("m", model);
    PreparedModificationQuery preparedQuery = this.updateByPK.prepare(params);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // UPDATE BY EXAMPLE

  private DynamicModificationQuery updateByExample;

  private void initializeUpdatebyexample() {
    this.updateByExample = dyn
      .literal("UPDATE \"LOCAL_House\"")
      .set()
        .if_("v.id != null").literal("id = ").parameter("v.id").endif()
        .if_("v.address != null").literal("address = ").parameter("v.address").endif()
      .endset()
      .where("AND")
        .if_("e.id != null").literal("id = ").parameter("e.id").endif()
        .if_("e.address != null").literal("address = ").parameter("e.address").endif()
      .endwhere()
      .endModificationQuery();
  }

  public int update(LocalHouseLayout example, LocalHouseLayout values) {
    Parameters params = this.dyn.newParameters();
    params.add("e", example);
    params.add("v", values);
    PreparedModificationQuery preparedQuery = this.updateByExample.prepare(params);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // UPDATE BY CRITERIA

  public UpdateWherePhase update(LocalHouseLayout values, LocalHouseTable tableOrView,
      final Predicate predicate) {
    List<Setter> setters = new ArrayList<>();
    if (values.getId() != null) setters.add(new Setter(tableOrView.id, sql.val(values.getId())));
    if (values.getAddress() != null) setters.add(new Setter(tableOrView.address, sql.val(values.getAddress())));
    return new UpdateWherePhase(this.context, tableOrView, setters, predicate, livesql_log);
  }

  // DELETE BY PRIMARY KEY

  private DynamicModificationQuery deleteByPK;

  private void initializeDeletebypk() {
    this.deleteByPK = dyn
      .literaln("DELETE FROM \"LOCAL_House\"")
      .literal("WHERE id = ").parameter("f.id").literaln()
      .endModificationQuery();
  }

  public int delete(Long id) {
    if (id == null) return 0;
    LocalHouse filter = new LocalHouse();
    filter.setId(id);
    Parameters params = this.dyn.newParameters();
    params.add("f", filter);
    PreparedModificationQuery preparedQuery = this.deleteByPK.prepare(params);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // DELETE BY EXAMPLE

  private DynamicModificationQuery deleteByExample;

  private void initializeDeletebyexample() {
    this.deleteByExample = dyn
      .literaln("DELETE FROM \"LOCAL_House\"")
      .where("AND")
        .if_("e.id != null").literal("id = ").parameter("e.id").endif()
        .if_("e.address != null").literal("address = ").parameter("e.address").endif()
      .endwhere()
      .endModificationQuery();
  }

  public int delete(LocalHouseLayout example) {
    Parameters params = this.dyn.newParameters();
    params.add("e", example);
    PreparedModificationQuery preparedQuery = this.deleteByExample.prepare(params);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      int count = preparedQuery.execute(conn);
      return count;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // DELETE BY CRITERIA

  public DeleteWherePhase delete(final LocalHouseTable from, final Predicate predicate) {
    return new DeleteWherePhase(this.context, from, predicate, livesql_log);
  }

  // ORDER BY

  public enum LocalHouseOrderBy implements OrderBy {

    ID("id", true),
    ID$DESC("id", false),
    ADDRESS("address", true),
    ADDRESS$DESC("address", false);

    private String sqlColumnName;
    private boolean ascending;

    private LocalHouseOrderBy(String sqlColumnName, boolean ascending) {
      this.sqlColumnName = sqlColumnName;
      this.ascending = ascending;
    }

    @Override
    public String getSQLColumnName() {
      return this.sqlColumnName;
    }

    @Override
    public boolean isAscending() {
      return this.ascending;
    }

  }

  // TABLE METADATA

  public LocalHouseTable newTable() {
    return new LocalHouseTable();
  }

  public LocalHouseTable newTable(final String alias) {
    return new LocalHouseTable(alias);
  }

  public static class LocalHouseTable extends Table<LocalHouse> {

    private static final NumericEntityColumnMetaData _ID = new NumericEntityColumnMetaData(
      "ID", "id", "BIGINT", 64, 0, TypeHandler.forClass(Long.class, TypeSource.STATIC_DIALECT_RULE, "D10"));
    private static final CharEntityColumnMetaData _ADDRESS = new CharEntityColumnMetaData(
      "ADDRESS", "address", "CHARACTER VARYING", 100, 0, TypeHandler.forClass(String.class, TypeSource.STATIC_DIALECT_RULE, "D14"));

    public final NumericEntityColumn id = new NumericEntityColumn(this, _ID);
    public final CharEntityColumn address = new CharEntityColumn(this, _ADDRESS);

    @Override
    public AllColumns star() {
      return new AllColumns(this.id, this.address);
    }

    LocalHouseTable() {
      super(null, null, Name.of("LOCAL_House", true), "Table", null, LocalHouseLayout.class, LocalHouse.class);
      initialize();
    }

    LocalHouseTable(final String alias) {
      super(null, null, Name.of("LOCAL_House", true), "Table", alias, LocalHouseLayout.class, LocalHouse.class);
      initialize();
    }

    private void initialize() {
      super.columns = new ArrayList<>();
      super.columns.add(this.id);
      super.columns.add(this.address);
    }

  }

  // GETTERS

  public DataSource getDataSource() {
    return this.dataSource;
  }

  // INTERNAL METHODS

  @PostConstruct
  private void initializeContext() {
    LiveSQLDialect liveSQLDialect = LShield.getLiveSQLDialect(this.sql);
    this.context = new LiveSQLContext(liveSQLDialect, this.dataSource, new RuntimeTypeSolver(null, liveSQLDialect));
    this.dyn = new DynamicSQL();
    this.initializeSelectbyprimarykey();
    this.initializeSelectbyexample();
    this.initializeInsert();
    this.initializeInsertbyexample();
    this.initializeUpdatebypk();
    this.initializeUpdatebyexample();
    this.initializeDeletebypk();
    this.initializeDeletebyexample();
  }

  private void logQuery(PreparedQuery preparedQuery) {
    if (log.isLoggable(Level.FINER)) {
      log.finest("SQL:\n" + preparedQuery.getPreview(true));
    } else if (log.isLoggable(Level.FINE)) {
      log.fine("SQL:\n" + preparedQuery.getPreview());
    }
  }

}
