// Autogenerated by HotRod -- Do not edit.

package app.persistence.dao;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.hotrod.dynamicsql.DynamicExpressionException;
import org.hotrod.dynamicsql.DynamicSelectQuery;
import org.hotrod.dynamicsql.Parameters;
import org.hotrod.dynamicsql.PreparedQuery;
import org.hotrod.dynamicsql.PreparedSelectQuery;
import org.hotrod.dynamicsql.RowReader;
import org.hotrod.dynamicsql.assembler.DynamicSQL;
import org.hotrod.exceptions.PersistenceException;
import org.hotrod.livesql.LShield;
import org.hotrod.livesql.LiveSQL;
import org.hotrod.livesql.dialects.LiveSQLDialect;
import org.hotrod.livesql.queries.LiveSQLContext;
import org.hotrod.livesql.queries.typesolver.TypeSolver;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

import app.persistence.model.BigAccount;

@Component
public class SalesDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  private static final Logger log = Logger.getLogger(SalesDAO.class.getName());

  @Autowired
  private DataSource dataSource;

  @Autowired
  private LiveSQL sql;

  private DynamicSQL dyn;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  @SuppressWarnings("unused")
  private LiveSQLContext context;

  // SEQUENCE ROW READER

  private final RowReader<Long> sequenceRowReader = new RowReader<Long>() {

    @Override
    public Long readRowFrom(ResultSet rs, Connection conn) throws SQLException {
      Long col1 = rs.getLong(1);
      if (rs.wasNull())
        col1 = null;
      return col1;
    }

  };

  // SELECT SEQUENCE

  private DynamicSelectQuery selectSequence0;

  private void initializeSelectSequence0() {
    this.selectSequence0 = dyn.literaln("SELECT NEXT VALUE FOR hired_seq").endSelectQuery();
  }

  public long getHiredNextValue() {
    Parameters context = this.dyn.newParameters();
    PreparedSelectQuery<Long> preparedQuery = this.selectSequence0.prepare(context, this.sequenceRowReader);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      long value = preparedQuery.executeOne(conn);
      return value;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // NITRO SELECT: findBigAccounts

  private DynamicSelectQuery select0;

  private void initializeSelect0() {
    this.select0 = dyn.literal("\n       ").literal(
        "\nselect id, balance as ibt_balance,\n  case when active then 'Active' else 'Inactive' end as status,\n  cast(case when type = 'CHK' then balance * 1.5 else balance * 1.2 end as int) as score\nfrom account\nwhere balance >= 200\n    ")
        .endSelectQuery();
  }

  public final class RowReader0 implements RowReader<BigAccount> {

    private boolean present1 = false;
    private boolean present2 = false;
    private boolean present3 = false;
    private boolean present4 = false;

    @Override
    public void discoverColumns(ResultSet rs) throws SQLException {
      ResultSetMetaData m = rs.getMetaData();
      present1 = false;
      present2 = false;
      present3 = false;
      present4 = false;
      int n = m.getColumnCount();
      for (int i = 1; i <= n; i++) {
        String l = m.getColumnLabel(i);
        if ("ID".equals(l))
          present1 = true;
        if ("IBT_BALANCE".equals(l))
          present2 = true;
        if ("STATUS".equals(l))
          present3 = true;
        if ("SCORE".equals(l))
          present4 = true;
      }
    }

    @Override
    public BigAccount readRowFrom(ResultSet rs, Connection conn) throws SQLException {
      BigAccount row = applicationContext.getBean(BigAccount.class);

      if (this.present1) {
        Integer col1 = rs.getInt("ID"); // ID
        if (rs.wasNull())
          col1 = null;
        row.setId(col1);
      }

      if (this.present2) {
        Integer col2 = rs.getInt("IBT_BALANCE"); // IBT_BALANCE
        if (rs.wasNull())
          col2 = null;
        row.setGrossBalance(col2);
      }

      if (this.present3) {
        String col3 = rs.getString("STATUS"); // STATUS
        row.setStatus(col3);
      }

      if (this.present4) {
        Integer col4 = rs.getInt("SCORE"); // SCORE
        if (rs.wasNull())
          col4 = null;
        row.setScore(col4);
      }

      return row;
    }

  };

  public List<BigAccount> findBigAccounts() {
    Parameters context = this.dyn.newParameters();
    RowReader0 rr = new RowReader0();
    PreparedSelectQuery<BigAccount> preparedQuery = this.select0.prepare(context, rr);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<BigAccount> rows = preparedQuery.execute(conn);
      return rows;
    } catch (DynamicExpressionException | SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // GETTERS

  public DataSource getDataSource() {
    return this.dataSource;
  }

  // INTERNAL METHODS

  @PostConstruct
  public void initializeContext() {
    LiveSQLDialect liveSQLDialect = LShield.getLiveSQLDialect(this.sql);
    this.context = new LiveSQLContext(liveSQLDialect, this.dataSource, new TypeSolver(null, liveSQLDialect), log);
    this.dyn = new DynamicSQL();
    this.initializeSelectSequence0();
    this.initializeSelect0();
  }

  private void logQuery(PreparedQuery preparedQuery) {
    if (log.isLoggable(Level.FINER)) {
      log.finest("SQL:\n" + preparedQuery.getPreview(true));
    } else if (log.isLoggable(Level.FINE)) {
      log.fine("SQL:\n" + preparedQuery.getPreview());
    }
  }

}
