CREATE TABLE branch (
  id INT PRIMARY KEY NOT NULL,
  name VARCHAR(20),
  established DATE
);

INSERT INTO branch (id, name, established) VALUES
  (51, 'Central', date '2021-05-21'),
  (52, 'South', date '2022-02-22'),
  (54, 'North', date '2023-09-18'),
  (56, 'VIP', date '2024-10-12'),
  (57, 'Lakeside', date '2025-12-25');

CREATE TABLE employee (
  id INT GENERATED BY DEFAULT AS IDENTITY (start with 501) PRIMARY KEY NOT NULL,
  first_name VARCHAR(20),
  last_name VARCHAR(20),
  branch_id INT REFERENCES branch (id)
);

INSERT INTO employee (id, first_name, last_name, branch_id) VALUES
  (101457, 'Anne', 'Smith', 52),
  (609792, 'Steve', 'Locksmith', 56),
  (899288, 'Ronald', 'Kaminkow', 57),
  (134081, 'Alice', 'Badell', 51),
  (207121, 'Julia', 'Whitesmith', 52),
  (610043, 'John', 'Gardener', 54);
  
CREATE TABLE candidate (
  first_name VARCHAR(20),
  last_name VARCHAR(20),
  accepted INTEGER
);

INSERT INTO candidate (first_name, last_name, accepted) VALUES
  ('Marty', 'McFly', 1),
  ('Lorraine', 'Baines', 1),
  ('Biff', 'Tannen', 0),  
  ('Emmett', 'Brown', 1);  
  