//  Autogenerated by HotRod -- Do not edit.

package app.daos.reporting.primitives;

import java.io.Serializable;
import java.sql.Date;
import org.hotrod.json.JSONObject;

public class AbstractPaymentVO implements Serializable {

  private static final long serialVersionUID = 1L;

  // VO Properties (table columns)

  protected Date paymentDate = null;
  protected Integer invoiceId = null;
  protected Integer amount = null;

  // getters & setters

  public Date getPaymentDate() {
    return this.paymentDate;
  }

  public void setPaymentDate(final Date paymentDate) {
    this.paymentDate = paymentDate;
  }

  public Integer getInvoiceId() {
    return this.invoiceId;
  }

  public void setInvoiceId(final Integer invoiceId) {
    this.invoiceId = invoiceId;
  }

  public Integer getAmount() {
    return this.amount;
  }

  public void setAmount(final Integer amount) {
    this.amount = amount;
  }

  // to string

  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + "\n");
    sb.append("- paymentDate=" + this.paymentDate + "\n");
    sb.append("- invoiceId=" + this.invoiceId + "\n");
    sb.append("- amount=" + this.amount);
    return sb.toString();
  }

  // to JSON Object

  public JSONObject toJSONObject() {
    JSONObject obj = new JSONObject();
    obj.addProperty("paymentDate", this.paymentDate);
    obj.addProperty("invoiceId", this.invoiceId);
    obj.addProperty("amount", this.amount);
    return obj;
  }

  // to JSON String

  public String toJSON() {
    return toJSONObject().render();
  }

}
