// Autogenerated by HotRod -- Do not edit.

package app.persistence.dao;

import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.sql.DataSource;

import org.hotrod.dynamicsql.DynamicSelectQuery;
import org.hotrod.dynamicsql.Parameters;
import org.hotrod.dynamicsql.PreparedQuery;
import org.hotrod.dynamicsql.PreparedSelectQuery;
import org.hotrod.dynamicsql.RowReader;
import org.hotrod.dynamicsql.assembler.DynamicSQL;
import org.hotrod.exceptions.PersistenceException;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;

import app.persistence.model.FoundEmployee;

@Component
public class ReportsDAO implements Serializable, ApplicationContextAware {

  private static final long serialVersionUID = 1L;

  private static final Logger log = Logger.getLogger(ReportsDAO.class.getName());

  @Autowired
  private DataSource dataSource;

  private DynamicSQL dyn;

  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  // NITRO SELECT: findEmployees

  private DynamicSelectQuery select0;

  private void initializeSelect0() {
    this.select0 = dyn
      .literal("\n      ")
      .literal("\n      SELECT *\n      FROM employee\n      WHERE name LIKE '%' || ")
      .parameterNullable("txt", Types.VARCHAR)
      .literal(" || '%'\n    ")
      .endSelectQuery();
  }

  public final class RowReader0 implements RowReader<FoundEmployee> {

    private boolean present1 = false;
    private boolean present2 = false;

    @Override
    public void discoverColumns(ResultSet rs) throws SQLException {
      ResultSetMetaData m = rs.getMetaData();
      present1 = false;
      present2 = false;
      int n = m.getColumnCount();
      for (int i = 1; i <= n; i++) {
        String l = m.getColumnLabel(i);
        if ("ID".equals(l)) present1 = true;
        if ("NAME".equals(l)) present2 = true;
      }
    }

    @Override
    public FoundEmployee readRowFrom(ResultSet rs, Connection conn) throws SQLException {
      FoundEmployee row = applicationContext.getBean(FoundEmployee.class);

      if (this.present1) {
        Integer col1 = rs.getInt("ID"); // ID
        if (rs.wasNull()) col1 = null;
        row.setId(col1);
      }

      if (this.present2) {
        String col2 = rs.getString("NAME"); // NAME
        row.setName(col2);
      }

      return row;
    }

  };

  public List<FoundEmployee> findEmployees(String txt) {
    Parameters params = this.dyn.newParameters();
    params.add("txt", txt);
    RowReader0 rr = new RowReader0();
    PreparedSelectQuery<FoundEmployee> preparedQuery = this.select0.prepare(params, rr);
    logQuery(preparedQuery);
    try (Connection conn = this.dataSource.getConnection()) {
      List<FoundEmployee> rows = preparedQuery.execute(conn);
      return rows;
    } catch (SQLException e) {
      throw new PersistenceException(e);
    }
  }

  // GETTERS

  public DataSource getDataSource() {
    return this.dataSource;
  }

  // INTERNAL METHODS

  @PostConstruct
  private void initializeContext() {
    this.dyn = new DynamicSQL();
    this.initializeSelect0();
  }

  private void logQuery(PreparedQuery preparedQuery) {
    if (log.isLoggable(Level.FINER)) {
      log.finest("SQL:\n" + preparedQuery.getPreview(true));
    } else if (log.isLoggable(Level.FINE)) {
      log.fine("SQL:\n" + preparedQuery.getPreview());
    }
  }

}
