
-- generated keys

create table data (
  name varchar(20),
  active int
);

insert into data (name, active) values ('Alice', 1);
insert into data (name, active) values ('Anne', 0);
insert into data (name, active) values ('Alanis', 1);

create table k1 (
  id tinyint generated by default as identity (start with 40) primary key,
  name varchar(20)
);

create table k2 (
  id smallint generated by default as identity (start with 50) primary key,
  name varchar(20)
);

create table k3 (
  id int generated by default as identity (start with 60) primary key,
  name varchar(20)
);

create table k4 (
  id bigint generated by default as identity (start with 70) primary key,
  name varchar(20)
);

create sequence seq1 start with 51;

create table s1 (
  id tinyint primary key,
  name varchar(20)
);

create table s2 (
  id smallint primary key,
  name varchar(20)
);

create table s3 (
  id int primary key,
  name varchar(20)
);

create table s4 (
  id bigint primary key,
  name varchar(20)
);

create table t5 (
  id bigint primary key,
  name varchar(20)
);

-- name solver

create table "Local_House" (
  id bigint primary key,
  zip_code varchar(100), -- equivalent to: Zip_Code, ZIP_CODE
  "zip_code" varchar(100),
  "Zip_Code" varchar(100),
  name varchar(20)
);

create table local_house (
  id bigint primary key
);

create table "local_house" (
  id bigint primary key
);

insert into "local_house" (id) values (123), (456);

create view city_code as select * from "local_house";

create table pty_received_document (
  id bigint primary key,
  name varchar(20),
  received timestamp
);

-- blob

create table person (
  id bigint primary key,
  photo bytea   
);

insert into person (id, photo) values 
  (1, file_read('data/car.png'));
  
