// Generated by HotRod 5.1.16-SNAPSHOT on Mar 22, 2026 at 10:40:53

package app.persistence.model;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import app.persistence.dao.LocalHouseDAO;
import app.persistence.layout.LocalHouseLayout;

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class LocalHouse extends LocalHouseLayout {

  private static final long serialVersionUID = 1L;

  @SuppressWarnings("unused")
  @Autowired
  private LocalHouseDAO localHouseDAO;

  // Add custom code below.

}
