// Generated by HotRod 5.1.12-SNAPSHOT on Feb 24, 2026 at 07:25:20

package app.persistence.model;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import app.persistence.dao.PtyReceivedDocumentDAO;
import app.persistence.layout.PtyReceivedDocumentLayout;

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class PtyReceivedDocument extends PtyReceivedDocumentLayout {

  private static final long serialVersionUID = 1L;

  @SuppressWarnings("unused")
  @Autowired
  private PtyReceivedDocumentDAO ptyReceivedDocumentDAO;

  // Add custom code below.

}
