// Generated by HotRod 5.1.12-SNAPSHOT on Feb 26, 2026 at 20:38:09

package app.persistence.model;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import app.persistence.dao.ReceivedDocumentDAO;
import app.persistence.layout.ReceivedDocumentLayout;

@Component
@Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class ReceivedDocument extends ReceivedDocumentLayout {

  private static final long serialVersionUID = 1L;

  @SuppressWarnings("unused")
  @Autowired
  private ReceivedDocumentDAO receivedDocumentDAO;

  // Add custom code below.

}
