package org.hotrod.generator.mybatisspring;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Logger;

import org.hotrod.config.Constants;
import org.hotrod.config.HotRodFragmentConfigTag;
import org.hotrod.config.JDBCTag;
import org.hotrod.exceptions.ControlledException;
import org.hotrod.exceptions.UncontrolledException;
import org.hotrod.generator.DAOType;
import org.hotrod.generator.FileGenerator;
import org.hotrod.generator.FileGenerator.TextWriter;
import org.hotrod.generator.jdbc.DataSetLayout;
import org.hotrod.generator.jdbc.EnumClass;
import org.hotrod.json.JSONObject;
import org.hotrod.metadata.ColumnMetadata;
import org.hotrod.metadata.DataSetMetadata;
import org.hotrod.typesolver.UnresolvableDataTypeException;
import org.hotrod.utils.AbstractClassWriter.ExternalClass;
import org.hotrod.utils.ClassPackage;
import org.hotrod.utils.ClassWriter;
import org.nocrala.tools.lang.collector.listcollector.ListWriter;

public class ObjectAbstractVO {

  private static final Logger log = Logger.getLogger(ObjectAbstractVO.class.getName());

  private DataSetMetadata metadata;
  private DataSetLayout layout;
  private MyBatisSpringGenerator generator;
  private DAOType daoType;
  private JDBCTag myBatisTag;
  private HotRodFragmentConfigTag fragmentConfig;
  private ClassPackage fragmentPackage;

  private ClassPackage classPackage;

  private ClassWriter w;

  private String parentDAOProperty;
  private String parentVOProperty;

  // Constructor

  public ObjectAbstractVO(final DataSetMetadata metadata, final DataSetLayout layout,
      final MyBatisSpringGenerator generator, final DAOType daoType, final JDBCTag myBatisTag) {
    super();
    log.fine("init");

    this.metadata = metadata;
    this.layout = layout;
    this.generator = generator;
    if (daoType == null) {
      throw new RuntimeException("VOType cannot be null.");
    }
//    metadata.getDaoTag().addGeneratableObject(this);
    this.daoType = daoType;
    this.myBatisTag = myBatisTag;
    this.fragmentConfig = metadata.getFragmentConfig();
    this.fragmentPackage = this.fragmentConfig != null && this.fragmentConfig.getFragmentPackage() != null
        ? this.fragmentConfig.getFragmentPackage()
        : null;

    this.classPackage = this.layout.getDAOPrimitivePackage(this.fragmentPackage);
  }

  // Getters

  public void generate(final FileGenerator fileGenerator) throws UncontrolledException, ControlledException {

    String className = this.getClassName() + ".java";
    File dir = this.layout.getDaoPrimitivePackageDir(this.fragmentPackage);
    File f = new File(dir, className);

    ClassPackage cp = this.layout.getDAOPrimitivePackage(this.fragmentPackage);

    this.w = new ClassWriter(cp, "// Autogenerated by " + Constants.TOOL_NAME + " -- Do not edit.", "");

    try (TextWriter tw = fileGenerator.createWriter(f)) {

      writeClassHeader();

      writeProperties();

      writeGettersAndSetters();

      writeToString();

      writeToJSON();

      writeClassFooter();

      this.w.writeTo(tw);

    } catch (IOException e) {
      throw new UncontrolledException(
          "Could not generate DAO primitives class: could not write to file '" + f.getName() + "'.", e);
    } catch (UnresolvableDataTypeException e) {
      throw new ControlledException("Could not generate DAO primitives for table '" + e.getColumnMetadata().getTable()
          + "'. Could not handle columns '" + e.getColumnMetadata().getName() + "' type: "
          + e.getColumnMetadata().getTypeName());
    }

  }

  private void writeClassHeader() throws IOException {

    // Signature

//    if (this.getBundle().getParent() != null) {
//      w.println("public class " + this.getClassName() + " implements ", LazyParentClassLoading.class, ", ",
//          Serializable.class, " {");
//    } else {
    w.println("public class " + this.getClassName() + " implements ", Serializable.class, " {");
//    }

    w.println();

    // Serial Version UID

    w.println("  private static final long serialVersionUID = 1L;");
    w.println();

  }

  private void writeProperties() throws IOException, UnresolvableDataTypeException {

    w.println("  // VO Properties ("
        + (this.daoType == DAOType.TABLE ? "table" : this.daoType == DAOType.VIEW ? "view" : "select") + " columns)");
    w.println();
    writeColumnProperties(this.metadata.getColumns());

    // add parent DAO & VO if it extends another table

    log.fine("" + this.metadata.getId() + ": this.metadata.getParentMetadata()=" + this.metadata.getParentMetadata());

//    if (this.getBundle().getParent() != null) {
//      w.println("  // Parent DAO and VO (since this table extends another one)");
//      w.println();
//
//      String daoClassName = this.getBundle().getParent().getDAO().getClassName();
//      this.parentDAOProperty = this.toLowerInitial(daoClassName);
//      w.println("  @" + Const.AUTOWIRED);
//      w.println("  private ", ExternalClass.of(daoClassName), " " + this.parentDAOProperty + " = null;");
//
//      w.println();
//      String voClassName = this.getBundle().getParent().getVO().getClassName();
//      this.parentVOProperty = this.toLowerInitial(voClassName);
//      w.println("  private ", ExternalClass.of(voClassName), " " + this.parentVOProperty + " = null;");
//      w.println();
//    }

  }

  private void writeColumnProperties(final List<ColumnMetadata> columns) throws IOException {
    for (ColumnMetadata cm : columns) {
      String javaType = resolveType(cm);
      w.println("  protected ", ExternalClass.of(javaType), " " + cm.getId().getJavaMemberName() + " = null;");
    }
    w.println();
  }

  private String resolveType(final ColumnMetadata cm) {
    EnumClass ec = this.generator.getEnum(cm.getEnumMetadata());
    return ec != null ? ec.getFullClassName() : cm.getType().getJavaClassName();
  }

  private void writeGettersAndSetters() throws IOException, UnresolvableDataTypeException {

//    if (this.getBundle().getParent() != null) { // table that extends another one
//
//      ColumnMetadata pkm = this.metadata.getPK().getColumns().get(0);
//      {
//
//        w.println("  // PK getters & setters");
//        w.println();
//
//        String javaType = resolveType(pkm);
//        String m = pkm.getId().getJavaMemberName();
//        writeGetter(pkm, javaType, m);
//
//        String setter = pkm.getId().getJavaSetter();
//        w.println("  public void " + setter + "(final ", ExternalClass.of(javaType), " " + m + ") {");
//        w.println("    this.unloadSuperclass();");
//        w.println("    this." + m + " = " + m + ";");
//        w.println("  }");
//
//        w.println();
//        w.println("  @Override");
//        w.println("  public boolean isLoaded() {");
//        w.println("    return this." + this.parentVOProperty + " != null;");
//        w.println("  }");
//        w.println();
//        w.println("  @Override");
//        w.println("  public void unloadSuperclass() {");
//        w.println("    System.out.println(\">>> Unloading superclass...\");");
//        w.println("    this." + this.parentVOProperty + " = null;");
//        w.println("  }");
//        w.println();
//        w.println("  @Override");
//        w.println("  public void loadSuperclass() {");
//        w.println("    if (!this.isLoaded()) {");
//        w.println("      System.out.println(\">>> Loading superclass\");");
//        w.println("      this." + this.parentVOProperty + " = this." + this.parentDAOProperty + ".selectByPK(this." + m
//            + ");");
//        w.println("    }");
//        w.println("    else");
//        w.println("      System.out.println(\">>>Nothing to do...already loaded\");");
//        w.println("  }");
//        w.println();
//      }
//
//      w.println("  // Non-PK getters & setters");
//      w.println();
//
//      for (ColumnMetadata cm : this.metadata.getNonPkColumns()) {
//        String javaType = resolveType(cm);
//        String m = cm.getId().getJavaMemberName();
//        writeGetter(cm, javaType, m);
//        writeSetter(cm, javaType, m);
//      }
//
//      w.println("  // Parent getters & setters");
//      w.println();
//      for (ColumnMetadata cm : this.metadata.getParentMetadata().getNonPkColumns()) {
//        String javaType = resolveType(cm);
//        String m = cm.getId().getJavaMemberName();
//        writeParentGetter(cm, javaType, m);
//        writeParentSetter(cm, javaType, m);
//      }
//
//    } else { // traditional table without extends

    w.println("  // getters & setters");
    w.println();

    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String javaType = resolveType(cm);
      String m = cm.getId().getJavaMemberName();
      writeGetter(cm, javaType, m);
      writeSetter(cm, javaType, m);
    }

//    }

  }

  private void writeGetter(ColumnMetadata cm, String javaType, String m) throws IOException {
    w.println("  public ", ExternalClass.of(javaType), " " + cm.getId().getJavaGetter() + "() {");
    w.println("    return this." + m + ";");
    w.println("  }");
    w.println();
  }

  private void writeSetter(final ColumnMetadata cm, final String javaType, final String m) throws IOException {
    String setter = cm.getId().getJavaSetter();
    w.println("  public void " + setter + "(final ", ExternalClass.of(javaType), " " + m + ") {");
    w.println("    this." + m + " = " + m + ";");
    w.println("  }");
    w.println();
  }

  private void writeParentGetter(ColumnMetadata cm, String javaType, String m) throws IOException {
    w.println("  public ", ExternalClass.of(javaType), " " + cm.getId().getJavaGetter() + "() {");
    w.println("    return this." + this.parentVOProperty + "." + cm.getId().getJavaGetter() + "();");
    w.println("  }");
    w.println();
  }

  private void writeParentSetter(final ColumnMetadata cm, final String javaType, final String m) throws IOException {
    String setter = cm.getId().getJavaSetter();
    w.println("  public void " + setter + "(final ", ExternalClass.of(javaType), " " + m + ") {");
    w.println("    this." + this.parentVOProperty + "." + setter + "(" + m + ");");
    w.println("  }");
    w.println();
  }

  private void writeToString() throws IOException, UnresolvableDataTypeException {
    w.println("  // to string");
    w.println();

    w.println("  public String toString() {");
    w.println("    ", StringBuilder.class, " sb = new ", java.lang.StringBuilder.class, "();");

    if (this.myBatisTag.getProperties().isMultilineTostring()) {
      w.println("    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + \"\\n\");");

      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \"\\n\");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.metadata.getColumns()) {
        String prop = cm.getId().getJavaMemberName();
        lw.add("\"- " + prop + "=\" + this." + prop);
      }
      w.println(lw.toString());

    } else {
      w.println("    sb.append(\"[\");");

      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \", \");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.metadata.getColumns()) {
        String prop = cm.getId().getJavaMemberName();
        lw.add("\"" + prop + "=\" + this." + prop);
      }
      w.println(lw.toString());

      w.println("    sb.append(\"]\");");
    }

    w.println("    return sb.toString();");
    w.println("  }");
    w.println();

  }

  private void writeToJSON() throws IOException, UnresolvableDataTypeException {
    w.println("  // to JSON Object");
    w.println();

    w.println("  public ", JSONObject.class, " toJSONObject() {");
    w.println("    ", JSONObject.class, " obj = new ", JSONObject.class, "();");

    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String prop = cm.getId().getJavaMemberName();
      w.println("    obj.addProperty(\"" + prop + "\", " + "this." + prop + ");");
    }

    w.println("    return obj;");
    w.println("  }");
    w.println();

    w.println("  // to JSON String");
    w.println();
    w.println("  public String toJSON() {");
    w.println("    return toJSONObject().render();");
    w.println("  }");
    w.println();
  }

  private void writeClassFooter() throws IOException {
    w.println("}");
  }

  DataSetMetadata getMetadata() {
    return metadata;
  }

  // Identifiers & File Paths

  public String getFullClassName() {
    return this.classPackage.getFullClassName(getClassName());
  }

  public String getClassName() {
    return this.myBatisTag.getDaos().generateAbstractVOName(this.metadata.getId());
  }

  // Helpers

  private String toLowerInitial(final String txt) {
    if (txt == null || txt.length() < 1) {
      return txt;
    }
    return txt.substring(0, 1).toLowerCase() + txt.substring(1);
  }

}
