package org.hotrod.generator.mybatis;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import org.apache.log4j.Logger;
import org.hotrod.ant.Constants;
import org.hotrod.ant.ControlledException;
import org.hotrod.ant.UncontrolledException;
import org.hotrod.config.HotRodFragmentConfigTag;
import org.hotrod.config.MyBatisTag;
import org.hotrod.database.PropertyType;
import org.hotrod.exceptions.UnresolvableDataTypeException;
import org.hotrod.generator.DAOType;
import org.hotrod.metadata.ColumnMetadata;
import org.hotrod.metadata.DataSetMetadata;
import org.hotrod.runtime.util.ListWriter;
import org.hotrod.utils.ClassPackage;

public class ObjectAbstractVO {

  private static final Logger log = Logger.getLogger(ObjectAbstractVO.class);

  private DataSetMetadata metadata;
  private DataSetLayout layout;
  private DAOType type;
  private MyBatisTag myBatisTag;
  private HotRodFragmentConfigTag fragmentConfig;
  private ClassPackage fragmentPackage;

  private ClassPackage classPackage;

  private Writer w;

  // Constructor

  public ObjectAbstractVO(final DataSetMetadata metadata, final DataSetLayout layout, final DAOType type,
      final MyBatisTag myBatisTag) {
    log.debug("init");
    this.metadata = metadata;
    this.layout = layout;
    if (type == null) {
      throw new RuntimeException("VOType cannot be null.");
    }
    this.type = type;
    this.myBatisTag = myBatisTag;
    this.fragmentConfig = metadata.getFragmentConfig();
    this.fragmentPackage = this.fragmentConfig != null && this.fragmentConfig.getFragmentPackage() != null
        ? this.fragmentConfig.getFragmentPackage() : null;

    this.classPackage = this.layout.getDAOPrimitivePackage(this.fragmentPackage);
  }

  // Getters

  public void generate() throws UncontrolledException, ControlledException {

    String className = this.getClassName() + ".java";

    File dir = this.layout.getDaoPrimitivePackageDir(this.fragmentPackage);
    File f = new File(dir, className);

    this.w = null;

    try {
      this.w = new BufferedWriter(new FileWriter(f));

      writeClassHeader();

      writeProperties();

      writeGettersAndSetters();

      writeToString();

      writePropertiesChangeLog();

      writeClassFooter();

    } catch (IOException e) {
      throw new UncontrolledException(
          "Could not generate DAO primitives class: could not write to file '" + f.getName() + "'.", e);
    } catch (UnresolvableDataTypeException e) {
      throw new ControlledException("Could not generate DAO primitives for table '" + e.getTableName()
          + "'. Could not handle columns '" + e.getColumnName() + "' type: " + e.getTypeName());
    } finally {
      if (this.w != null) {
        try {
          this.w.close();
        } catch (IOException e) {
          throw new UncontrolledException(
              "Could not generate DAO primitives class: could not close file '" + f.getName() + "'.", e);
        }
      }
    }

  }

  private void writeClassHeader() throws IOException {

    // Comment

    println("// Autogenerated by " + Constants.TOOL_NAME + " -- Do not edit.");
    println();

    // Package

    println("package " + this.classPackage.getPackage() + ";");
    println();

    // Imports

    println("import java.io.Serializable;");
    println();

    // Signature

    println("public class " + this.getClassName() + " implements Serializable {");
    println();

    // Serial Version UID

    println("  private static final long serialVersionUID = 1L;");
    println();

  }

  private void writeProperties() throws IOException, UnresolvableDataTypeException {
    println("  // VO Properties ("
        + (this.type == DAOType.TABLE ? "table" : this.type == DAOType.VIEW ? "view" : "select") + " columns)");
    println();
    for (ColumnMetadata cm : this.metadata.getColumns()) {
      println("  protected " + cm.getType().getJavaClassName() + " " + cm.getIdentifier().getJavaMemberIdentifier()
          + " = null;" + (cm.getType().isLOB() ? " // it's a LOB type" : ""));
    }
    println();
  }

  private void writeGettersAndSetters() throws IOException, UnresolvableDataTypeException {
    println("  // getters & setters");
    println();

    for (ColumnMetadata cm : this.metadata.getColumns()) {
      PropertyType type = cm.getType();
      String m = cm.getIdentifier().getJavaMemberIdentifier();

      println("  public final " + type.getJavaClassName() + " " + cm.getIdentifier().getGetter() + "() {");
      println("    return this." + m + ";");
      println("  }");
      println();

      String setter = cm.getIdentifier().getSetter();
      writeSetter(cm, type, m, setter);

    }

  }

  private void writeSetter(final ColumnMetadata cm, final PropertyType type, final String m, final String setter)
      throws IOException {
    println("  public final void " + setter + "(final " + type.getJavaClassName() + " " + m + ") {");
    println("    this." + m + " = " + m + ";");
    String name = cm.getIdentifier().getJavaMemberIdentifier() + "WasSet";
    println("    this.propertiesChangeLog." + name + " = true;");

    println("  }");
    println();
  }

  private void writeToString() throws IOException, UnresolvableDataTypeException {
    println("  // to string");
    println();

    println("  public String toString() {");
    println("    java.lang.StringBuilder sb = new java.lang.StringBuilder();");

    if (this.myBatisTag.getProperties().isMultilineTostring()) {
      println("    sb.append( getClass().getName() + '@' + Integer.toHexString(hashCode()) + \"\\n\");");

      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \"\\n\");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.metadata.getColumns()) {
        String prop = cm.getIdentifier().getJavaMemberIdentifier();
        lw.add("\"" + prop + "=\" + this." + prop);
      }
      println(lw.toString());

    } else {
      println("    sb.append(\"[\");");

      String prefix = "";
      String elemPrefix = "    sb.append(";
      String elemSuffix = "";
      String separator = " + \", \");\n";
      String lastSeparator = separator;
      String suffix = ");";
      ListWriter lw = new ListWriter(prefix, elemPrefix, elemSuffix, separator, lastSeparator, suffix);
      for (ColumnMetadata cm : this.metadata.getColumns()) {
        String prop = cm.getIdentifier().getJavaMemberIdentifier();
        lw.add("\"" + prop + "=\" + this." + prop);
      }
      println(lw.toString());

      println("    sb.append(\"]\");");
    }

    println("    return sb.toString();");
    println("  }");
    println();

  }

  /**
   * <pre>
   * // Properties change log
   * 
   * private PropertiesChangeLog propertiesChangeLog = new PropertiesChangeLog();
   * 
   * public class PropertiesChangeLog {
   *   boolean idWasSet = false;
   *   boolean nameWasSet = false;
   *   boolean typeWasSet = false;
   *   boolean currentBalanceWasSet = false;
   *   boolean createdOnWasSet = false;
   * }
   * </pre>
   * 
   * @throws IOException
   */
  private void writePropertiesChangeLog() throws IOException {
    println("  // Properties change log");
    println();
    println("  public PropertiesChangeLog propertiesChangeLog = new PropertiesChangeLog();");
    println();
    println("  public class PropertiesChangeLog {");

    for (ColumnMetadata cm : this.metadata.getColumns()) {
      String name = cm.getIdentifier().getJavaMemberIdentifier() + "WasSet";
      println("    public boolean " + name + " = false;");
    }

    println("  }");
    println();

  }

  private void writeClassFooter() throws IOException {
    println("}");
  }

  // Identifiers & File Paths

  public String getFullClassName() {
    return this.classPackage.getFullClassName(getClassName());
  }

  public String getClassName() {
    return this.myBatisTag.getDaos().generateAbstractVOName(this.metadata.getIdentifier());
  }

  // Helpers

  private void print(final String txt) throws IOException {
    this.w.write(txt);
  }

  private void println(final String txt) throws IOException {
    this.w.write(txt);
    println();
  }

  private void println() throws IOException {
    this.w.write("\n");
  }

}
